## Finance DataSet

In [1]:
!pip install numpy

Requirement already satisfied: numpy in ./.venv/lib/python3.14/site-packages (2.5.3)

In [2]:
!pip install polars

Requirement already satisfied: polars in ./.venv/lib/python3.14/site-packages (1.44.2)
Requirement already satisfied: polars-runtime-32==1.44.2 in ./.venv/lib/python3.14/site-packages (from polars) (1.44.2)

In [5]:
# Creating DataFrame from a dict or a collection of dicts.
########################
## LOCATION DataFrame ##
########################

import polars as pl
import random
from datetime import datetime

location = pl.DataFrame({
    "ID": list(range(11, 23)),
    "AS_OF_DATE": datetime(2022, 1, 1),
    "DESCRIPTION" : ["Boston","New York","Philadelphia","Cleveland","Richmond",
                     "Atlanta","Chicago","St. Louis","Minneapolis","Kansas City",
                     "Dallas","San Francisco"],
    "REGION": ["Region A","Region B","Region C","Region D"] * 3,
    "TYPE" : "Physical",
    "CATEGORY" : ["Ship","Recv","Mfg"] * 4
})

location.sample(5).with_row_index("Row #")

shape: (5, 7)
┌───────┬─────┬─────────────────────┬───────────────┬──────────┬──────────┬──────────┐
│ Row # ┆ ID  ┆ AS_OF_DATE          ┆ DESCRIPTION   ┆ REGION   ┆ TYPE     ┆ CATEGORY │
│ ---   ┆ --- ┆ ---                 ┆ ---           ┆ ---      ┆ ---      ┆ ---      │
│ u32   ┆ i64 ┆ datetime[μs]        ┆ str           ┆ str      ┆ str      ┆ str      │
╞═══════╪═════╪═════════════════════╪═══════════════╪══════════╪══════════╪══════════╡
│ 0     ┆ 17  ┆ 2022-01-01 00:00:00 ┆ Chicago       ┆ Region C ┆ Physical ┆ Ship     │
│ 1     ┆ 22  ┆ 2022-01-01 00:00:00 ┆ San Francisco ┆ Region D ┆ Physical ┆ Mfg      │
│ 2     ┆ 12  ┆ 2022-01-01 00:00:00 ┆ New York      ┆ Region B ┆ Physical ┆ Recv     │
│ 3     ┆ 14  ┆ 2022-01-01 00:00:00 ┆ Cleveland     ┆ Region D ┆ Physical ┆ Ship     │
│ 4     ┆ 16  ┆ 2022-01-01 00:00:00 ┆ Atlanta       ┆ Region B ┆ Physical ┆ Mfg      │
└───────┴─────┴─────────────────────┴───────────────┴──────────┴──────────┴──────────┘

In [7]:
########################
## ACCOUNTS DataFrame ##
########################
import random
from datetime import datetime

accounts = pl.DataFrame({
    "ID":  list(range(10000, 45000, 1000)),
    "AS_OF_DATE" : datetime(2022, 1, 1),
    "DESCRIPTION" : ["Operating Expenses","Non Operating Expenses","Assets",
                     "Liabilities","Net worth accounts", "Statistical Accounts",
                     "Revenue"] * 5,
    "REGION": ["Region A","Region B","Region C","Region D", "Region E"] * 7,
    "TYPE" : ["E","E","A","L","N","S","R"] * 5,
    "STATUS" : "Active",
    "CLASSIFICATION" : ["OPERATING_EXPENSES","NON-OPERATING_EXPENSES", 
                        "ASSETS","LIABILITIES","NET_WORTH","STATISTICS",
                        "REVENUE"] * 5,
    "CATEGORY" : [
       		"Travel","Payroll","non-Payroll","Allowance","Cash",
       		"Facility","Supply","Services","Investment","Misc.",
       		"Depreciation","Gain","Service","Retired","Fault.",
       		"Receipt","Accrual","Return","Credit","ROI",
       		"Cash","Funds","Invest","Transfer","Roll-over",
       		"FTE","Members","Non_Members","Temp","Contractors",
       		"Sales","Merchant","Service","Consulting","Subscriptions"
       	],
})
accounts.sample(5).with_row_index("Row #")

shape: (5, 9)
┌───────┬───────┬────────────────┬────────────────┬───┬──────┬────────┬───────────────┬────────────┐
│ Row # ┆ ID    ┆ AS_OF_DATE     ┆ DESCRIPTION    ┆ … ┆ TYPE ┆ STATUS ┆ CLASSIFICATIO ┆ CATEGORY   │
│ ---   ┆ ---   ┆ ---            ┆ ---            ┆   ┆ ---  ┆ ---    ┆ N             ┆ ---        │
│ u32   ┆ i64   ┆ datetime[μs]   ┆ str            ┆   ┆ str  ┆ str    ┆ ---           ┆ str        │
│       ┆       ┆                ┆                ┆   ┆      ┆        ┆ str           ┆            │
╞═══════╪═══════╪════════════════╪════════════════╪═══╪══════╪════════╪═══════════════╪════════════╡
│ 0     ┆ 10000 ┆ 2022-01-01     ┆ Operating      ┆ … ┆ E    ┆ Active ┆ OPERATING_EXP ┆ Travel     │
│       ┆       ┆ 00:00:00       ┆ Expenses       ┆   ┆      ┆        ┆ ENSES         ┆            │
│ 1     ┆ 15000 ┆ 2022-01-01     ┆ Statistical    ┆ … ┆ S    ┆ Active ┆ STATISTICS    ┆ Facility   │
│       ┆       ┆ 00:00:00       ┆ Accounts       ┆   ┆      ┆        ┆               ┆            │
│ 2     ┆ 17000 ┆ 2022-01-01     ┆ Operating      ┆ … ┆ E    ┆ Active ┆ OPERATING_EXP ┆ Services   │
│       ┆       ┆ 00:00:00       ┆ Expenses       ┆   ┆      ┆        ┆ ENSES         ┆            │
│ 3     ┆ 18000 ┆ 2022-01-01     ┆ Non Operating  ┆ … ┆ E    ┆ Active ┆ NON-OPERATING ┆ Investment │
│       ┆       ┆ 00:00:00       ┆ Expenses       ┆   ┆      ┆        ┆ _EXPENSES     ┆            │
│ 4     ┆ 14000 ┆ 2022-01-01     ┆ Net worth      ┆ … ┆ N    ┆ Active ┆ NET_WORTH     ┆ Cash       │
│       ┆       ┆ 00:00:00       ┆ accounts       ┆   ┆      ┆        ┆               ┆            │
└───────┴───────┴────────────────┴────────────────┴───┴──────┴────────┴───────────────┴────────────┘

In [8]:
##########################
## DEPARTMENT DataFrame ##
##########################
import random
from datetime import datetime

dept = pl.DataFrame({
    "ID":  list(range(1000, 2500, 100)),
    "AS_OF_DATE" : datetime(2022, 1, 1),
    "DESCRIPTION" : ["Sales & Marketing","Human Resource",
                     "Information Technology","Business leaders","other temp"] * 3,
    "REGION": ["Region A","Region B","Region C"] * 5,
    "STATUS" : "Active",
    "CLASSIFICATION" : ["SALES","HR", "IT","BUSINESS","OTHERS"] * 3,
    "TYPE" : ["S","H","I","B","O"] * 3,
    "CATEGORY" : ["sales","human_resource","IT_Staff","business","others"] * 3,
})
dept.sample(5).with_row_index("Row #")

shape: (5, 9)
┌───────┬──────┬───────────────┬───────────────┬───┬────────┬───────────────┬──────┬───────────────┐
│ Row # ┆ ID   ┆ AS_OF_DATE    ┆ DESCRIPTION   ┆ … ┆ STATUS ┆ CLASSIFICATIO ┆ TYPE ┆ CATEGORY      │
│ ---   ┆ ---  ┆ ---           ┆ ---           ┆   ┆ ---    ┆ N             ┆ ---  ┆ ---           │
│ u32   ┆ i64  ┆ datetime[μs]  ┆ str           ┆   ┆ str    ┆ ---           ┆ str  ┆ str           │
│       ┆      ┆               ┆               ┆   ┆        ┆ str           ┆      ┆               │
╞═══════╪══════╪═══════════════╪═══════════════╪═══╪════════╪═══════════════╪══════╪═══════════════╡
│ 0     ┆ 1800 ┆ 2022-01-01    ┆ Business      ┆ … ┆ Active ┆ BUSINESS      ┆ B    ┆ business      │
│       ┆      ┆ 00:00:00      ┆ leaders       ┆   ┆        ┆               ┆      ┆               │
│ 1     ┆ 2400 ┆ 2022-01-01    ┆ other temp    ┆ … ┆ Active ┆ OTHERS        ┆ O    ┆ others        │
│       ┆      ┆ 00:00:00      ┆               ┆   ┆        ┆               ┆      ┆               │
│ 2     ┆ 1000 ┆ 2022-01-01    ┆ Sales &       ┆ … ┆ Active ┆ SALES         ┆ S    ┆ sales         │
│       ┆      ┆ 00:00:00      ┆ Marketing     ┆   ┆        ┆               ┆      ┆               │
│ 3     ┆ 1100 ┆ 2022-01-01    ┆ Human         ┆ … ┆ Active ┆ HR            ┆ H    ┆ human_resourc │
│       ┆      ┆ 00:00:00      ┆ Resource      ┆   ┆        ┆               ┆      ┆ e             │
│ 4     ┆ 1400 ┆ 2022-01-01    ┆ other temp    ┆ … ┆ Active ┆ OTHERS        ┆ O    ┆ others        │
│       ┆      ┆ 00:00:00      ┆               ┆   ┆        ┆               ┆      ┆               │
└───────┴──────┴───────────────┴───────────────┴───┴────────┴───────────────┴──────┴───────────────┘

In [9]:
######################
## LEDGER DataFrame ##
######################
import random
from datetime import datetime

sampleSize = 100_000
org = "ABC Inc."
ledger_type = "ACTUALS" # BUDGET, STATS are other Ledger types
fiscal_year_from = 2020
fiscal_year_to = 2023
random.seed(123)

ledger = pl.DataFrame({
	"LEDGER" : ledger_type,
	"ORG" : org,
	"FISCAL_YEAR": random.choices(list(range(fiscal_year_from, 
                                          fiscal_year_to+1, 1)),k=sampleSize),
	"PERIOD": random.choices(list(range(1, 12+1, 1)),k=sampleSize),
	"ACCOUNT" : random.choices(accounts["ID"], k=sampleSize),
	"DEPT" : random.choices(dept["ID"], k=sampleSize),
	"LOCATION" : random.choices(location["ID"], k=sampleSize),
	"POSTED_TOTAL": random.sample(range(1000000), sampleSize)
})
ledger.sample(5).with_row_index("Row #")

shape: (5, 9)
┌───────┬─────────┬──────────┬─────────────┬───┬─────────┬──────┬──────────┬──────────────┐
│ Row # ┆ LEDGER  ┆ ORG      ┆ FISCAL_YEAR ┆ … ┆ ACCOUNT ┆ DEPT ┆ LOCATION ┆ POSTED_TOTAL │
│ ---   ┆ ---     ┆ ---      ┆ ---         ┆   ┆ ---     ┆ ---  ┆ ---      ┆ ---          │
│ u32   ┆ str     ┆ str      ┆ i64         ┆   ┆ i64     ┆ i64  ┆ i64      ┆ i64          │
╞═══════╪═════════╪══════════╪═════════════╪═══╪═════════╪══════╪══════════╪══════════════╡
│ 0     ┆ ACTUALS ┆ ABC Inc. ┆ 2022        ┆ … ┆ 15000   ┆ 2300 ┆ 20       ┆ 162981       │
│ 1     ┆ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ … ┆ 30000   ┆ 1800 ┆ 19       ┆ 32238        │
│ 2     ┆ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ … ┆ 41000   ┆ 2100 ┆ 16       ┆ 409304       │
│ 3     ┆ ACTUALS ┆ ABC Inc. ┆ 2022        ┆ … ┆ 26000   ┆ 1500 ┆ 21       ┆ 806754       │
│ 4     ┆ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ … ┆ 21000   ┆ 1000 ┆ 20       ┆ 805108       │
└───────┴─────────┴──────────┴─────────────┴───┴─────────┴──────┴──────────┴──────────────┘

In [11]:
ledger_type = "BUDGET" # ACTUALS, STATS are other Ledger types

ledger_budg = pl.DataFrame({
	"LEDGER" : ledger_type,
	"ORG" : org,
	"FISCAL_YEAR": random.choices(list(range(fiscal_year_from, fiscal_year_to+1, 1))
                               ,k=sampleSize),
	"PERIOD": random.choices(list(range(1, 12+1, 1)),k=sampleSize),
	"ACCOUNT" : random.choices(accounts["ID"], k=sampleSize),
	"DEPT" : random.choices(dept["ID"], k=sampleSize),
	"LOCATION" : random.choices(location["ID"], k=sampleSize),
	"POSTED_TOTAL": random.sample(range(1000000), sampleSize)
})
ledger_budg.sample(5).with_row_index("Row #")

shape: (5, 9)
┌───────┬────────┬──────────┬─────────────┬───┬─────────┬──────┬──────────┬──────────────┐
│ Row # ┆ LEDGER ┆ ORG      ┆ FISCAL_YEAR ┆ … ┆ ACCOUNT ┆ DEPT ┆ LOCATION ┆ POSTED_TOTAL │
│ ---   ┆ ---    ┆ ---      ┆ ---         ┆   ┆ ---     ┆ ---  ┆ ---      ┆ ---          │
│ u32   ┆ str    ┆ str      ┆ i64         ┆   ┆ i64     ┆ i64  ┆ i64      ┆ i64          │
╞═══════╪════════╪══════════╪═════════════╪═══╪═════════╪══════╪══════════╪══════════════╡
│ 0     ┆ BUDGET ┆ ABC Inc. ┆ 2023        ┆ … ┆ 32000   ┆ 1700 ┆ 11       ┆ 191899       │
│ 1     ┆ BUDGET ┆ ABC Inc. ┆ 2021        ┆ … ┆ 42000   ┆ 1100 ┆ 13       ┆ 642174       │
│ 2     ┆ BUDGET ┆ ABC Inc. ┆ 2020        ┆ … ┆ 20000   ┆ 1600 ┆ 12       ┆ 744630       │
│ 3     ┆ BUDGET ┆ ABC Inc. ┆ 2022        ┆ … ┆ 31000   ┆ 2200 ┆ 17       ┆ 362583       │
│ 4     ┆ BUDGET ┆ ABC Inc. ┆ 2022        ┆ … ┆ 36000   ┆ 1600 ┆ 13       ┆ 826260       │
└───────┴────────┴──────────┴─────────────┴───┴─────────┴──────┴──────────┴──────────────┘

In [12]:
#########################################
# combined ledger for Actuals and Budget
#########################################
dfLedger = pl.concat([ledger, ledger_budg], how="vertical")
dfLedger.sample(5).with_row_index("Row #")

shape: (5, 9)
┌───────┬─────────┬──────────┬─────────────┬───┬─────────┬──────┬──────────┬──────────────┐
│ Row # ┆ LEDGER  ┆ ORG      ┆ FISCAL_YEAR ┆ … ┆ ACCOUNT ┆ DEPT ┆ LOCATION ┆ POSTED_TOTAL │
│ ---   ┆ ---     ┆ ---      ┆ ---         ┆   ┆ ---     ┆ ---  ┆ ---      ┆ ---          │
│ u32   ┆ str     ┆ str      ┆ i64         ┆   ┆ i64     ┆ i64  ┆ i64      ┆ i64          │
╞═══════╪═════════╪══════════╪═════════════╪═══╪═════════╪══════╪══════════╪══════════════╡
│ 0     ┆ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ … ┆ 14000   ┆ 1900 ┆ 19       ┆ 728319       │
│ 1     ┆ BUDGET  ┆ ABC Inc. ┆ 2020        ┆ … ┆ 34000   ┆ 1500 ┆ 19       ┆ 263608       │
│ 2     ┆ ACTUALS ┆ ABC Inc. ┆ 2022        ┆ … ┆ 18000   ┆ 1200 ┆ 14       ┆ 226738       │
│ 3     ┆ ACTUALS ┆ ABC Inc. ┆ 2021        ┆ … ┆ 12000   ┆ 1400 ┆ 13       ┆ 745380       │
│ 4     ┆ BUDGET  ┆ ABC Inc. ┆ 2021        ┆ … ┆ 11000   ┆ 1900 ┆ 22       ┆ 590625       │
└───────┴─────────┴──────────┴─────────────┴───┴─────────┴──────┴──────────┴──────────────┘

## Supply Chain DataSet

In [14]:
################################
## PRODUCT_CATEGORY DataFrame ##
################################
import random
from datetime import datetime

category = pl.DataFrame({
    "ID":  list(range(1000, 2500, 100)),
    "AS_OF_DATE" : datetime(2022, 1, 1),
    "DESCRIPTION" : ["Rx","Material","Consulting","Construction",
                     "un-assigned"] * 3,
    "REGION": ["Region A","Region B","Region C"] * 5,
    "STATUS" : "Active",
    "CLASSIFICATION" : ["Rx","Material", "Services","Constructions",
                        "OTHERS"] * 3,
    "TYPE" : ["R","M","S","C","O"] * 3,
})
category.sample(5).with_row_index("Row #")

shape: (5, 8)
┌───────┬──────┬─────────────────────┬─────────────┬──────────┬────────┬────────────────┬──────┐
│ Row # ┆ ID   ┆ AS_OF_DATE          ┆ DESCRIPTION ┆ REGION   ┆ STATUS ┆ CLASSIFICATION ┆ TYPE │
│ ---   ┆ ---  ┆ ---                 ┆ ---         ┆ ---      ┆ ---    ┆ ---            ┆ ---  │
│ u32   ┆ i64  ┆ datetime[μs]        ┆ str         ┆ str      ┆ str    ┆ str            ┆ str  │
╞═══════╪══════╪═════════════════════╪═════════════╪══════════╪════════╪════════════════╪══════╡
│ 0     ┆ 1900 ┆ 2022-01-01 00:00:00 ┆ un-assigned ┆ Region A ┆ Active ┆ OTHERS         ┆ O    │
│ 1     ┆ 2200 ┆ 2022-01-01 00:00:00 ┆ Consulting  ┆ Region A ┆ Active ┆ Services       ┆ S    │
│ 2     ┆ 1600 ┆ 2022-01-01 00:00:00 ┆ Material    ┆ Region A ┆ Active ┆ Material       ┆ M    │
│ 3     ┆ 1200 ┆ 2022-01-01 00:00:00 ┆ Consulting  ┆ Region C ┆ Active ┆ Services       ┆ S    │
│ 4     ┆ 1000 ┆ 2022-01-01 00:00:00 ┆ Rx          ┆ Region A ┆ Active ┆ Rx             ┆ R    │
└───────┴──────┴─────────────────────┴─────────────┴──────────┴────────┴────────────────┴──────┘

In [15]:
#######################
## PRODUCT DataFrame ##
#######################
import random
from datetime import datetime

product = pl.DataFrame({
    "ID":  list(range(100, 250, 10)),
    "AS_OF_DATE" : datetime(2022, 1, 1),
    "DESCRIPTION" : ["Item 1","Item 2","Item 3","Item 4","Item 5"] * 3,
    "STATUS" : "Active",
    "CATEGORY" : random.choices(category["ID"], k=15),
})
product.sample(5).with_row_index("Row #")

shape: (5, 6)
┌───────┬─────┬─────────────────────┬─────────────┬────────┬──────────┐
│ Row # ┆ ID  ┆ AS_OF_DATE          ┆ DESCRIPTION ┆ STATUS ┆ CATEGORY │
│ ---   ┆ --- ┆ ---                 ┆ ---         ┆ ---    ┆ ---      │
│ u32   ┆ i64 ┆ datetime[μs]        ┆ str         ┆ str    ┆ i64      │
╞═══════╪═════╪═════════════════════╪═════════════╪════════╪══════════╡
│ 0     ┆ 100 ┆ 2022-01-01 00:00:00 ┆ Item 1      ┆ Active ┆ 2200     │
│ 1     ┆ 170 ┆ 2022-01-01 00:00:00 ┆ Item 3      ┆ Active ┆ 1100     │
│ 2     ┆ 130 ┆ 2022-01-01 00:00:00 ┆ Item 4      ┆ Active ┆ 1000     │
│ 3     ┆ 220 ┆ 2022-01-01 00:00:00 ┆ Item 3      ┆ Active ┆ 1600     │
│ 4     ┆ 180 ┆ 2022-01-01 00:00:00 ┆ Item 4      ┆ Active ┆ 1100     │
└───────┴─────┴─────────────────────┴─────────────┴────────┴──────────┘

In [16]:
########################
## CUSTOMER DataFrame ##
########################
import random
from datetime import datetime

customer = pl.DataFrame({
    "ID":  list(range(100, 250, 10)),
    "AS_OF_DATE" : datetime(2022, 1, 1),
    "DESCRIPTION" : ["Customer 1","Customer 2","Customer 3",
                     "Customer 4","Customer 5"] * 3,
    "ADDRESS" : ["Address 1","Address 2","Address 3",
                 "Address 4","Address 5"] * 3,
    "PHONE" : ["0000000001","0000000002","0000000003",
               "0000000004","0000000005"] * 3,
    "EMAIL" : ["1@email","2@email","3@email","4@email","5@email"] * 3,
    "STATUS" : "Active",
    "TYPE" : ["Corp","Gov","Individual"] * 5,
    "CATEGORY" : random.choices(category["ID"], k=15),
})
customer.sample(5).with_row_index("Row #")

shape: (5, 10)
┌───────┬─────┬─────────────────────┬─────────────┬───┬─────────┬────────┬────────────┬──────────┐
│ Row # ┆ ID  ┆ AS_OF_DATE          ┆ DESCRIPTION ┆ … ┆ EMAIL   ┆ STATUS ┆ TYPE       ┆ CATEGORY │
│ ---   ┆ --- ┆ ---                 ┆ ---         ┆   ┆ ---     ┆ ---    ┆ ---        ┆ ---      │
│ u32   ┆ i64 ┆ datetime[μs]        ┆ str         ┆   ┆ str     ┆ str    ┆ str        ┆ i64      │
╞═══════╪═════╪═════════════════════╪═════════════╪═══╪═════════╪════════╪════════════╪══════════╡
│ 0     ┆ 230 ┆ 2022-01-01 00:00:00 ┆ Customer 4  ┆ … ┆ 4@email ┆ Active ┆ Gov        ┆ 1400     │
│ 1     ┆ 130 ┆ 2022-01-01 00:00:00 ┆ Customer 4  ┆ … ┆ 4@email ┆ Active ┆ Corp       ┆ 1800     │
│ 2     ┆ 200 ┆ 2022-01-01 00:00:00 ┆ Customer 1  ┆ … ┆ 1@email ┆ Active ┆ Gov        ┆ 1700     │
│ 3     ┆ 100 ┆ 2022-01-01 00:00:00 ┆ Customer 1  ┆ … ┆ 1@email ┆ Active ┆ Corp       ┆ 1000     │
│ 4     ┆ 150 ┆ 2022-01-01 00:00:00 ┆ Customer 1  ┆ … ┆ 1@email ┆ Active ┆ Individual ┆ 2300     │
└───────┴─────┴─────────────────────┴─────────────┴───┴─────────┴────────┴────────────┴──────────┘

In [17]:
#####################
## ORDER DataFrame ##
#####################
import random
from datetime import datetime
sampleSize = 10

order = pl.DataFrame({
    "ID":  list(range(1000, 1100, sampleSize)),
    "AS_OF_DATE" : datetime(2024, 1, 1),
    "CUSTOMER": random.choices(customer["ID"], k=sampleSize),
    "ITEM": random.choices(product["ID"], k=sampleSize),
    "QTY": random.sample(range(1000000), sampleSize),
	"POSTED_TOTAL": random.sample(range(1000000), sampleSize)
})
order.sample(5).with_row_index("Row #")

shape: (5, 7)
┌───────┬──────┬─────────────────────┬──────────┬──────┬────────┬──────────────┐
│ Row # ┆ ID   ┆ AS_OF_DATE          ┆ CUSTOMER ┆ ITEM ┆ QTY    ┆ POSTED_TOTAL │
│ ---   ┆ ---  ┆ ---                 ┆ ---      ┆ ---  ┆ ---    ┆ ---          │
│ u32   ┆ i64  ┆ datetime[μs]        ┆ i64      ┆ i64  ┆ i64    ┆ i64          │
╞═══════╪══════╪═════════════════════╪══════════╪══════╪════════╪══════════════╡
│ 0     ┆ 1010 ┆ 2024-01-01 00:00:00 ┆ 150      ┆ 110  ┆ 914763 ┆ 257778       │
│ 1     ┆ 1060 ┆ 2024-01-01 00:00:00 ┆ 120      ┆ 120  ┆ 905046 ┆ 656761       │
│ 2     ┆ 1070 ┆ 2024-01-01 00:00:00 ┆ 220      ┆ 220  ┆ 102258 ┆ 38051        │
│ 3     ┆ 1030 ┆ 2024-01-01 00:00:00 ┆ 140      ┆ 190  ┆ 271223 ┆ 296333       │
│ 4     ┆ 1040 ┆ 2024-01-01 00:00:00 ┆ 140      ┆ 210  ┆ 576853 ┆ 275990       │
└───────┴──────┴─────────────────────┴──────────┴──────┴────────┴──────────────┘

In [18]:
#######################
## INVOICE DataFrame ##
#######################
import random
from datetime import datetime
sampleSize = 10

invoice = pl.DataFrame({
    "AS_OF_DATE" : datetime(2024, 1, 1),
    "ORDER": random.choices(order["ID"], k=sampleSize),
    "STATUS" : ["open","paid","cancelled","shipped","hold"] * 2,
})
invoice.sample(5).with_row_index("Row #")

shape: (5, 4)
┌───────┬─────────────────────┬───────┬───────────┐
│ Row # ┆ AS_OF_DATE          ┆ ORDER ┆ STATUS    │
│ ---   ┆ ---                 ┆ ---   ┆ ---       │
│ u32   ┆ datetime[μs]        ┆ i64   ┆ str       │
╞═══════╪═════════════════════╪═══════╪═══════════╡
│ 0     ┆ 2024-01-01 00:00:00 ┆ 1000  ┆ paid      │
│ 1     ┆ 2024-01-01 00:00:00 ┆ 1060  ┆ cancelled │
│ 2     ┆ 2024-01-01 00:00:00 ┆ 1050  ┆ paid      │
│ 3     ┆ 2024-01-01 00:00:00 ┆ 1030  ┆ shipped   │
│ 4     ┆ 2024-01-01 00:00:00 ┆ 1050  ┆ cancelled │
└───────┴─────────────────────┴───────┴───────────┘

## IO

In [44]:
#################
### csv files ###
#################
dfLedger.write_csv("data/ledger.csv")
dfLedger_c = pl.read_csv("data/ledger.csv")
# Polars allows you to scan a CSV input. 
# Scanning delays the actual parsing of the file 
# and instead returns a lazy computation holder called a LazyFrame.
dfLedger_c = pl.scan_csv("data/ledger.csv")


#####################
### parquet files ###
#####################
dfLedger.write_parquet("data/ledger.parquet")
dfLedger_c = pl.read_parquet("data/ledger.parquet")
# Polars allows you to scan a parquet input. 
# Scanning delays the actual parsing of the file and instead 
# returns a lazy computation holder called a LazyFrame.
dfLedger_c = pl.scan_parquet("data/ledger.parquet")

###############
## databases ##
###############
import polars as pl

connection_uri = "postgres://username:password@server:port/database"
query = "SELECT * FROM foo"

pl.read_database(query=query, connection_uri=connection_uri)

# Polars doesn't manage connections and data transfer from databases by itself. 
# Instead external libraries (known as engines) handle this.
#  At present Polars can use two engines to read from databases:
# ConnectorX and ADBC
# $  pip install connectorx
# $  pip install adbc-driver-sqlite

# As with reading from a database above Polars uses an engine 
# to write to a database. 
# The currently supported engines are:
# SQLAlchemy and
# Arrow Database Connectivity (ADBC)
# $  pip install SQLAlchemy pandas

# AWS & Big Query - API - WIP as of 07/11/23

In [28]:
print(dfLedger.sample(5))
##################
## select context
##################
out = dfLedger.select(
    pl.col("FISCAL_YEAR").sort(),
    pl.col("PERIOD").sort(),
    pl.col(["LEDGER", "ORG", "ACCOUNT", "DEPT", "LOCATION"]),
    (pl.col("POSTED_TOTAL") / 1000).alias("in Thousands"),
).with_row_index("Row #")
print(out)

shape: (5, 8)
┌─────────┬──────────┬─────────────┬────────┬─────────┬──────┬──────────┬──────────────┐
│ LEDGER  ┆ ORG      ┆ FISCAL_YEAR ┆ PERIOD ┆ ACCOUNT ┆ DEPT ┆ LOCATION ┆ POSTED_TOTAL │
│ ---     ┆ ---      ┆ ---         ┆ ---    ┆ ---     ┆ ---  ┆ ---      ┆ ---          │
│ str     ┆ str      ┆ i64         ┆ i64    ┆ i64     ┆ i64  ┆ i64      ┆ i64          │
╞═════════╪══════════╪═════════════╪════════╪═════════╪══════╪══════════╪══════════════╡
│ BUDGET  ┆ ABC Inc. ┆ 2021        ┆ 5      ┆ 44000   ┆ 1100 ┆ 11       ┆ 732906       │
│ ACTUALS ┆ ABC Inc. ┆ 2021        ┆ 10     ┆ 16000   ┆ 1800 ┆ 17       ┆ 222087       │
│ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ 5      ┆ 20000   ┆ 2000 ┆ 16       ┆ 935164       │
│ BUDGET  ┆ ABC Inc. ┆ 2023        ┆ 5      ┆ 23000   ┆ 1200 ┆ 11       ┆ 603780       │
│ BUDGET  ┆ ABC Inc. ┆ 2020        ┆ 6      ┆ 18000   ┆ 1600 ┆ 17       ┆ 152681       │
└─────────┴──────────┴─────────────┴────────┴─────────┴──────┴──────────┴──────────────┘
shape: (200_000, 9)
┌────────┬─────────────┬────────┬─────────┬───┬─────────┬──────┬──────────┬──────────────┐
│ Row #  ┆ FISCAL_YEAR ┆ PERIOD ┆ LEDGER  ┆ … ┆ ACCOUNT ┆ DEPT ┆ LOCATION ┆ in Thousands │
│ ---    ┆ ---         ┆ ---    ┆ ---     ┆   ┆ ---     ┆ ---  ┆ ---      ┆ ---          │
│ u32    ┆ i64         ┆ i64    ┆ str     ┆   ┆ i64     ┆ i64  ┆ i64      ┆ f64          │
╞════════╪═════════════╪════════╪═════════╪═══╪═════════╪══════╪══════════╪══════════════╡
│ 0      ┆ 2020        ┆ 1      ┆ ACTUALS ┆ … ┆ 12000   ┆ 2400 ┆ 22       ┆ 753.956      │
│ 1      ┆ 2020        ┆ 1      ┆ ACTUALS ┆ … ┆ 10000   ┆ 1900 ┆ 14       ┆ 826.906      │
│ 2      ┆ 2020        ┆ 1      ┆ ACTUALS ┆ … ┆ 21000   ┆ 1700 ┆ 17       ┆ 454.574      │
│ 3      ┆ 2020        ┆ 1      ┆ ACTUALS ┆ … ┆ 34000   ┆ 1300 ┆ 12       ┆ 334.989      │
│ 4      ┆ 2020        ┆ 1      ┆ ACTUALS ┆ … ┆ 14000   ┆ 2100 ┆ 11       ┆ 290.813      │
│ …      ┆ …           ┆ …      ┆ …       ┆ … ┆ …       ┆ …    ┆ …        ┆ …            │
│ 199995 ┆ 2023        ┆ 12     ┆ BUDGET  ┆ … ┆ 21000   ┆ 1600 ┆ 12       ┆ 853.43       │
│ 199996 ┆ 2023        ┆ 12     ┆ BUDGET  ┆ … ┆ 41000   ┆ 2000 ┆ 20       ┆ 142.082      │
│ 199997 ┆ 2023        ┆ 12     ┆ BUDGET  ┆ … ┆ 41000   ┆ 1500 ┆ 22       ┆ 0.499        │
│ 199998 ┆ 2023        ┆ 12     ┆ BUDGET  ┆ … ┆ 32000   ┆ 1100 ┆ 11       ┆ 742.81       │
│ 199999 ┆ 2023        ┆ 12     ┆ BUDGET  ┆ … ┆ 38000   ┆ 1900 ┆ 15       ┆ 152.106      │
└────────┴─────────────┴────────┴─────────┴───┴─────────┴──────┴──────────┴──────────────┘

In [29]:
##########################
## with_columns context ##
##########################
out = dfLedger.with_columns(
    (pl.col("POSTED_TOTAL") / 1000).alias("in Thousands"),
).with_row_index("Row #")
print(out)

shape: (200_000, 10)
┌────────┬─────────┬──────────┬─────────────┬───┬──────┬──────────┬──────────────┬──────────────┐
│ Row #  ┆ LEDGER  ┆ ORG      ┆ FISCAL_YEAR ┆ … ┆ DEPT ┆ LOCATION ┆ POSTED_TOTAL ┆ in Thousands │
│ ---    ┆ ---     ┆ ---      ┆ ---         ┆   ┆ ---  ┆ ---      ┆ ---          ┆ ---          │
│ u32    ┆ str     ┆ str      ┆ i64         ┆   ┆ i64  ┆ i64      ┆ i64          ┆ f64          │
╞════════╪═════════╪══════════╪═════════════╪═══╪══════╪══════════╪══════════════╪══════════════╡
│ 0      ┆ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ … ┆ 2400 ┆ 22       ┆ 753956       ┆ 753.956      │
│ 1      ┆ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ … ┆ 1900 ┆ 14       ┆ 826906       ┆ 826.906      │
│ 2      ┆ ACTUALS ┆ ABC Inc. ┆ 2021        ┆ … ┆ 1700 ┆ 17       ┆ 454574       ┆ 454.574      │
│ 3      ┆ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ … ┆ 1300 ┆ 12       ┆ 334989       ┆ 334.989      │
│ 4      ┆ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ … ┆ 2100 ┆ 11       ┆ 290813       ┆ 290.813      │
│ …      ┆ …       ┆ …        ┆ …           ┆ … ┆ …    ┆ …        ┆ …            ┆ …            │
│ 199995 ┆ BUDGET  ┆ ABC Inc. ┆ 2022        ┆ … ┆ 1600 ┆ 12       ┆ 853430       ┆ 853.43       │
│ 199996 ┆ BUDGET  ┆ ABC Inc. ┆ 2020        ┆ … ┆ 2000 ┆ 20       ┆ 142082       ┆ 142.082      │
│ 199997 ┆ BUDGET  ┆ ABC Inc. ┆ 2022        ┆ … ┆ 1500 ┆ 22       ┆ 499          ┆ 0.499        │
│ 199998 ┆ BUDGET  ┆ ABC Inc. ┆ 2021        ┆ … ┆ 1100 ┆ 11       ┆ 742810       ┆ 742.81       │
│ 199999 ┆ BUDGET  ┆ ABC Inc. ┆ 2020        ┆ … ┆ 1900 ┆ 15       ┆ 152106       ┆ 152.106      │
└────────┴─────────┴──────────┴─────────────┴───┴──────┴──────────┴──────────────┴──────────────┘

In [30]:
##########################
## filter context ##
##########################
out = dfLedger.filter(
    ((pl.col("LEDGER") == "ACTUALS") & (pl.col("FISCAL_YEAR") == 2023))
).with_row_index("Row #")
print(out)

shape: (25_136, 9)
┌───────┬─────────┬──────────┬─────────────┬───┬─────────┬──────┬──────────┬──────────────┐
│ Row # ┆ LEDGER  ┆ ORG      ┆ FISCAL_YEAR ┆ … ┆ ACCOUNT ┆ DEPT ┆ LOCATION ┆ POSTED_TOTAL │
│ ---   ┆ ---     ┆ ---      ┆ ---         ┆   ┆ ---     ┆ ---  ┆ ---      ┆ ---          │
│ u32   ┆ str     ┆ str      ┆ i64         ┆   ┆ i64     ┆ i64  ┆ i64      ┆ i64          │
╞═══════╪═════════╪══════════╪═════════════╪═══╪═════════╪══════╪══════════╪══════════════╡
│ 0     ┆ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ … ┆ 14000   ┆ 2100 ┆ 11       ┆ 290813       │
│ 1     ┆ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ … ┆ 16000   ┆ 1600 ┆ 21       ┆ 28323        │
│ 2     ┆ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ … ┆ 42000   ┆ 1600 ┆ 16       ┆ 106856       │
│ 3     ┆ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ … ┆ 37000   ┆ 1600 ┆ 17       ┆ 145223       │
│ 4     ┆ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ … ┆ 21000   ┆ 1100 ┆ 14       ┆ 912981       │
│ …     ┆ …       ┆ …        ┆ …           ┆ … ┆ …       ┆ …    ┆ …        ┆ …            │
│ 25131 ┆ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ … ┆ 13000   ┆ 1000 ┆ 14       ┆ 165519       │
│ 25132 ┆ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ … ┆ 20000   ┆ 1400 ┆ 17       ┆ 831737       │
│ 25133 ┆ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ … ┆ 32000   ┆ 1700 ┆ 16       ┆ 131723       │
│ 25134 ┆ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ … ┆ 33000   ┆ 2200 ┆ 17       ┆ 187186       │
│ 25135 ┆ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ … ┆ 14000   ┆ 1800 ┆ 18       ┆ 642420       │
└───────┴─────────┴──────────┴─────────────┴───┴─────────┴──────┴──────────┴──────────────┘

In [32]:
######################
## group by context ##
######################
out = dfLedger.filter(
    ((pl.col("LEDGER") == "ACTUALS") & (pl.col("FISCAL_YEAR") == 2023))
        ).group_by("LEDGER").agg(
                                pl.len()
                                ).with_row_index("Row #")
print(out)

out = dfLedger.group_by("LEDGER", "FISCAL_YEAR").agg(
                                pl.len()
                                ).with_row_index("Row #")
print(out)

# sort group by data by FISCAL_YEAR
out = dfLedger.group_by("LEDGER", "FISCAL_YEAR").agg(
                                pl.len(),
                                pl.sum("POSTED_TOTAL"),
                                (pl.sum("POSTED_TOTAL") / 1_000_000)
                                .alias("Posted Total in Million"),
                                ).with_row_index("Row #")
print(out)

shape: (1, 3)
┌───────┬─────────┬───────┐
│ Row # ┆ LEDGER  ┆ len   │
│ ---   ┆ ---     ┆ ---   │
│ u32   ┆ str     ┆ u32   │
╞═══════╪═════════╪═══════╡
│ 0     ┆ ACTUALS ┆ 25136 │
└───────┴─────────┴───────┘
shape: (8, 4)
┌───────┬─────────┬─────────────┬───────┐
│ Row # ┆ LEDGER  ┆ FISCAL_YEAR ┆ len   │
│ ---   ┆ ---     ┆ ---         ┆ ---   │
│ u32   ┆ str     ┆ i64         ┆ u32   │
╞═══════╪═════════╪═════════════╪═══════╡
│ 0     ┆ BUDGET  ┆ 2020        ┆ 25255 │
│ 1     ┆ BUDGET  ┆ 2023        ┆ 24910 │
│ 2     ┆ BUDGET  ┆ 2021        ┆ 25021 │
│ 3     ┆ ACTUALS ┆ 2023        ┆ 25136 │
│ 4     ┆ ACTUALS ┆ 2021        ┆ 25036 │
│ 5     ┆ ACTUALS ┆ 2022        ┆ 24871 │
│ 6     ┆ ACTUALS ┆ 2020        ┆ 24957 │
│ 7     ┆ BUDGET  ┆ 2022        ┆ 24814 │
└───────┴─────────┴─────────────┴───────┘
shape: (8, 6)
┌───────┬─────────┬─────────────┬───────┬──────────────┬─────────────────────────┐
│ Row # ┆ LEDGER  ┆ FISCAL_YEAR ┆ len   ┆ POSTED_TOTAL ┆ Posted Total in Million │
│ ---   ┆ ---     ┆ ---         ┆ ---   ┆ ---          ┆ ---                     │
│ u32   ┆ str     ┆ i64         ┆ u32   ┆ i64          ┆ f64                     │
╞═══════╪═════════╪═════════════╪═══════╪══════════════╪═════════════════════════╡
│ 0     ┆ BUDGET  ┆ 2022        ┆ 24814 ┆ 12426384357  ┆ 12426.384357            │
│ 1     ┆ BUDGET  ┆ 2020        ┆ 25255 ┆ 12650442434  ┆ 12650.442434            │
│ 2     ┆ BUDGET  ┆ 2021        ┆ 25021 ┆ 12523123626  ┆ 12523.123626            │
│ 3     ┆ ACTUALS ┆ 2023        ┆ 25136 ┆ 12526897831  ┆ 12526.897831            │
│ 4     ┆ ACTUALS ┆ 2021        ┆ 25036 ┆ 12506846602  ┆ 12506.846602            │
│ 5     ┆ ACTUALS ┆ 2020        ┆ 24957 ┆ 12430170980  ┆ 12430.17098             │
│ 6     ┆ BUDGET  ┆ 2023        ┆ 24910 ┆ 12498973303  ┆ 12498.973303            │
│ 7     ┆ ACTUALS ┆ 2022        ┆ 24871 ┆ 12420814798  ┆ 12420.814798            │
└───────┴─────────┴─────────────┴───────┴──────────────┴─────────────────────────┘

## Polars DataFrame Expressions

#### using Expression to select columns

In [33]:
######################
# selection context ##
######################
print(order.sample(5).with_row_index("Row #"))

 # using numerical operators
dfOrder = order.select(
    pl.col("ID"),
    pl.col("AS_OF_DATE"),
    pl.col("CUSTOMER"),
    pl.col("ITEM"),
    pl.col("QTY"),
    (pl.col("POSTED_TOTAL") / 1000).alias("Amount in thousands"),
).with_row_index("Row #")
print(dfOrder)

shape: (5, 7)
┌───────┬──────┬─────────────────────┬──────────┬──────┬────────┬──────────────┐
│ Row # ┆ ID   ┆ AS_OF_DATE          ┆ CUSTOMER ┆ ITEM ┆ QTY    ┆ POSTED_TOTAL │
│ ---   ┆ ---  ┆ ---                 ┆ ---      ┆ ---  ┆ ---    ┆ ---          │
│ u32   ┆ i64  ┆ datetime[μs]        ┆ i64      ┆ i64  ┆ i64    ┆ i64          │
╞═══════╪══════╪═════════════════════╪══════════╪══════╪════════╪══════════════╡
│ 0     ┆ 1000 ┆ 2024-01-01 00:00:00 ┆ 200      ┆ 210  ┆ 707819 ┆ 141345       │
│ 1     ┆ 1090 ┆ 2024-01-01 00:00:00 ┆ 110      ┆ 100  ┆ 658423 ┆ 15062        │
│ 2     ┆ 1050 ┆ 2024-01-01 00:00:00 ┆ 120      ┆ 130  ┆ 345494 ┆ 164911       │
│ 3     ┆ 1060 ┆ 2024-01-01 00:00:00 ┆ 120      ┆ 120  ┆ 905046 ┆ 656761       │
│ 4     ┆ 1010 ┆ 2024-01-01 00:00:00 ┆ 150      ┆ 110  ┆ 914763 ┆ 257778       │
└───────┴──────┴─────────────────────┴──────────┴──────┴────────┴──────────────┘
shape: (10, 7)
┌───────┬──────┬─────────────────────┬──────────┬──────┬────────┬─────────────────────┐
│ Row # ┆ ID   ┆ AS_OF_DATE          ┆ CUSTOMER ┆ ITEM ┆ QTY    ┆ Amount in thousands │
│ ---   ┆ ---  ┆ ---                 ┆ ---      ┆ ---  ┆ ---    ┆ ---                 │
│ u32   ┆ i64  ┆ datetime[μs]        ┆ i64      ┆ i64  ┆ i64    ┆ f64                 │
╞═══════╪══════╪═════════════════════╪══════════╪══════╪════════╪═════════════════════╡
│ 0     ┆ 1000 ┆ 2024-01-01 00:00:00 ┆ 200      ┆ 210  ┆ 707819 ┆ 141.345             │
│ 1     ┆ 1010 ┆ 2024-01-01 00:00:00 ┆ 150      ┆ 110  ┆ 914763 ┆ 257.778             │
│ 2     ┆ 1020 ┆ 2024-01-01 00:00:00 ┆ 190      ┆ 130  ┆ 984229 ┆ 567.161             │
│ 3     ┆ 1030 ┆ 2024-01-01 00:00:00 ┆ 140      ┆ 190  ┆ 271223 ┆ 296.333             │
│ 4     ┆ 1040 ┆ 2024-01-01 00:00:00 ┆ 140      ┆ 210  ┆ 576853 ┆ 275.99              │
│ 5     ┆ 1050 ┆ 2024-01-01 00:00:00 ┆ 120      ┆ 130  ┆ 345494 ┆ 164.911             │
│ 6     ┆ 1060 ┆ 2024-01-01 00:00:00 ┆ 120      ┆ 120  ┆ 905046 ┆ 656.761             │
│ 7     ┆ 1070 ┆ 2024-01-01 00:00:00 ┆ 220      ┆ 220  ┆ 102258 ┆ 38.051              │
│ 8     ┆ 1080 ┆ 2024-01-01 00:00:00 ┆ 120      ┆ 100  ┆ 763885 ┆ 777.376             │
│ 9     ┆ 1090 ┆ 2024-01-01 00:00:00 ┆ 110      ┆ 100  ┆ 658423 ┆ 15.062              │
└───────┴──────┴─────────────────────┴──────────┴──────┴────────┴─────────────────────┘

In [34]:
# select context the selection applies expressions over columns.
# The expressions in this context must produce Series that are
# all the same length or have a length of 1.

# select all cols
dfOrder.select(pl.col("*")).sample(5)
# dfOrder.select(pl.all()).sample(5)

shape: (5, 7)
┌───────┬──────┬─────────────────────┬──────────┬──────┬────────┬─────────────────────┐
│ Row # ┆ ID   ┆ AS_OF_DATE          ┆ CUSTOMER ┆ ITEM ┆ QTY    ┆ Amount in thousands │
│ ---   ┆ ---  ┆ ---                 ┆ ---      ┆ ---  ┆ ---    ┆ ---                 │
│ u32   ┆ i64  ┆ datetime[μs]        ┆ i64      ┆ i64  ┆ i64    ┆ f64                 │
╞═══════╪══════╪═════════════════════╪══════════╪══════╪════════╪═════════════════════╡
│ 8     ┆ 1080 ┆ 2024-01-01 00:00:00 ┆ 120      ┆ 100  ┆ 763885 ┆ 777.376             │
│ 5     ┆ 1050 ┆ 2024-01-01 00:00:00 ┆ 120      ┆ 130  ┆ 345494 ┆ 164.911             │
│ 4     ┆ 1040 ┆ 2024-01-01 00:00:00 ┆ 140      ┆ 210  ┆ 576853 ┆ 275.99              │
│ 0     ┆ 1000 ┆ 2024-01-01 00:00:00 ┆ 200      ┆ 210  ┆ 707819 ┆ 141.345             │
│ 3     ┆ 1030 ┆ 2024-01-01 00:00:00 ┆ 140      ┆ 190  ┆ 271223 ┆ 296.333             │
└───────┴──────┴─────────────────────┴──────────┴──────┴────────┴─────────────────────┘

In [35]:
# select all cols excluding some
dfOrder.select(pl.col("*").exclude("CUSTOMER", "QTY")).sample(5)

shape: (5, 5)
┌───────┬──────┬─────────────────────┬──────┬─────────────────────┐
│ Row # ┆ ID   ┆ AS_OF_DATE          ┆ ITEM ┆ Amount in thousands │
│ ---   ┆ ---  ┆ ---                 ┆ ---  ┆ ---                 │
│ u32   ┆ i64  ┆ datetime[μs]        ┆ i64  ┆ f64                 │
╞═══════╪══════╪═════════════════════╪══════╪═════════════════════╡
│ 7     ┆ 1070 ┆ 2024-01-01 00:00:00 ┆ 220  ┆ 38.051              │
│ 8     ┆ 1080 ┆ 2024-01-01 00:00:00 ┆ 100  ┆ 777.376             │
│ 0     ┆ 1000 ┆ 2024-01-01 00:00:00 ┆ 210  ┆ 141.345             │
│ 3     ┆ 1030 ┆ 2024-01-01 00:00:00 ┆ 190  ┆ 296.333             │
│ 4     ┆ 1040 ┆ 2024-01-01 00:00:00 ┆ 210  ┆ 275.99              │
└───────┴──────┴─────────────────────┴──────┴─────────────────────┘

In [36]:
# select certain cols
dfOrder.select(pl.col("Row #", "ID", "QTY")).sample(5)

shape: (5, 3)
┌───────┬──────┬────────┐
│ Row # ┆ ID   ┆ QTY    │
│ ---   ┆ ---  ┆ ---    │
│ u32   ┆ i64  ┆ i64    │
╞═══════╪══════╪════════╡
│ 8     ┆ 1080 ┆ 763885 │
│ 5     ┆ 1050 ┆ 345494 │
│ 4     ┆ 1040 ┆ 576853 │
│ 0     ┆ 1000 ┆ 707819 │
│ 9     ┆ 1090 ┆ 658423 │
└───────┴──────┴────────┘

In [37]:
# working with date columns
dfOrder.select(
    pl.col("AS_OF_DATE").dt.to_string("%Y-%h-%d"),
    pl.col("Row #", "ID", "QTY")
    ).sample(5)

shape: (5, 4)
┌─────────────┬───────┬──────┬────────┐
│ AS_OF_DATE  ┆ Row # ┆ ID   ┆ QTY    │
│ ---         ┆ ---   ┆ ---  ┆ ---    │
│ str         ┆ u32   ┆ i64  ┆ i64    │
╞═════════════╪═══════╪══════╪════════╡
│ 2024-Jan-01 ┆ 2     ┆ 1020 ┆ 984229 │
│ 2024-Jan-01 ┆ 9     ┆ 1090 ┆ 658423 │
│ 2024-Jan-01 ┆ 6     ┆ 1060 ┆ 905046 │
│ 2024-Jan-01 ┆ 1     ┆ 1010 ┆ 914763 │
│ 2024-Jan-01 ┆ 8     ┆ 1080 ┆ 763885 │
└─────────────┴───────┴──────┴────────┘

In [38]:
# select cols by regex
dfOrder.select(pl.col("^.*(ID|QT|Amount).*$")).sample(5)

shape: (5, 3)
┌──────┬────────┬─────────────────────┐
│ ID   ┆ QTY    ┆ Amount in thousands │
│ ---  ┆ ---    ┆ ---                 │
│ i64  ┆ i64    ┆ f64                 │
╞══════╪════════╪═════════════════════╡
│ 1080 ┆ 763885 ┆ 777.376             │
│ 1070 ┆ 102258 ┆ 38.051              │
│ 1000 ┆ 707819 ┆ 141.345             │
│ 1030 ┆ 271223 ┆ 296.333             │
│ 1040 ┆ 576853 ┆ 275.99              │
└──────┴────────┴─────────────────────┘

In [39]:
# select cols by data types
print(dfOrder.sample(1)) # original - take a note of dtypes
dfOrder.select(pl.col(pl.UInt32, pl.Int64)).sample(5)

shape: (1, 7)
┌───────┬──────┬─────────────────────┬──────────┬──────┬────────┬─────────────────────┐
│ Row # ┆ ID   ┆ AS_OF_DATE          ┆ CUSTOMER ┆ ITEM ┆ QTY    ┆ Amount in thousands │
│ ---   ┆ ---  ┆ ---                 ┆ ---      ┆ ---  ┆ ---    ┆ ---                 │
│ u32   ┆ i64  ┆ datetime[μs]        ┆ i64      ┆ i64  ┆ i64    ┆ f64                 │
╞═══════╪══════╪═════════════════════╪══════════╪══════╪════════╪═════════════════════╡
│ 0     ┆ 1000 ┆ 2024-01-01 00:00:00 ┆ 200      ┆ 210  ┆ 707819 ┆ 141.345             │
└───────┴──────┴─────────────────────┴──────────┴──────┴────────┴─────────────────────┘

shape: (5, 5)
┌───────┬──────┬──────────┬──────┬────────┐
│ Row # ┆ ID   ┆ CUSTOMER ┆ ITEM ┆ QTY    │
│ ---   ┆ ---  ┆ ---      ┆ ---  ┆ ---    │
│ u32   ┆ i64  ┆ i64      ┆ i64  ┆ i64    │
╞═══════╪══════╪══════════╪══════╪════════╡
│ 8     ┆ 1080 ┆ 120      ┆ 100  ┆ 763885 │
│ 3     ┆ 1030 ┆ 140      ┆ 190  ┆ 271223 │
│ 6     ┆ 1060 ┆ 120      ┆ 120  ┆ 905046 │
│ 2     ┆ 1020 ┆ 190      ┆ 130  ┆ 984229 │
│ 0     ┆ 1000 ┆ 200      ┆ 210  ┆ 707819 │
└───────┴──────┴──────────┴──────┴────────┘

In [40]:
# select cols by data types
print(dfOrder.sample(1)) # original - take a note of dtypes
dfOrder.select(pl.col(pl.UInt32, pl.Int64)).sample(5)

shape: (1, 7)
┌───────┬──────┬─────────────────────┬──────────┬──────┬────────┬─────────────────────┐
│ Row # ┆ ID   ┆ AS_OF_DATE          ┆ CUSTOMER ┆ ITEM ┆ QTY    ┆ Amount in thousands │
│ ---   ┆ ---  ┆ ---                 ┆ ---      ┆ ---  ┆ ---    ┆ ---                 │
│ u32   ┆ i64  ┆ datetime[μs]        ┆ i64      ┆ i64  ┆ i64    ┆ f64                 │
╞═══════╪══════╪═════════════════════╪══════════╪══════╪════════╪═════════════════════╡
│ 2     ┆ 1020 ┆ 2024-01-01 00:00:00 ┆ 190      ┆ 130  ┆ 984229 ┆ 567.161             │
└───────┴──────┴─────────────────────┴──────────┴──────┴────────┴─────────────────────┘

shape: (5, 5)
┌───────┬──────┬──────────┬──────┬────────┐
│ Row # ┆ ID   ┆ CUSTOMER ┆ ITEM ┆ QTY    │
│ ---   ┆ ---  ┆ ---      ┆ ---  ┆ ---    │
│ u32   ┆ i64  ┆ i64      ┆ i64  ┆ i64    │
╞═══════╪══════╪══════════╪══════╪════════╡
│ 1     ┆ 1010 ┆ 150      ┆ 110  ┆ 914763 │
│ 5     ┆ 1050 ┆ 120      ┆ 130  ┆ 345494 │
│ 2     ┆ 1020 ┆ 190      ┆ 130  ┆ 984229 │
│ 4     ┆ 1040 ┆ 140      ┆ 210  ┆ 576853 │
│ 7     ┆ 1070 ┆ 220      ┆ 220  ┆ 102258 │
└───────┴──────┴──────────┴──────┴────────┘

In [42]:
# select cols to pull unique # of column values
# for example, pull # of distint | unique customers

dfOrderSample = dfOrder.select(pl.col("CUSTOMER"))

# print row count by CUSTOMER
print(dfOrderSample.group_by("CUSTOMER").agg(pl.len()))

# print unique # of rows by CUSTOMER
print(dfOrderSample.select(pl.col("CUSTOMER")).n_unique())

shape: (7, 2)
┌──────────┬─────┐
│ CUSTOMER ┆ len │
│ ---      ┆ --- │
│ i64      ┆ u32 │
╞══════════╪═════╡
│ 220      ┆ 1   │
│ 140      ┆ 2   │
│ 150      ┆ 1   │
│ 110      ┆ 1   │
│ 200      ┆ 1   │
│ 190      ┆ 1   │
│ 120      ┆ 3   │
└──────────┴─────┘
7

In [43]:
# using conditional expression

df_conditional = dfOrder.select(
    pl.col("CUSTOMER"),
    pl.when(pl.col("CUSTOMER") == 100)
    .then(pl.lit("Preferred"))
    .otherwise(pl.lit(False))
    .alias("conditional"),
    
)
print(df_conditional)

shape: (10, 2)
┌──────────┬─────────────┐
│ CUSTOMER ┆ conditional │
│ ---      ┆ ---         │
│ i64      ┆ str         │
╞══════════╪═════════════╡
│ 200      ┆ false       │
│ 150      ┆ false       │
│ 190      ┆ false       │
│ 140      ┆ false       │
│ 140      ┆ false       │
│ 120      ┆ false       │
│ 120      ┆ false       │
│ 220      ┆ false       │
│ 120      ┆ false       │
│ 110      ┆ false       │
└──────────┴─────────────┘

In [47]:
#########################################
## select columns using selectors
## using cs selector for column selection
#########################################

import polars.selectors as cs

dfOrder.select(pl.all())
dfOrder.select(cs.integer(), cs.string()).sample(5) 
# all int and string cols

dfOrder.select(cs.numeric() - cs.first()) 
# all cols except first col

dfOrder.select(cs.by_name("CUSTOMER") | cs.numeric()) 
# col=CUSTOMER or all numeric cols

dfOrder.select(~cs.numeric()) 
# everything else which is not numeric

dfOrder.select(cs.contains("ID"), cs.matches(".*_.*")) 
# select cols by pattern

dfOrder.select(cs.temporal().as_expr().dt.to_string("%Y-%h-%d")) 
# cols by converting to expressions

#####################
# debugging selectors
#####################

# is_selector
from polars.selectors import is_selector

out = cs.temporal()
print(is_selector(out))

# selector_column_names
# from polars.selectors import cs

out = cs.temporal().as_expr().dt.to_string("%Y-%h-%d")
print(out.sample(5))

True
cs.temporal().dt.to_string().sample([dyn int: 5])

In [48]:
#####################
## DataType Casting #
#####################
# Polar provide casting method to convert the underlying DataType 
# of a column to a new one
# strict=True # means, DataType conversion will throw an error
# strict=False # means, DataType conversion will convert value to null

# cast
print(dfOrder.sample(5))
out = dfOrder.select(
    pl.col("ID").cast(pl.Float32).alias("integers_as_floats"),
    pl.col("QTY").cast(pl.Float32).alias("floats_as_integers"),
)
print(out)

shape: (5, 7)
┌───────┬──────┬─────────────────────┬──────────┬──────┬────────┬─────────────────────┐
│ Row # ┆ ID   ┆ AS_OF_DATE          ┆ CUSTOMER ┆ ITEM ┆ QTY    ┆ Amount in thousands │
│ ---   ┆ ---  ┆ ---                 ┆ ---      ┆ ---  ┆ ---    ┆ ---                 │
│ u32   ┆ i64  ┆ datetime[μs]        ┆ i64      ┆ i64  ┆ i64    ┆ f64                 │
╞═══════╪══════╪═════════════════════╪══════════╪══════╪════════╪═════════════════════╡
│ 9     ┆ 1090 ┆ 2024-01-01 00:00:00 ┆ 110      ┆ 100  ┆ 658423 ┆ 15.062              │
│ 7     ┆ 1070 ┆ 2024-01-01 00:00:00 ┆ 220      ┆ 220  ┆ 102258 ┆ 38.051              │
│ 2     ┆ 1020 ┆ 2024-01-01 00:00:00 ┆ 190      ┆ 130  ┆ 984229 ┆ 567.161             │
│ 1     ┆ 1010 ┆ 2024-01-01 00:00:00 ┆ 150      ┆ 110  ┆ 914763 ┆ 257.778             │
│ 3     ┆ 1030 ┆ 2024-01-01 00:00:00 ┆ 140      ┆ 190  ┆ 271223 ┆ 296.333             │
└───────┴──────┴─────────────────────┴──────────┴──────┴────────┴─────────────────────┘
shape: (10, 2)
┌────────────────────┬────────────────────┐
│ integers_as_floats ┆ floats_as_integers │
│ ---                ┆ ---                │
│ f32                ┆ f32                │
╞════════════════════╪════════════════════╡
│ 1000.0             ┆ 707819.0           │
│ 1010.0             ┆ 914763.0           │
│ 1020.0             ┆ 984229.0           │
│ 1030.0             ┆ 271223.0           │
│ 1040.0             ┆ 576853.0           │
│ 1050.0             ┆ 345494.0           │
│ 1060.0             ┆ 905046.0           │
│ 1070.0             ┆ 102258.0           │
│ 1080.0             ┆ 763885.0           │
│ 1090.0             ┆ 658423.0           │
└────────────────────┴────────────────────┘

In [49]:
# downncast
# casting from Int64 to Int16 and from Float64 to Float32 can be 
# used to lower memory usage
out = dfOrder.select(
    pl.col("ID").cast(pl.Int16).alias("integers_smallfootprint"),
    pl.col("CUSTOMER").cast(pl.Int16).alias("floats_smallfootprint"),
    pl.col("Amount in thousands").cast(pl.Float32).alias("Amount"),
)
print(out)

shape: (10, 3)
┌─────────────────────────┬───────────────────────┬────────────┐
│ integers_smallfootprint ┆ floats_smallfootprint ┆ Amount     │
│ ---                     ┆ ---                   ┆ ---        │
│ i16                     ┆ i16                   ┆ f32        │
╞═════════════════════════╪═══════════════════════╪════════════╡
│ 1000                    ┆ 200                   ┆ 141.345001 │
│ 1010                    ┆ 150                   ┆ 257.778015 │
│ 1020                    ┆ 190                   ┆ 567.161011 │
│ 1030                    ┆ 140                   ┆ 296.333008 │
│ 1040                    ┆ 140                   ┆ 275.98999  │
│ 1050                    ┆ 120                   ┆ 164.910995 │
│ 1060                    ┆ 120                   ┆ 656.760986 │
│ 1070                    ┆ 220                   ┆ 38.050999  │
│ 1080                    ┆ 120                   ┆ 777.375977 │
│ 1090                    ┆ 110                   ┆ 15.062     │
└─────────────────────────┴───────────────────────┴────────────┘

In [50]:
# overflow
try:
    out = dfOrder.select(pl.col("Amount in thousands").cast(pl.Int8))
    print(out)
except Exception as e:
    print(e)

# to supress above error
# run with strict=False
out = dfOrder.select(pl.col("Amount in thousands").cast(pl.Int8, strict=False))
print(out)

conversion from `f64` to `i8` failed in column 'Amount in thousands' for 8 out of 10 values: [141.345, 257.778, … 777.376]

This error occurred in the following expression:
	col("Amount in thousands").strict_cast(Int8)

shape: (10, 1)
┌─────────────────────┐
│ Amount in thousands │
│ ---                 │
│ i8                  │
╞═════════════════════╡
│ null                │
│ null                │
│ null                │
│ null                │
│ null                │
│ null                │
│ null                │
│ 38                  │
│ null                │
│ 15                  │
└─────────────────────┘

In [51]:
# strings datatype casting

# changing numeric fields to string
out = dfOrder.select(
    pl.all().exclude("ID"),
    pl.col("ID").cast(pl.Utf8)
)
print(out)

# change string back to numeric
out = dfOrder.select(
    pl.all().exclude("ID"),
    pl.col("ID").cast(pl.Int16)
)
print(out)

shape: (10, 7)
┌───────┬─────────────────────┬──────────┬──────┬────────┬─────────────────────┬──────┐
│ Row # ┆ AS_OF_DATE          ┆ CUSTOMER ┆ ITEM ┆ QTY    ┆ Amount in thousands ┆ ID   │
│ ---   ┆ ---                 ┆ ---      ┆ ---  ┆ ---    ┆ ---                 ┆ ---  │
│ u32   ┆ datetime[μs]        ┆ i64      ┆ i64  ┆ i64    ┆ f64                 ┆ str  │
╞═══════╪═════════════════════╪══════════╪══════╪════════╪═════════════════════╪══════╡
│ 0     ┆ 2024-01-01 00:00:00 ┆ 200      ┆ 210  ┆ 707819 ┆ 141.345             ┆ 1000 │
│ 1     ┆ 2024-01-01 00:00:00 ┆ 150      ┆ 110  ┆ 914763 ┆ 257.778             ┆ 1010 │
│ 2     ┆ 2024-01-01 00:00:00 ┆ 190      ┆ 130  ┆ 984229 ┆ 567.161             ┆ 1020 │
│ 3     ┆ 2024-01-01 00:00:00 ┆ 140      ┆ 190  ┆ 271223 ┆ 296.333             ┆ 1030 │
│ 4     ┆ 2024-01-01 00:00:00 ┆ 140      ┆ 210  ┆ 576853 ┆ 275.99              ┆ 1040 │
│ 5     ┆ 2024-01-01 00:00:00 ┆ 120      ┆ 130  ┆ 345494 ┆ 164.911             ┆ 1050 │
│ 6     ┆ 2024-01-01 00:00:00 ┆ 120      ┆ 120  ┆ 905046 ┆ 656.761             ┆ 1060 │
│ 7     ┆ 2024-01-01 00:00:00 ┆ 220      ┆ 220  ┆ 102258 ┆ 38.051              ┆ 1070 │
│ 8     ┆ 2024-01-01 00:00:00 ┆ 120      ┆ 100  ┆ 763885 ┆ 777.376             ┆ 1080 │
│ 9     ┆ 2024-01-01 00:00:00 ┆ 110      ┆ 100  ┆ 658423 ┆ 15.062              ┆ 1090 │
└───────┴─────────────────────┴──────────┴──────┴────────┴─────────────────────┴──────┘
shape: (10, 7)
┌───────┬─────────────────────┬──────────┬──────┬────────┬─────────────────────┬──────┐
│ Row # ┆ AS_OF_DATE          ┆ CUSTOMER ┆ ITEM ┆ QTY    ┆ Amount in thousands ┆ ID   │
│ ---   ┆ ---                 ┆ ---      ┆ ---  ┆ ---    ┆ ---                 ┆ ---  │
│ u32   ┆ datetime[μs]        ┆ i64      ┆ i64  ┆ i64    ┆ f64                 ┆ i16  │
╞═══════╪═════════════════════╪══════════╪══════╪════════╪═════════════════════╪══════╡
│ 0     ┆ 2024-01-01 00:00:00 ┆ 200      ┆ 210  ┆ 707819 ┆ 141.345             ┆ 1000 │
│ 1     ┆ 2024-01-01 00:00:00 ┆ 150      ┆ 110  ┆ 914763 ┆ 257.778             ┆ 1010 │
│ 2     ┆ 2024-01-01 00:00:00 ┆ 190      ┆ 130  ┆ 984229 ┆ 567.161             ┆ 1020 │
│ 3     ┆ 2024-01-01 00:00:00 ┆ 140      ┆ 190  ┆ 271223 ┆ 296.333             ┆ 1030 │
│ 4     ┆ 2024-01-01 00:00:00 ┆ 140      ┆ 210  ┆ 576853 ┆ 275.99              ┆ 1040 │
│ 5     ┆ 2024-01-01 00:00:00 ┆ 120      ┆ 130  ┆ 345494 ┆ 164.911             ┆ 1050 │
│ 6     ┆ 2024-01-01 00:00:00 ┆ 120      ┆ 120  ┆ 905046 ┆ 656.761             ┆ 1060 │
│ 7     ┆ 2024-01-01 00:00:00 ┆ 220      ┆ 220  ┆ 102258 ┆ 38.051              ┆ 1070 │
│ 8     ┆ 2024-01-01 00:00:00 ┆ 120      ┆ 100  ┆ 763885 ┆ 777.376             ┆ 1080 │
│ 9     ┆ 2024-01-01 00:00:00 ┆ 110      ┆ 100  ┆ 658423 ┆ 15.062              ┆ 1090 │
└───────┴─────────────────────┴──────────┴──────┴────────┴─────────────────────┴──────┘

In [52]:
df = pl.DataFrame({"strings_not_float": ["4.0", "not_a_number",
                                          "6.0", "7.0", "8.0"]})
try:
    out = df.select(pl.col("strings_not_float").cast(pl.Float64))
    print(out)
except Exception as e:
    print(e)

# as per exception, it suggests to use strptime to convert string to numeric
# this is only applicable and works well when string hold datatime values

conversion from `str` to `f64` failed in column 'strings_not_float' for 1 out of 5 values: ["not_a_number"]

This error occurred in the following expression:
	col("strings_not_float").strict_cast(Float64)

In [53]:
# boolean
# Boolean cast convert all non-zero numeric (int & floats) to true
# Boolean cast convert all zero numeric (int & floats) to false

print(dfOrder.sample(4))
out = dfOrder.select(
        pl.col("Row #").cast(pl.Boolean),
        pl.col("QTY").cast(pl.Boolean),
        pl.all().exclude("Row #", "QTY"),
        )
print(out)

shape: (4, 7)
┌───────┬──────┬─────────────────────┬──────────┬──────┬────────┬─────────────────────┐
│ Row # ┆ ID   ┆ AS_OF_DATE          ┆ CUSTOMER ┆ ITEM ┆ QTY    ┆ Amount in thousands │
│ ---   ┆ ---  ┆ ---                 ┆ ---      ┆ ---  ┆ ---    ┆ ---                 │
│ u32   ┆ i64  ┆ datetime[μs]        ┆ i64      ┆ i64  ┆ i64    ┆ f64                 │
╞═══════╪══════╪═════════════════════╪══════════╪══════╪════════╪═════════════════════╡
│ 1     ┆ 1010 ┆ 2024-01-01 00:00:00 ┆ 150      ┆ 110  ┆ 914763 ┆ 257.778             │
│ 6     ┆ 1060 ┆ 2024-01-01 00:00:00 ┆ 120      ┆ 120  ┆ 905046 ┆ 656.761             │
│ 5     ┆ 1050 ┆ 2024-01-01 00:00:00 ┆ 120      ┆ 130  ┆ 345494 ┆ 164.911             │
│ 0     ┆ 1000 ┆ 2024-01-01 00:00:00 ┆ 200      ┆ 210  ┆ 707819 ┆ 141.345             │
└───────┴──────┴─────────────────────┴──────────┴──────┴────────┴─────────────────────┘
shape: (10, 7)
┌───────┬──────┬──────┬─────────────────────┬──────────┬──────┬─────────────────────┐
│ Row # ┆ QTY  ┆ ID   ┆ AS_OF_DATE          ┆ CUSTOMER ┆ ITEM ┆ Amount in thousands │
│ ---   ┆ ---  ┆ ---  ┆ ---                 ┆ ---      ┆ ---  ┆ ---                 │
│ bool  ┆ bool ┆ i64  ┆ datetime[μs]        ┆ i64      ┆ i64  ┆ f64                 │
╞═══════╪══════╪══════╪═════════════════════╪══════════╪══════╪═════════════════════╡
│ false ┆ true ┆ 1000 ┆ 2024-01-01 00:00:00 ┆ 200      ┆ 210  ┆ 141.345             │
│ true  ┆ true ┆ 1010 ┆ 2024-01-01 00:00:00 ┆ 150      ┆ 110  ┆ 257.778             │
│ true  ┆ true ┆ 1020 ┆ 2024-01-01 00:00:00 ┆ 190      ┆ 130  ┆ 567.161             │
│ true  ┆ true ┆ 1030 ┆ 2024-01-01 00:00:00 ┆ 140      ┆ 190  ┆ 296.333             │
│ true  ┆ true ┆ 1040 ┆ 2024-01-01 00:00:00 ┆ 140      ┆ 210  ┆ 275.99              │
│ true  ┆ true ┆ 1050 ┆ 2024-01-01 00:00:00 ┆ 120      ┆ 130  ┆ 164.911             │
│ true  ┆ true ┆ 1060 ┆ 2024-01-01 00:00:00 ┆ 120      ┆ 120  ┆ 656.761             │
│ true  ┆ true ┆ 1070 ┆ 2024-01-01 00:00:00 ┆ 220      ┆ 220  ┆ 38.051              │
│ true  ┆ true ┆ 1080 ┆ 2024-01-01 00:00:00 ┆ 120      ┆ 100  ┆ 777.376             │
│ true  ┆ true ┆ 1090 ┆ 2024-01-01 00:00:00 ┆ 110      ┆ 100  ┆ 15.062              │
└───────┴──────┴──────┴─────────────────────┴──────────┴──────┴─────────────────────┘

In [54]:
# dates
out = dfOrder.select(
                    pl.col("AS_OF_DATE"),
                    pl.col("AS_OF_DATE").cast(pl.Int64).alias("DATE_as_Int"),
                    pl.col("AS_OF_DATE").cast(pl.Utf8).alias("DATE_as_Str")
                    )
print(out)

shape: (10, 3)
┌─────────────────────┬──────────────────┬────────────────────────────┐
│ AS_OF_DATE          ┆ DATE_as_Int      ┆ DATE_as_Str                │
│ ---                 ┆ ---              ┆ ---                        │
│ datetime[μs]        ┆ i64              ┆ str                        │
╞═════════════════════╪══════════════════╪════════════════════════════╡
│ 2024-01-01 00:00:00 ┆ 1704067200000000 ┆ 2024-01-01 00:00:00.000000 │
│ 2024-01-01 00:00:00 ┆ 1704067200000000 ┆ 2024-01-01 00:00:00.000000 │
│ 2024-01-01 00:00:00 ┆ 1704067200000000 ┆ 2024-01-01 00:00:00.000000 │
│ 2024-01-01 00:00:00 ┆ 1704067200000000 ┆ 2024-01-01 00:00:00.000000 │
│ 2024-01-01 00:00:00 ┆ 1704067200000000 ┆ 2024-01-01 00:00:00.000000 │
│ 2024-01-01 00:00:00 ┆ 1704067200000000 ┆ 2024-01-01 00:00:00.000000 │
│ 2024-01-01 00:00:00 ┆ 1704067200000000 ┆ 2024-01-01 00:00:00.000000 │
│ 2024-01-01 00:00:00 ┆ 1704067200000000 ┆ 2024-01-01 00:00:00.000000 │
│ 2024-01-01 00:00:00 ┆ 1704067200000000 ┆ 2024-01-01 00:00:00.000000 │
│ 2024-01-01 00:00:00 ┆ 1704067200000000 ┆ 2024-01-01 00:00:00.000000 │
└─────────────────────┴──────────────────┴────────────────────────────┘

In [55]:
# To perform casting operations between strings and Dates/Datetimes, strftime and strptime are utilized.
# Polars adopts the chrono format syntax for when formatting. 
# It's worth noting that strptime features additional options that support timezone functionality.
# Refer to the API documentation for further information.

dfOrderTmp = dfOrder.select(
                    pl.col("AS_OF_DATE"),
                    pl.col("AS_OF_DATE").cast(pl.Int64).alias("DATE_as_Int"),
                    pl.col("AS_OF_DATE").cast(pl.Utf8).alias("DATE_as_Str")
                     )
print(dfOrderTmp)

out = dfOrderTmp.select(
    pl.col("AS_OF_DATE"),
    pl.col("AS_OF_DATE").dt.strftime("%Y-%m-%d")
    .alias("AS_OF_DATE_as_strftime"),
    pl.col("DATE_as_Str").str.strptime(pl.Datetime, "%Y-%m-%d", strict=False)
)
print(out)

shape: (10, 3)
┌─────────────────────┬──────────────────┬────────────────────────────┐
│ AS_OF_DATE          ┆ DATE_as_Int      ┆ DATE_as_Str                │
│ ---                 ┆ ---              ┆ ---                        │
│ datetime[μs]        ┆ i64              ┆ str                        │
╞═════════════════════╪══════════════════╪════════════════════════════╡
│ 2024-01-01 00:00:00 ┆ 1704067200000000 ┆ 2024-01-01 00:00:00.000000 │
│ 2024-01-01 00:00:00 ┆ 1704067200000000 ┆ 2024-01-01 00:00:00.000000 │
│ 2024-01-01 00:00:00 ┆ 1704067200000000 ┆ 2024-01-01 00:00:00.000000 │
│ 2024-01-01 00:00:00 ┆ 1704067200000000 ┆ 2024-01-01 00:00:00.000000 │
│ 2024-01-01 00:00:00 ┆ 1704067200000000 ┆ 2024-01-01 00:00:00.000000 │
│ 2024-01-01 00:00:00 ┆ 1704067200000000 ┆ 2024-01-01 00:00:00.000000 │
│ 2024-01-01 00:00:00 ┆ 1704067200000000 ┆ 2024-01-01 00:00:00.000000 │
│ 2024-01-01 00:00:00 ┆ 1704067200000000 ┆ 2024-01-01 00:00:00.000000 │
│ 2024-01-01 00:00:00 ┆ 1704067200000000 ┆ 2024-01-01 00:00:00.000000 │
│ 2024-01-01 00:00:00 ┆ 1704067200000000 ┆ 2024-01-01 00:00:00.000000 │
└─────────────────────┴──────────────────┴────────────────────────────┘
shape: (10, 3)
┌─────────────────────┬────────────────────────┬──────────────┐
│ AS_OF_DATE          ┆ AS_OF_DATE_as_strftime ┆ DATE_as_Str  │
│ ---                 ┆ ---                    ┆ ---          │
│ datetime[μs]        ┆ str                    ┆ datetime[μs] │
╞═════════════════════╪════════════════════════╪══════════════╡
│ 2024-01-01 00:00:00 ┆ 2024-01-01             ┆ null         │
│ 2024-01-01 00:00:00 ┆ 2024-01-01             ┆ null         │
│ 2024-01-01 00:00:00 ┆ 2024-01-01             ┆ null         │
│ 2024-01-01 00:00:00 ┆ 2024-01-01             ┆ null         │
│ 2024-01-01 00:00:00 ┆ 2024-01-01             ┆ null         │
│ 2024-01-01 00:00:00 ┆ 2024-01-01             ┆ null         │
│ 2024-01-01 00:00:00 ┆ 2024-01-01             ┆ null         │
│ 2024-01-01 00:00:00 ┆ 2024-01-01             ┆ null         │
│ 2024-01-01 00:00:00 ┆ 2024-01-01             ┆ null         │
│ 2024-01-01 00:00:00 ┆ 2024-01-01             ┆ null         │
└─────────────────────┴────────────────────────┴──────────────┘

#### working with Strings

In [58]:
# working with Strings
# Polars store string as Utf8 strings
# String processing functions are available in the str namespace.

print(customer.sample(5))

out = customer.select(
    pl.all(),
    pl.col("DESCRIPTION").str.len_chars().alias("DESCRIPTION_byte_count"),
    pl.col("ADDRESS").str.len_chars().alias("ADDRESS_letter_count"),
)
print(out)

shape: (5, 9)
┌─────┬───────────────┬─────────────┬───────────┬───┬─────────┬────────┬────────────┬──────────┐
│ ID  ┆ AS_OF_DATE    ┆ DESCRIPTION ┆ ADDRESS   ┆ … ┆ EMAIL   ┆ STATUS ┆ TYPE       ┆ CATEGORY │
│ --- ┆ ---           ┆ ---         ┆ ---       ┆   ┆ ---     ┆ ---    ┆ ---        ┆ ---      │
│ i64 ┆ datetime[μs]  ┆ str         ┆ str       ┆   ┆ str     ┆ str    ┆ str        ┆ i64      │
╞═════╪═══════════════╪═════════════╪═══════════╪═══╪═════════╪════════╪════════════╪══════════╡
│ 120 ┆ 2022-01-01    ┆ Customer 3  ┆ Address 3 ┆ … ┆ 3@email ┆ Active ┆ Individual ┆ 1300     │
│     ┆ 00:00:00      ┆             ┆           ┆   ┆         ┆        ┆            ┆          │
│ 110 ┆ 2022-01-01    ┆ Customer 2  ┆ Address 2 ┆ … ┆ 2@email ┆ Active ┆ Gov        ┆ 1700     │
│     ┆ 00:00:00      ┆             ┆           ┆   ┆         ┆        ┆            ┆          │
│ 200 ┆ 2022-01-01    ┆ Customer 1  ┆ Address 1 ┆ … ┆ 1@email ┆ Active ┆ Gov        ┆ 1700     │
│     ┆ 00:00:00      ┆             ┆           ┆   ┆         ┆        ┆            ┆          │
│ 160 ┆ 2022-01-01    ┆ Customer 2  ┆ Address 2 ┆ … ┆ 2@email ┆ Active ┆ Corp       ┆ 2400     │
│     ┆ 00:00:00      ┆             ┆           ┆   ┆         ┆        ┆            ┆          │
│ 190 ┆ 2022-01-01    ┆ Customer 5  ┆ Address 5 ┆ … ┆ 5@email ┆ Active ┆ Corp       ┆ 2100     │
│     ┆ 00:00:00      ┆             ┆           ┆   ┆         ┆        ┆            ┆          │
└─────┴───────────────┴─────────────┴───────────┴───┴─────────┴────────┴────────────┴──────────┘
shape: (15, 11)
┌─────┬─────────────┬────────────┬───────────┬───┬────────────┬──────────┬────────────┬────────────┐
│ ID  ┆ AS_OF_DATE  ┆ DESCRIPTIO ┆ ADDRESS   ┆ … ┆ TYPE       ┆ CATEGORY ┆ DESCRIPTIO ┆ ADDRESS_le │
│ --- ┆ ---         ┆ N          ┆ ---       ┆   ┆ ---        ┆ ---      ┆ N_byte_cou ┆ tter_count │
│ i64 ┆ datetime[μs ┆ ---        ┆ str       ┆   ┆ str        ┆ i64      ┆ nt         ┆ ---        │
│     ┆ ]           ┆ str        ┆           ┆   ┆            ┆          ┆ ---        ┆ u32        │
│     ┆             ┆            ┆           ┆   ┆            ┆          ┆ u32        ┆            │
╞═════╪═════════════╪════════════╪═══════════╪═══╪════════════╪══════════╪════════════╪════════════╡
│ 100 ┆ 2022-01-01  ┆ Customer 1 ┆ Address 1 ┆ … ┆ Corp       ┆ 1000     ┆ 10         ┆ 9          │
│     ┆ 00:00:00    ┆            ┆           ┆   ┆            ┆          ┆            ┆            │
│ 110 ┆ 2022-01-01  ┆ Customer 2 ┆ Address 2 ┆ … ┆ Gov        ┆ 1700     ┆ 10         ┆ 9          │
│     ┆ 00:00:00    ┆            ┆           ┆   ┆            ┆          ┆            ┆            │
│ 120 ┆ 2022-01-01  ┆ Customer 3 ┆ Address 3 ┆ … ┆ Individual ┆ 1300     ┆ 10         ┆ 9          │
│     ┆ 00:00:00    ┆            ┆           ┆   ┆            ┆          ┆            ┆            │
│ 130 ┆ 2022-01-01  ┆ Customer 4 ┆ Address 4 ┆ … ┆ Corp       ┆ 1800     ┆ 10         ┆ 9          │
│     ┆ 00:00:00    ┆            ┆           ┆   ┆            ┆          ┆            ┆            │
│ 140 ┆ 2022-01-01  ┆ Customer 5 ┆ Address 5 ┆ … ┆ Gov        ┆ 1000     ┆ 10         ┆ 9          │
│     ┆ 00:00:00    ┆            ┆           ┆   ┆            ┆          ┆            ┆            │
│ …   ┆ …           ┆ …          ┆ …         ┆ … ┆ …          ┆ …        ┆ …          ┆ …          │
│ 200 ┆ 2022-01-01  ┆ Customer 1 ┆ Address 1 ┆ … ┆ Gov        ┆ 1700     ┆ 10         ┆ 9          │
│     ┆ 00:00:00    ┆            ┆           ┆   ┆            ┆          ┆            ┆            │
│ 210 ┆ 2022-01-01  ┆ Customer 2 ┆ Address 2 ┆ … ┆ Individual ┆ 1100     ┆ 10         ┆ 9          │
│     ┆ 00:00:00    ┆            ┆           ┆   ┆            ┆          ┆            ┆            │
│ 220 ┆ 2022-01-01  ┆ Customer 3 ┆ Address 3 ┆ … ┆ Corp       ┆ 1100     ┆ 10         ┆ 9          │
│     ┆ 00:00:00    ┆            ┆           ┆   ┆            ┆          ┆            ┆            │
│ 230 ┆ 2022-01-01  ┆ Customer 4 ┆ Address 4 ┆ … ┆ Gov        ┆ 1400     ┆ 10         ┆ 9          │
│     ┆ 00:00:00    ┆            ┆           ┆   ┆            ┆          ┆            ┆            │
│ 240 ┆ 2022-01-01  ┆ Customer 5 ┆ Address 5 ┆ … ┆ Individual ┆ 1000     ┆ 10         ┆ 9          │
│     ┆ 00:00:00    ┆            ┆           ┆   ┆            ┆          ┆            ┆            │
└─────┴─────────────┴────────────┴───────────┴───┴────────────┴──────────┴────────────┴────────────┘

In [59]:
# string parsing
out = customer.select(
    # pl.all(),
    pl.col("ADDRESS"),
    pl.col("ADDRESS").str.contains("aDD|ress").alias("regex"),
    pl.col("ADDRESS").str.contains("Add$", literal=True).alias("literal"),
    pl.col("ADDRESS").str.starts_with("Add").alias("starts_with"),
    pl.col("ADDRESS").str.ends_with("ress").alias("ends_with"),
)
print(out)

shape: (15, 5)
┌───────────┬───────┬─────────┬─────────────┬───────────┐
│ ADDRESS   ┆ regex ┆ literal ┆ starts_with ┆ ends_with │
│ ---       ┆ ---   ┆ ---     ┆ ---         ┆ ---       │
│ str       ┆ bool  ┆ bool    ┆ bool        ┆ bool      │
╞═══════════╪═══════╪═════════╪═════════════╪═══════════╡
│ Address 1 ┆ true  ┆ false   ┆ true        ┆ false     │
│ Address 2 ┆ true  ┆ false   ┆ true        ┆ false     │
│ Address 3 ┆ true  ┆ false   ┆ true        ┆ false     │
│ Address 4 ┆ true  ┆ false   ┆ true        ┆ false     │
│ Address 5 ┆ true  ┆ false   ┆ true        ┆ false     │
│ …         ┆ …     ┆ …       ┆ …           ┆ …         │
│ Address 1 ┆ true  ┆ false   ┆ true        ┆ false     │
│ Address 2 ┆ true  ┆ false   ┆ true        ┆ false     │
│ Address 3 ┆ true  ┆ false   ┆ true        ┆ false     │
│ Address 4 ┆ true  ┆ false   ┆ true        ┆ false     │
│ Address 5 ┆ true  ┆ false   ┆ true        ┆ false     │
└───────────┴───────┴─────────┴─────────────┴───────────┘

In [60]:
# extract a pettern
df = pl.DataFrame(
    {
        "a": [
            "http://vote.com/ballon_dor?candidate=messi&ref=polars",
            "http://vote.com/ballon_dor?candidat=jorginho&ref=polars",
            "http://vote.com/ballon_dor?candidate=ronaldo&ref=polars",
        ]
    }
)
out = df.select(
    pl.col("a").str.extract(r"candidate=(\w+)", group_index=1),
)
print(out)

# extract all
df = pl.DataFrame({"foo": ["123 bla 45 asd", "xyz 678 910t"]})
out = customer.select(
    pl.col("ADDRESS").str.extract_all(r"(\d+)").alias("extracted_nrs"),
)
print(out)

shape: (3, 1)
┌─────────┐
│ a       │
│ ---     │
│ str     │
╞═════════╡
│ messi   │
│ null    │
│ ronaldo │
└─────────┘
shape: (15, 1)
┌───────────────┐
│ extracted_nrs │
│ ---           │
│ list[str]     │
╞═══════════════╡
│ ["1"]         │
│ ["2"]         │
│ ["3"]         │
│ ["4"]         │
│ ["5"]         │
│ …             │
│ ["1"]         │
│ ["2"]         │
│ ["3"]         │
│ ["4"]         │
│ ["5"]         │
└───────────────┘

In [61]:
# replace | replace all
df = pl.DataFrame({"id": [1, 2], "text": ["123abc", "abc456"]})
out = customer.with_columns(
    pl.col("ADDRESS").str.replace(r"Address", "ADDRESS")
    .alias("text_replace"),
    pl.col("ADDRESS").str.replace_all("ress", "RESS", literal=True)
    .alias("text_replace_all"),
)
print(out)

shape: (15, 11)
┌─────┬─────────────┬────────────┬───────────┬───┬────────────┬──────────┬────────────┬────────────┐
│ ID  ┆ AS_OF_DATE  ┆ DESCRIPTIO ┆ ADDRESS   ┆ … ┆ TYPE       ┆ CATEGORY ┆ text_repla ┆ text_repla │
│ --- ┆ ---         ┆ N          ┆ ---       ┆   ┆ ---        ┆ ---      ┆ ce         ┆ ce_all     │
│ i64 ┆ datetime[μs ┆ ---        ┆ str       ┆   ┆ str        ┆ i64      ┆ ---        ┆ ---        │
│     ┆ ]           ┆ str        ┆           ┆   ┆            ┆          ┆ str        ┆ str        │
╞═════╪═════════════╪════════════╪═══════════╪═══╪════════════╪══════════╪════════════╪════════════╡
│ 100 ┆ 2022-01-01  ┆ Customer 1 ┆ Address 1 ┆ … ┆ Corp       ┆ 1000     ┆ ADDRESS 1  ┆ AddRESS 1  │
│     ┆ 00:00:00    ┆            ┆           ┆   ┆            ┆          ┆            ┆            │
│ 110 ┆ 2022-01-01  ┆ Customer 2 ┆ Address 2 ┆ … ┆ Gov        ┆ 1700     ┆ ADDRESS 2  ┆ AddRESS 2  │
│     ┆ 00:00:00    ┆            ┆           ┆   ┆            ┆          ┆            ┆            │
│ 120 ┆ 2022-01-01  ┆ Customer 3 ┆ Address 3 ┆ … ┆ Individual ┆ 1300     ┆ ADDRESS 3  ┆ AddRESS 3  │
│     ┆ 00:00:00    ┆            ┆           ┆   ┆            ┆          ┆            ┆            │
│ 130 ┆ 2022-01-01  ┆ Customer 4 ┆ Address 4 ┆ … ┆ Corp       ┆ 1800     ┆ ADDRESS 4  ┆ AddRESS 4  │
│     ┆ 00:00:00    ┆            ┆           ┆   ┆            ┆          ┆            ┆            │
│ 140 ┆ 2022-01-01  ┆ Customer 5 ┆ Address 5 ┆ … ┆ Gov        ┆ 1000     ┆ ADDRESS 5  ┆ AddRESS 5  │
│     ┆ 00:00:00    ┆            ┆           ┆   ┆            ┆          ┆            ┆            │
│ …   ┆ …           ┆ …          ┆ …         ┆ … ┆ …          ┆ …        ┆ …          ┆ …          │
│ 200 ┆ 2022-01-01  ┆ Customer 1 ┆ Address 1 ┆ … ┆ Gov        ┆ 1700     ┆ ADDRESS 1  ┆ AddRESS 1  │
│     ┆ 00:00:00    ┆            ┆           ┆   ┆            ┆          ┆            ┆            │
│ 210 ┆ 2022-01-01  ┆ Customer 2 ┆ Address 2 ┆ … ┆ Individual ┆ 1100     ┆ ADDRESS 2  ┆ AddRESS 2  │
│     ┆ 00:00:00    ┆            ┆           ┆   ┆            ┆          ┆            ┆            │
│ 220 ┆ 2022-01-01  ┆ Customer 3 ┆ Address 3 ┆ … ┆ Corp       ┆ 1100     ┆ ADDRESS 3  ┆ AddRESS 3  │
│     ┆ 00:00:00    ┆            ┆           ┆   ┆            ┆          ┆            ┆            │
│ 230 ┆ 2022-01-01  ┆ Customer 4 ┆ Address 4 ┆ … ┆ Gov        ┆ 1400     ┆ ADDRESS 4  ┆ AddRESS 4  │
│     ┆ 00:00:00    ┆            ┆           ┆   ┆            ┆          ┆            ┆            │
│ 240 ┆ 2022-01-01  ┆ Customer 5 ┆ Address 5 ┆ … ┆ Individual ┆ 1000     ┆ ADDRESS 5  ┆ AddRESS 5  │
│     ┆ 00:00:00    ┆            ┆           ┆   ┆            ┆          ┆            ┆            │
└─────┴─────────────┴────────────┴───────────┴───┴────────────┴──────────┴────────────┴────────────┘

#### using Expression to apply Aggregation

In [63]:
# most used functionality in EDA is to view data 
# aggregated by different criterias
# Polars Data Frame literally shines in here and is the tool of choice
# because aggregation requires speed, parallel optimized queries

# let's review our Ledger Data Frame we created

######################
## LEDGER DataFrame ##
######################
import random
from datetime import datetime

sampleSize = 100_000
org = "ABC Inc."
ledger_type = "ACTUALS" # BUDGET, STATS are other Ledger types
fiscal_year_from = 2020
fiscal_year_to = 2023
random.seed(123)

ledger = pl.DataFrame({
	"LEDGER" : ledger_type,
	"ORG" : org,
	"FISCAL_YEAR": random.choices(list(range(fiscal_year_from, 
                                          fiscal_year_to+1, 1)),k=sampleSize),
	"PERIOD": random.choices(list(range(1, 12+1, 1)),k=sampleSize),
	"ACCOUNT" : random.choices(accounts["ID"], k=sampleSize),
	"DEPT" : random.choices(dept["ID"], k=sampleSize),
	"LOCATION" : random.choices(location["ID"], k=sampleSize),
	"POSTED_TOTAL": random.sample(range(1000000), sampleSize)
})

ledger_type = "BUDGET" # ACTUALS, STATS are other Ledger types
ledger_budg = pl.DataFrame({
	"LEDGER" : ledger_type,
	"ORG" : org,
	"FISCAL_YEAR": random.choices(list(range(fiscal_year_from, fiscal_year_to+1, 1))
                               ,k=sampleSize),
	"PERIOD": random.choices(list(range(1, 12+1, 1)),k=sampleSize),
	"ACCOUNT" : random.choices(accounts["ID"], k=sampleSize),
	"DEPT" : random.choices(dept["ID"], k=sampleSize),
	"LOCATION" : random.choices(location["ID"], k=sampleSize),
	"POSTED_TOTAL": random.sample(range(1000000), sampleSize)
})

#########################################
# combined ledger for Actuals and Budget
#########################################
dfLedger = pl.concat([ledger, ledger_budg], how="vertical")
print(dfLedger.sample(5).with_row_index("Row #"))
print(dfLedger.shape)

shape: (5, 9)
┌───────┬─────────┬──────────┬─────────────┬───┬─────────┬──────┬──────────┬──────────────┐
│ Row # ┆ LEDGER  ┆ ORG      ┆ FISCAL_YEAR ┆ … ┆ ACCOUNT ┆ DEPT ┆ LOCATION ┆ POSTED_TOTAL │
│ ---   ┆ ---     ┆ ---      ┆ ---         ┆   ┆ ---     ┆ ---  ┆ ---      ┆ ---          │
│ u32   ┆ str     ┆ str      ┆ i64         ┆   ┆ i64     ┆ i64  ┆ i64      ┆ i64          │
╞═══════╪═════════╪══════════╪═════════════╪═══╪═════════╪══════╪══════════╪══════════════╡
│ 0     ┆ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ … ┆ 11000   ┆ 2100 ┆ 13       ┆ 570908       │
│ 1     ┆ BUDGET  ┆ ABC Inc. ┆ 2020        ┆ … ┆ 28000   ┆ 2100 ┆ 20       ┆ 330146       │
│ 2     ┆ BUDGET  ┆ ABC Inc. ┆ 2022        ┆ … ┆ 15000   ┆ 1100 ┆ 12       ┆ 583414       │
│ 3     ┆ BUDGET  ┆ ABC Inc. ┆ 2021        ┆ … ┆ 11000   ┆ 1200 ┆ 22       ┆ 700497       │
│ 4     ┆ BUDGET  ┆ ABC Inc. ┆ 2022        ┆ … ┆ 36000   ┆ 2200 ┆ 13       ┆ 99734        │
└───────┴─────────┴──────────┴─────────────┴───┴─────────┴──────┴──────────┴──────────────┘
(200000, 8)

In [64]:
# first let's change data type of few columns
# to a categorical dtype
out = dfLedger.with_columns(
    pl.col("LEDGER").cast(pl.Categorical),
    pl.col("ORG").cast(pl.Categorical),
    (pl.col("POSTED_TOTAL") / 1000).cast(pl.Float32)
)
print(out.sample(5))

shape: (5, 8)
┌─────────┬──────────┬─────────────┬────────┬─────────┬──────┬──────────┬──────────────┐
│ LEDGER  ┆ ORG      ┆ FISCAL_YEAR ┆ PERIOD ┆ ACCOUNT ┆ DEPT ┆ LOCATION ┆ POSTED_TOTAL │
│ ---     ┆ ---      ┆ ---         ┆ ---    ┆ ---     ┆ ---  ┆ ---      ┆ ---          │
│ cat     ┆ cat      ┆ i64         ┆ i64    ┆ i64     ┆ i64  ┆ i64      ┆ f32          │
╞═════════╪══════════╪═════════════╪════════╪═════════╪══════╪══════════╪══════════════╡
│ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ 5      ┆ 23000   ┆ 1300 ┆ 20       ┆ 430.022003   │
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 7      ┆ 11000   ┆ 2100 ┆ 15       ┆ 978.754028   │
│ ACTUALS ┆ ABC Inc. ┆ 2022        ┆ 10     ┆ 19000   ┆ 1500 ┆ 18       ┆ 967.953003   │
│ BUDGET  ┆ ABC Inc. ┆ 2023        ┆ 8      ┆ 29000   ┆ 1200 ┆ 15       ┆ 798.547974   │
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 3      ┆ 22000   ┆ 1800 ┆ 15       ┆ 592.638977   │
└─────────┴──────────┴─────────────┴────────┴─────────┴──────┴──────────┴──────────────┘

In [72]:
q = (
    out.lazy()
    .group_by("LEDGER", "FISCAL_YEAR")
    .agg(
        pl.len(),  # Replaces deprecated pl.count()
        pl.col("PERIOD").sort().implode().alias("PERIODS"),  # Explicitly create a sorted list
        (pl.sum("POSTED_TOTAL") / 1_000_000).cast(pl.Float32).alias("TOTAL (in millions)")
    )
    .sort("len", descending=True)  # Column name from pl.len() defaults to "len"
    .limit(5)
)

df = q.collect()
print(df)

shape: (5, 5)
┌─────────┬─────────────┬───────┬──────────────┬─────────────────────┐
│ LEDGER  ┆ FISCAL_YEAR ┆ len   ┆ PERIODS      ┆ TOTAL (in millions) │
│ ---     ┆ ---         ┆ ---   ┆ ---          ┆ ---                 │
│ cat     ┆ i64         ┆ u32   ┆ list[i64]    ┆ f32                 │
╞═════════╪═════════════╪═══════╪══════════════╪═════════════════════╡
│ BUDGET  ┆ 2023        ┆ 25260 ┆ [1, 1, … 12] ┆ 12.646668           │
│ ACTUALS ┆ 2023        ┆ 25136 ┆ [1, 1, … 12] ┆ 12.526898           │
│ ACTUALS ┆ 2021        ┆ 25036 ┆ [1, 1, … 12] ┆ 12.506847           │
│ ACTUALS ┆ 2020        ┆ 24957 ┆ [1, 1, … 12] ┆ 12.430171           │
│ BUDGET  ┆ 2020        ┆ 24944 ┆ [1, 1, … 12] ┆ 12.488546           │
└─────────┴─────────────┴───────┴──────────────┴─────────────────────┘

In [75]:
# conditional aggregation
# Let's say we want to know counts by Quarters.
# We could directly query that in the aggregation without the need of a lambda 
# or grooming the DataFrame.
out = dfLedger.with_columns(
    pl.col("LEDGER").cast(pl.Categorical),
    pl.col("ORG").cast(pl.Categorical),
    (pl.col("POSTED_TOTAL") / 1000).cast(pl.Float32)
)
q = (
    out.lazy()
    .group_by("LEDGER", "FISCAL_YEAR")
    .agg(
        pl.len(),
        ((pl.col("PERIOD") >= 1) & (pl.col("PERIOD") <= 3)).sum().cast(pl.Int32).alias("Q1 counts"),
        ((pl.col("PERIOD") >= 4) & (pl.col("PERIOD") <= 6)).sum().cast(pl.Int32).alias("Q2 counts"),
        ((pl.col("PERIOD") >= 7) & (pl.col("PERIOD") <= 9)).sum().cast(pl.Int32).alias("Q3 counts"),
        ((pl.col("PERIOD") >= 10) & (pl.col("PERIOD") <= 12)).sum().cast(pl.Int32).alias("Q4 counts"),
        (pl.sum("POSTED_TOTAL") / 1000000).cast(pl.Float32).alias("TOTAL (in milions)")
    )
    .sort("FISCAL_YEAR", descending=True)
    .limit(5)
)

df = q.collect()
print(df)

shape: (5, 8)
┌─────────┬─────────────┬───────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ LEDGER  ┆ FISCAL_YEAR ┆ len   ┆ Q1 counts ┆ Q2 counts ┆ Q3 counts ┆ Q4 counts ┆ TOTAL (in │
│ ---     ┆ ---         ┆ ---   ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ milions)  │
│ cat     ┆ i64         ┆ u32   ┆ i32       ┆ i32       ┆ i32       ┆ i32       ┆ ---       │
│         ┆             ┆       ┆           ┆           ┆           ┆           ┆ f32       │
╞═════════╪═════════════╪═══════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ BUDGET  ┆ 2023        ┆ 25260 ┆ 6221      ┆ 6298      ┆ 6406      ┆ 6335      ┆ 12.646668 │
│ ACTUALS ┆ 2023        ┆ 25136 ┆ 6339      ┆ 6377      ┆ 6222      ┆ 6198      ┆ 12.526898 │
│ ACTUALS ┆ 2022        ┆ 24871 ┆ 6284      ┆ 6138      ┆ 6242      ┆ 6207      ┆ 12.420815 │
│ BUDGET  ┆ 2022        ┆ 24877 ┆ 6228      ┆ 6228      ┆ 6248      ┆ 6173      ┆ 12.404568 │
│ BUDGET  ┆ 2021        ┆ 24919 ┆ 6247      ┆ 6274      ┆ 6142      ┆ 6256      ┆ 12.544223 │
└─────────┴─────────────┴───────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [77]:
# filtering
# We can also filter the groups. Let's say we want to compute a mean per group,
# but we don't want to include all values from that group, 
# and we also don't want to filter the rows from the DataFrame 
# (because we need those rows for another aggregation).

# In the example below we show how this can be done.
def avg_by_qtr(fromMonth: int, toMonth: int) -> pl.Expr:
    return (
        (pl.col("POSTED_TOTAL")).filter(((pl.col("PERIOD") >= fromMonth) & (pl.col("PERIOD") <= toMonth)))
        .mean()
        .alias(f"avg {fromMonth}-{toMonth} Month")
    )

q = (
    out.lazy()
    .group_by("LEDGER", "FISCAL_YEAR")
    .agg(
        pl.len(),
        # ((pl.col("PERIOD") >= 1) & (pl.col("PERIOD") <= 3)).sum().cast(pl.Int32).alias("Q1 counts"),
        # ((pl.col("PERIOD") >= 4) & (pl.col("PERIOD") <= 6)).sum().cast(pl.Int32).alias("Q2 counts"),
        # ((pl.col("PERIOD") >= 7) & (pl.col("PERIOD") <= 9)).sum().cast(pl.Int32).alias("Q3 counts"),
        # ((pl.col("PERIOD") >= 10) & (pl.col("PERIOD") <= 12)).sum().cast(pl.Int32).alias("Q4 counts"),
        avg_by_qtr(1,3),
        avg_by_qtr(4,6),
        avg_by_qtr(7,9),
        avg_by_qtr(10,12),
        (pl.sum("POSTED_TOTAL") / 1000000).cast(pl.Float32).alias("TOTAL (in milions)")
    )
    .sort("FISCAL_YEAR", descending=True)
    .limit(5)
)

df = q.collect()
print(df)

shape: (5, 8)
┌─────────┬─────────────┬───────┬─────────────┬─────────────┬────────────┬────────────┬────────────┐
│ LEDGER  ┆ FISCAL_YEAR ┆ len   ┆ avg 1-3     ┆ avg 4-6     ┆ avg 7-9    ┆ avg 10-12  ┆ TOTAL (in  │
│ ---     ┆ ---         ┆ ---   ┆ Month       ┆ Month       ┆ Month      ┆ Month      ┆ milions)   │
│ cat     ┆ i64         ┆ u32   ┆ ---         ┆ ---         ┆ ---        ┆ ---        ┆ ---        │
│         ┆             ┆       ┆ f32         ┆ f32         ┆ f32        ┆ f32        ┆ f32        │
╞═════════╪═════════════╪═══════╪═════════════╪═════════════╪════════════╪════════════╪════════════╡
│ BUDGET  ┆ 2023        ┆ 25260 ┆ 497.987366  ┆ 503.527405  ┆ 496.942993 ┆ 504.191895 ┆ 12.646668  │
│ ACTUALS ┆ 2023        ┆ 25136 ┆ 489.695618  ┆ 497.552917  ┆ 504.888397 ┆ 501.5177   ┆ 12.526898  │
│ ACTUALS ┆ 2022        ┆ 24871 ┆ 500.282257  ┆ 505.403717  ┆ 494.125    ┆ 497.912811 ┆ 12.420815  │
│ BUDGET  ┆ 2022        ┆ 24877 ┆ 502.224091  ┆ 496.800201  ┆ 494.446838 ┆ 501.108154 ┆ 12.404568  │
│ ACTUALS ┆ 2021        ┆ 25036 ┆ 499.124664  ┆ 503.51532   ┆ 497.495422 ┆ 498.116364 ┆ 12.506847  │
└─────────┴─────────────┴───────┴─────────────┴─────────────┴────────────┴────────────┴────────────┘

#### using Expression to handle missing data

In [78]:
# let's review two example scenarios

# 1st case: one period/month of data is missing from dataset

# another useful example, is user want to prepare budgets
# based on actuals

# 2nd use case: create datasets based on FILL strategy

# check out few samples of Ledger Data Frame
out = dfLedger.with_columns(
    pl.col("LEDGER").cast(pl.Categorical),
    pl.col("ORG").cast(pl.Categorical),
    (pl.col("POSTED_TOTAL") / 1000).cast(pl.Float32)
).sort("FISCAL_YEAR", "PERIOD")
print(out.head(5))

# count of rows for ACCOUNT = 10000, LOCATION = 14 & PERIOD = 12
print("Rows|Columns: ", out.filter((pl.col("ACCOUNT") == 10000) 
                 & (pl.col("LOCATION") == 14) 
                 & (pl.col("PERIOD") == 12)).shape)

outRevised = dfLedger.with_columns(
    pl.col("LEDGER").cast(pl.Categorical),
    pl.col("ORG").cast(pl.Categorical),
    (pl.col("POSTED_TOTAL") / 1000).cast(pl.Float32),
    pl.when(
        (pl.col("ACCOUNT") == 10000) 
                 & (pl.col("LOCATION") == 14) 
                 & (pl.col("PERIOD") == 12)
        )
    .then(None)
    .otherwise((pl.col("POSTED_TOTAL") / 1000).cast(pl.Float32))
    .alias("POSTED_TOTAL_rev")
).sort("FISCAL_YEAR", "PERIOD")

print("Rows|Columns: ", outRevised.filter((pl.col("ACCOUNT") == 10000) 
                 & (pl.col("LOCATION") == 14) 
                 & (pl.col("PERIOD") == 12)).sample(5))

shape: (5, 8)
┌─────────┬──────────┬─────────────┬────────┬─────────┬──────┬──────────┬──────────────┐
│ LEDGER  ┆ ORG      ┆ FISCAL_YEAR ┆ PERIOD ┆ ACCOUNT ┆ DEPT ┆ LOCATION ┆ POSTED_TOTAL │
│ ---     ┆ ---      ┆ ---         ┆ ---    ┆ ---     ┆ ---  ┆ ---      ┆ ---          │
│ cat     ┆ cat      ┆ i64         ┆ i64    ┆ i64     ┆ i64  ┆ i64      ┆ f32          │
╞═════════╪══════════╪═════════════╪════════╪═════════╪══════╪══════════╪══════════════╡
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 1      ┆ 41000   ┆ 2100 ┆ 14       ┆ 849.52002    │
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 1      ┆ 10000   ┆ 1900 ┆ 14       ┆ 826.906006   │
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 1      ┆ 31000   ┆ 1500 ┆ 22       ┆ 573.536011   │
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 1      ┆ 36000   ┆ 2300 ┆ 14       ┆ 27.806999    │
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 1      ┆ 28000   ┆ 1100 ┆ 15       ┆ 20.66        │
└─────────┴──────────┴─────────────┴────────┴─────────┴──────┴──────────┴──────────────┘
Rows|Columns:  (38, 8)
Rows|Columns:  shape: (5, 9)
┌────────┬──────────┬─────────────┬────────┬───┬──────┬──────────┬──────────────┬──────────────────┐
│ LEDGER ┆ ORG      ┆ FISCAL_YEAR ┆ PERIOD ┆ … ┆ DEPT ┆ LOCATION ┆ POSTED_TOTAL ┆ POSTED_TOTAL_rev │
│ ---    ┆ ---      ┆ ---         ┆ ---    ┆   ┆ ---  ┆ ---      ┆ ---          ┆ ---              │
│ cat    ┆ cat      ┆ i64         ┆ i64    ┆   ┆ i64  ┆ i64      ┆ f32          ┆ f32              │
╞════════╪══════════╪═════════════╪════════╪═══╪══════╪══════════╪══════════════╪══════════════════╡
│ BUDGET ┆ ABC Inc. ┆ 2021        ┆ 12     ┆ … ┆ 1000 ┆ 14       ┆ 79.495003    ┆ null             │
│ BUDGET ┆ ABC Inc. ┆ 2022        ┆ 12     ┆ … ┆ 1700 ┆ 14       ┆ 917.286987   ┆ null             │
│ BUDGET ┆ ABC Inc. ┆ 2021        ┆ 12     ┆ … ┆ 2000 ┆ 14       ┆ 78.411003    ┆ null             │
│ BUDGET ┆ ABC Inc. ┆ 2023        ┆ 12     ┆ … ┆ 2400 ┆ 14       ┆ 658.724976   ┆ null             │
│ BUDGET ┆ ABC Inc. ┆ 2021        ┆ 12     ┆ … ┆ 1500 ┆ 14       ┆ 506.071014   ┆ null             │
└────────┴──────────┴─────────────┴────────┴───┴──────┴──────────┴──────────────┴──────────────────┘

In [79]:
# display counts of Null rows
outRevised.null_count()

shape: (1, 9)
┌────────┬─────┬─────────────┬────────┬───┬──────┬──────────┬──────────────┬──────────────────┐
│ LEDGER ┆ ORG ┆ FISCAL_YEAR ┆ PERIOD ┆ … ┆ DEPT ┆ LOCATION ┆ POSTED_TOTAL ┆ POSTED_TOTAL_rev │
│ ---    ┆ --- ┆ ---         ┆ ---    ┆   ┆ ---  ┆ ---      ┆ ---          ┆ ---              │
│ u32    ┆ u32 ┆ u32         ┆ u32    ┆   ┆ u32  ┆ u32      ┆ u32          ┆ u32              │
╞════════╪═════╪═════════════╪════════╪═══╪══════╪══════════╪══════════════╪══════════════════╡
│ 0      ┆ 0   ┆ 0           ┆ 0      ┆ … ┆ 0    ┆ 0        ┆ 0            ┆ 38               │
└────────┴─────┴─────────────┴────────┴───┴──────┴──────────┴──────────────┴──────────────────┘

In [80]:
# Filling missing data

# Fill with specified literal value
outRevised_1 = outRevised.with_columns(
        pl.col("POSTED_TOTAL_rev").fill_null(
            pl.lit(0.0),
        ),
    )
print("Rows|Columns: ", outRevised_1.filter((pl.col("ACCOUNT") == 10000) 
                 & (pl.col("LOCATION") == 14) 
                 & (pl.col("PERIOD") == 12)).sample(5))

Rows|Columns:  shape: (5, 9)
┌─────────┬──────────┬─────────────┬────────┬───┬──────┬──────────┬──────────────┬─────────────────┐
│ LEDGER  ┆ ORG      ┆ FISCAL_YEAR ┆ PERIOD ┆ … ┆ DEPT ┆ LOCATION ┆ POSTED_TOTAL ┆ POSTED_TOTAL_re │
│ ---     ┆ ---      ┆ ---         ┆ ---    ┆   ┆ ---  ┆ ---      ┆ ---          ┆ v               │
│ cat     ┆ cat      ┆ i64         ┆ i64    ┆   ┆ i64  ┆ i64      ┆ f32          ┆ ---             │
│         ┆          ┆             ┆        ┆   ┆      ┆          ┆              ┆ f32             │
╞═════════╪══════════╪═════════════╪════════╪═══╪══════╪══════════╪══════════════╪═════════════════╡
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 12     ┆ … ┆ 2100 ┆ 14       ┆ 236.289001   ┆ 0.0             │
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 12     ┆ … ┆ 1100 ┆ 14       ┆ 637.629028   ┆ 0.0             │
│ BUDGET  ┆ ABC Inc. ┆ 2023        ┆ 12     ┆ … ┆ 2400 ┆ 14       ┆ 658.724976   ┆ 0.0             │
│ ACTUALS ┆ ABC Inc. ┆ 2021        ┆ 12     ┆ … ┆ 2200 ┆ 14       ┆ 519.124023   ┆ 0.0             │
│ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ 12     ┆ … ┆ 2400 ┆ 14       ┆ 664.72998    ┆ 0.0             │
└─────────┴──────────┴─────────────┴────────┴───┴──────┴──────────┴──────────────┴─────────────────┘

In [81]:
# Filling missing data

# Fill with a strategy
outRevised_2 = outRevised.with_columns(
        pl.col("POSTED_TOTAL_rev").fill_null(
            strategy="forward"
        ),
    )
print("Rows|Columns: ", outRevised_2.filter((pl.col("ACCOUNT") == 10000) 
                 & (pl.col("LOCATION") == 14) 
                 & (pl.col("PERIOD") == 12)).sample(5))

Rows|Columns:  shape: (5, 9)
┌─────────┬──────────┬─────────────┬────────┬───┬──────┬──────────┬──────────────┬─────────────────┐
│ LEDGER  ┆ ORG      ┆ FISCAL_YEAR ┆ PERIOD ┆ … ┆ DEPT ┆ LOCATION ┆ POSTED_TOTAL ┆ POSTED_TOTAL_re │
│ ---     ┆ ---      ┆ ---         ┆ ---    ┆   ┆ ---  ┆ ---      ┆ ---          ┆ v               │
│ cat     ┆ cat      ┆ i64         ┆ i64    ┆   ┆ i64  ┆ i64      ┆ f32          ┆ ---             │
│         ┆          ┆             ┆        ┆   ┆      ┆          ┆              ┆ f32             │
╞═════════╪══════════╪═════════════╪════════╪═══╪══════╪══════════╪══════════════╪═════════════════╡
│ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ 12     ┆ … ┆ 1300 ┆ 14       ┆ 607.448975   ┆ 69.383003       │
│ BUDGET  ┆ ABC Inc. ┆ 2021        ┆ 12     ┆ … ┆ 1500 ┆ 14       ┆ 506.071014   ┆ 210.104004      │
│ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ 12     ┆ … ┆ 1400 ┆ 14       ┆ 459.990997   ┆ 568.599976      │
│ BUDGET  ┆ ABC Inc. ┆ 2022        ┆ 12     ┆ … ┆ 1700 ┆ 14       ┆ 917.286987   ┆ 8.285           │
│ BUDGET  ┆ ABC Inc. ┆ 2022        ┆ 12     ┆ … ┆ 1700 ┆ 14       ┆ 855.356995   ┆ 959.562012      │
└─────────┴──────────┴─────────────┴────────┴───┴──────┴──────────┴──────────────┴─────────────────┘

In [82]:
# Filling missing data

# Fill with an expression
outRevised_3 = outRevised.with_columns(
        pl.col("POSTED_TOTAL_rev").fill_null(
            pl.median("POSTED_TOTAL_rev")
        ),
    )
print("Rows|Columns: ", outRevised_3.filter((pl.col("ACCOUNT") == 10000) 
                 & (pl.col("LOCATION") == 14) 
                 & (pl.col("PERIOD") == 12)).sample(5))

Rows|Columns:  shape: (5, 9)
┌─────────┬──────────┬─────────────┬────────┬───┬──────┬──────────┬──────────────┬─────────────────┐
│ LEDGER  ┆ ORG      ┆ FISCAL_YEAR ┆ PERIOD ┆ … ┆ DEPT ┆ LOCATION ┆ POSTED_TOTAL ┆ POSTED_TOTAL_re │
│ ---     ┆ ---      ┆ ---         ┆ ---    ┆   ┆ ---  ┆ ---      ┆ ---          ┆ v               │
│ cat     ┆ cat      ┆ i64         ┆ i64    ┆   ┆ i64  ┆ i64      ┆ f32          ┆ ---             │
│         ┆          ┆             ┆        ┆   ┆      ┆          ┆              ┆ f32             │
╞═════════╪══════════╪═════════════╪════════╪═══╪══════╪══════════╪══════════════╪═════════════════╡
│ BUDGET  ┆ ABC Inc. ┆ 2021        ┆ 12     ┆ … ┆ 2100 ┆ 14       ┆ 860.922974   ┆ 501.114014      │
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 12     ┆ … ┆ 1100 ┆ 14       ┆ 927.965027   ┆ 501.114014      │
│ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ 12     ┆ … ┆ 2400 ┆ 14       ┆ 664.72998    ┆ 501.114014      │
│ BUDGET  ┆ ABC Inc. ┆ 2021        ┆ 12     ┆ … ┆ 1000 ┆ 14       ┆ 79.495003    ┆ 501.114014      │
│ BUDGET  ┆ ABC Inc. ┆ 2021        ┆ 12     ┆ … ┆ 2100 ┆ 14       ┆ 129.438004   ┆ 501.114014      │
└─────────┴──────────┴─────────────┴────────┴───┴──────┴──────────┴──────────────┴─────────────────┘

In [83]:
# Filling missing data

# Fill with interpolation
outRevised_4 = outRevised.with_columns(
        pl.col("POSTED_TOTAL_rev").fill_null(
            pl.col("POSTED_TOTAL_rev").interpolate(),
        ),
    )
print("Rows|Columns: ", outRevised_4.filter((pl.col("ACCOUNT") == 10000) 
                 & (pl.col("LOCATION") == 14) 
                 & (pl.col("PERIOD") == 12)).sample(5))

Rows|Columns:  shape: (5, 9)
┌─────────┬──────────┬─────────────┬────────┬───┬──────┬──────────┬──────────────┬─────────────────┐
│ LEDGER  ┆ ORG      ┆ FISCAL_YEAR ┆ PERIOD ┆ … ┆ DEPT ┆ LOCATION ┆ POSTED_TOTAL ┆ POSTED_TOTAL_re │
│ ---     ┆ ---      ┆ ---         ┆ ---    ┆   ┆ ---  ┆ ---      ┆ ---          ┆ v               │
│ cat     ┆ cat      ┆ i64         ┆ i64    ┆   ┆ i64  ┆ i64      ┆ f32          ┆ ---             │
│         ┆          ┆             ┆        ┆   ┆      ┆          ┆              ┆ f32             │
╞═════════╪══════════╪═════════════╪════════╪═══╪══════╪══════════╪══════════════╪═════════════════╡
│ BUDGET  ┆ ABC Inc. ┆ 2021        ┆ 12     ┆ … ┆ 2300 ┆ 14       ┆ 977.153015   ┆ 703.575012      │
│ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ 12     ┆ … ┆ 1400 ┆ 14       ┆ 459.990997   ┆ 712.169983      │
│ BUDGET  ┆ ABC Inc. ┆ 2021        ┆ 12     ┆ … ┆ 1000 ┆ 14       ┆ 79.495003    ┆ 246.421494      │
│ BUDGET  ┆ ABC Inc. ┆ 2020        ┆ 12     ┆ … ┆ 1500 ┆ 14       ┆ 142.300995   ┆ 282.196472      │
│ ACTUALS ┆ ABC Inc. ┆ 2021        ┆ 12     ┆ … ┆ 2200 ┆ 14       ┆ 519.124023   ┆ 611.158508      │
└─────────┴──────────┴─────────────┴────────┴───┴──────┴──────────┴──────────────┴─────────────────┘

#### using Expression to apply Folds

In [84]:
# basic calculations using Polars expressions
df = pl.DataFrame(
    {
        "a": [1, 2, 3],
        "b": [10, 20, 30],
    }
)

out = df.select(
    (pl.col("a") + pl.col("b")).alias("sum"),
    pl.col("a").mean().alias("mean"),
    pl.col("a").min().alias("min"),
    pl.col("a").max().alias("max")
    )
out

shape: (3, 4)
┌─────┬──────┬─────┬─────┐
│ sum ┆ mean ┆ min ┆ max │
│ --- ┆ ---  ┆ --- ┆ --- │
│ i64 ┆ f64  ┆ i64 ┆ i64 │
╞═════╪══════╪═════╪═════╡
│ 11  ┆ 2.0  ┆ 1   ┆ 3   │
│ 22  ┆ 2.0  ┆ 1   ┆ 3   │
│ 33  ┆ 2.0  ┆ 1   ┆ 3   │
└─────┴──────┴─────┴─────┘

In [85]:
# using Polars Folds to perform complex algerbic aggregations
out = df.select(
    pl.fold(acc=pl.lit(0), function=lambda acc, x: acc + x, exprs=pl.all()).alias(
        "sum"
    ),
)
out

shape: (3, 1)
┌─────┐
│ sum │
│ --- │
│ i32 │
╞═════╡
│ 11  │
│ 22  │
│ 33  │
└─────┘

In [87]:
# Let's use Polars Folds to perform a conditional Algebric operation
# below sample DataFrame produces a Balance Sheet,
# however, NETWORTH calculated is wrong


############################
## BalanceSheet DataFrame ##
############################
import random
from datetime import datetime

sampleSize = 100_000
org = "ABC Inc."
ledger_type = "ACTUALS" # BUDGET, STATS are other Ledger types
fiscal_year_from = 2020
fiscal_year_to = 2023
random.seed(123)

balanceSheet = pl.DataFrame({
	"LEDGER" : ledger_type,
	"ORG" : org,
	"FISCAL_YEAR": random.choices(list(range(fiscal_year_from, 
                                          fiscal_year_to+1, 1)),k=sampleSize),
	"PERIOD": random.choices(list(range(1, 12+1, 1)),k=sampleSize),
	"ASSETS": random.sample(range(1000000), sampleSize),
    "LIABILITY": random.sample(range(1000000), sampleSize),
    "REVENUE": random.sample(range(1000000), sampleSize),
    "NETWORTH": random.sample(range(1000000), sampleSize),
})
print(balanceSheet.sample(5).with_row_index("Row #"))

shape: (5, 9)
┌───────┬─────────┬──────────┬─────────────┬───┬────────┬───────────┬─────────┬──────────┐
│ Row # ┆ LEDGER  ┆ ORG      ┆ FISCAL_YEAR ┆ … ┆ ASSETS ┆ LIABILITY ┆ REVENUE ┆ NETWORTH │
│ ---   ┆ ---     ┆ ---      ┆ ---         ┆   ┆ ---    ┆ ---       ┆ ---     ┆ ---      │
│ u32   ┆ str     ┆ str      ┆ i64         ┆   ┆ i64    ┆ i64       ┆ i64     ┆ i64      │
╞═══════╪═════════╪══════════╪═════════════╪═══╪════════╪═══════════╪═════════╪══════════╡
│ 0     ┆ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ … ┆ 624111 ┆ 646517    ┆ 89328   ┆ 902335   │
│ 1     ┆ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ … ┆ 253802 ┆ 416357    ┆ 120749  ┆ 653549   │
│ 2     ┆ ACTUALS ┆ ABC Inc. ┆ 2021        ┆ … ┆ 556193 ┆ 663354    ┆ 955930  ┆ 131265   │
│ 3     ┆ ACTUALS ┆ ABC Inc. ┆ 2021        ┆ … ┆ 486836 ┆ 779671    ┆ 868793  ┆ 558780   │
│ 4     ┆ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ … ┆ 640430 ┆ 822572    ┆ 986978  ┆ 245137   │
└───────┴─────────┴──────────┴─────────────┴───┴────────┴───────────┴─────────┴──────────┘

In [88]:
# let's use Polars Folds to
# A. calculate NetWorth_c = ASSETS + REVENUE - LIABILITY
# B. generate a unique COSTCenter String = LEDGER+ORG+FISCAL_YEAR

out = balanceSheet.with_columns(
    pl.fold(acc=pl.lit(0),
            function=lambda acc, x: acc + x, 
            exprs=(pl.col("ASSETS","REVENUE"), pl.col("LIABILITY")*-1))
            .alias("NetWorth_c"),
    pl.fold(acc=pl.lit(""),
            function=lambda acc, x: acc + x, 
            exprs=(pl.col("LEDGER","ORG","FISCAL_YEAR"))
            .alias("CostCenter"),
    )
)
print(out.head)

<bound method DataFrame.head of shape: (100_000, 10)
┌─────────┬──────────┬─────────────┬────────┬───┬─────────┬──────────┬────────────┬────────────┐
│ LEDGER  ┆ ORG      ┆ FISCAL_YEAR ┆ PERIOD ┆ … ┆ REVENUE ┆ NETWORTH ┆ NetWorth_c ┆ literal    │
│ ---     ┆ ---      ┆ ---         ┆ ---    ┆   ┆ ---     ┆ ---      ┆ ---        ┆ ---        │
│ str     ┆ str      ┆ i64         ┆ i64    ┆   ┆ i64     ┆ i64      ┆ i32        ┆ str        │
╞═════════╪══════════╪═════════════╪════════╪═══╪═════════╪══════════╪════════════╪════════════╡
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 10     ┆ … ┆ 825234  ┆ 630949   ┆ 358184     ┆ ACTUALSABC │
│         ┆          ┆             ┆        ┆   ┆         ┆          ┆            ┆ Inc.2020   │
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 1      ┆ … ┆ 401531  ┆ 307809   ┆ -289400    ┆ ACTUALSABC │
│         ┆          ┆             ┆        ┆   ┆         ┆          ┆            ┆ Inc.2020   │
│ ACTUALS ┆ ABC Inc. ┆ 2021        ┆ 12     ┆ … ┆ 777927  ┆ 536595   ┆ 597339     ┆ ACTUALSABC │
│         ┆          ┆             ┆        ┆   ┆         ┆          ┆            ┆ Inc.2021   │
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 3      ┆ … ┆ 445913  ┆ 400960   ┆ 398951     ┆ ACTUALSABC │
│         ┆          ┆             ┆        ┆   ┆         ┆          ┆            ┆ Inc.2020   │
│ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ 9      ┆ … ┆ 339738  ┆ 116069   ┆ -72121     ┆ ACTUALSABC │
│         ┆          ┆             ┆        ┆   ┆         ┆          ┆            ┆ Inc.2023   │
│ …       ┆ …        ┆ …           ┆ …      ┆ … ┆ …       ┆ …        ┆ …          ┆ …          │
│ ACTUALS ┆ ABC Inc. ┆ 2022        ┆ 7      ┆ … ┆ 523338  ┆ 286147   ┆ 46438      ┆ ACTUALSABC │
│         ┆          ┆             ┆        ┆   ┆         ┆          ┆            ┆ Inc.2022   │
│ ACTUALS ┆ ABC Inc. ┆ 2022        ┆ 6      ┆ … ┆ 812724  ┆ 541937   ┆ 851037     ┆ ACTUALSABC │
│         ┆          ┆             ┆        ┆   ┆         ┆          ┆            ┆ Inc.2022   │
│ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ 8      ┆ … ┆ 188039  ┆ 876970   ┆ 301553     ┆ ACTUALSABC │
│         ┆          ┆             ┆        ┆   ┆         ┆          ┆            ┆ Inc.2023   │
│ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ 8      ┆ … ┆ 610809  ┆ 715951   ┆ -100056    ┆ ACTUALSABC │
│         ┆          ┆             ┆        ┆   ┆         ┆          ┆            ┆ Inc.2023   │
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 2      ┆ … ┆ 783855  ┆ 226190   ┆ 667217     ┆ ACTUALSABC │
│         ┆          ┆             ┆        ┆   ┆         ┆          ┆            ┆ Inc.2020   │
└─────────┴──────────┴─────────────┴────────┴───┴─────────┴──────────┴────────────┴────────────┘>

#### using Expression to apply List & Arrays

In [89]:
########################
## CUSTOMER DataFrame ##
########################

import random
from datetime import datetime

customer = pl.DataFrame({
    "ID":  list(range(100, 250, 10)),
    "AS_OF_DATE" : datetime(2022, 1, 1),
    "DESCRIPTION" : ["Customer 1","Customer 2","Customer 3","Customer 4","Customer 5"] * 3,
    "ADDRESS" : [["Address 1a, Address 1b"],["Address 2a, Address 2b"],
                 ["Address 3a, Address 3b"],["Address 4a, Address 4b"],
                 ["Address 5a, Address 5b"]] * 3,
    "PHONE1" : [[100100,100200],[200100,200200],[300100,300200],
                [400100,400200],[500100,500200]] * 3,
    "PHONE2" : ["100100 | 100200","200100 | 200200","300100 | 300200",
                "400100 | 400200","500100 | 500200"] * 3,
    "PHONE3" : [["100100 | 100200 | 100300 | 100400 | 100500"],
                ["200100 | 200200 | 200300 | 200400 | 200500"],
                ["300100 | 300200 | 300300 | 300400 | 300500"],
                ["400100 | 300200 | 400300 | 400400 | 400500"],
                ["500100 | 500200 | 500300 | 500400 | 500500"],
                ] 
                * 3,
    "EMAIL" : ["1a@email 1b@email","2a@email 2b@email","3a@email 3b@email",
               "4a@email 4b@email","5a@email 5b@email donotreply@email"] * 3,
    "STATUS" : "Active",
    "TYPE" : ["Corp","Gov","Individual"] * 5,
    "CATEGORY" : random.choices(category["ID"], k=15),
})
customer.sample(5).with_row_index("Row #")
# Address, PHONE1, PHONE3, EMAIL are lists of [str, int, str, str]
# PHONE2, EMAIL contains a list, but is saved as str

shape: (5, 12)
┌───────┬─────┬────────────────┬─────────────┬───┬────────────────┬────────┬────────────┬──────────┐
│ Row # ┆ ID  ┆ AS_OF_DATE     ┆ DESCRIPTION ┆ … ┆ EMAIL          ┆ STATUS ┆ TYPE       ┆ CATEGORY │
│ ---   ┆ --- ┆ ---            ┆ ---         ┆   ┆ ---            ┆ ---    ┆ ---        ┆ ---      │
│ u32   ┆ i64 ┆ datetime[μs]   ┆ str         ┆   ┆ str            ┆ str    ┆ str        ┆ i64      │
╞═══════╪═════╪════════════════╪═════════════╪═══╪════════════════╪════════╪════════════╪══════════╡
│ 0     ┆ 220 ┆ 2022-01-01     ┆ Customer 3  ┆ … ┆ 3a@email       ┆ Active ┆ Corp       ┆ 1400     │
│       ┆     ┆ 00:00:00       ┆             ┆   ┆ 3b@email       ┆        ┆            ┆          │
│ 1     ┆ 150 ┆ 2022-01-01     ┆ Customer 1  ┆ … ┆ 1a@email       ┆ Active ┆ Individual ┆ 2300     │
│       ┆     ┆ 00:00:00       ┆             ┆   ┆ 1b@email       ┆        ┆            ┆          │
│ 2     ┆ 240 ┆ 2022-01-01     ┆ Customer 5  ┆ … ┆ 5a@email       ┆ Active ┆ Individual ┆ 1800     │
│       ┆     ┆ 00:00:00       ┆             ┆   ┆ 5b@email       ┆        ┆            ┆          │
│       ┆     ┆                ┆             ┆   ┆ donotreply@e…  ┆        ┆            ┆          │
│ 3     ┆ 210 ┆ 2022-01-01     ┆ Customer 2  ┆ … ┆ 2a@email       ┆ Active ┆ Individual ┆ 2000     │
│       ┆     ┆ 00:00:00       ┆             ┆   ┆ 2b@email       ┆        ┆            ┆          │
│ 4     ┆ 200 ┆ 2022-01-01     ┆ Customer 1  ┆ … ┆ 1a@email       ┆ Active ┆ Gov        ┆ 1200     │
│       ┆     ┆ 00:00:00       ┆             ┆   ┆ 1b@email       ┆        ┆            ┆          │
└───────┴─────┴────────────────┴─────────────┴───┴────────────────┴────────┴────────────┴──────────┘

In [100]:
# Polars provide powerful List manipulations methods

# creating a list

out = customer.select(
    pl.col("ID"),
    pl.col("DESCRIPTION"),
    pl.col("PHONE1"),
    
    # PHONE1: Convert list of ints to list of strings
    pl.col("PHONE1").list.eval(pl.element().cast(pl.Utf8)).alias("Phone1_Str_List"),
    
    pl.col("PHONE2"),
    # PHONE2: Split string into list
    pl.col("PHONE2").str.split(" \\| ", literal=True).alias("PHONE2_new"),
    
    pl.col("PHONE3"),
    # PHONE3: Split and Explode with explicit parameters to silence warnings
    pl.col("PHONE3")
      .list.eval(pl.element().str.split(" \\| ", literal=True))
      .list.explode(empty_as_null=False) # Explicitly set to False (new default) or True (old default)
      .alias("new")
)

print(out)

shape: (15, 8)
┌─────┬─────────────┬─────────────┬────────────┬────────────┬────────────┬────────────┬────────────┐
│ ID  ┆ DESCRIPTION ┆ PHONE1      ┆ Phone1_Str ┆ PHONE2     ┆ PHONE2_new ┆ PHONE3     ┆ new        │
│ --- ┆ ---         ┆ ---         ┆ _List      ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ i64 ┆ str         ┆ list[i64]   ┆ ---        ┆ str        ┆ list[str]  ┆ list[str]  ┆ list[str]  │
│     ┆             ┆             ┆ list[str]  ┆            ┆            ┆            ┆            │
╞═════╪═════════════╪═════════════╪════════════╪════════════╪════════════╪════════════╪════════════╡
│ 100 ┆ Customer 1  ┆ [100100,    ┆ ["100100", ┆ 100100 |   ┆ ["100100 | ┆ ["100100 | ┆ ["100100 | │
│     ┆             ┆ 100200]     ┆ "100200"]  ┆ 100200     ┆ 100200"]   ┆ 100200 |   ┆ 100200 |   │
│     ┆             ┆             ┆            ┆            ┆            ┆ 100300 |   ┆ 100300 |   │
│     ┆             ┆             ┆            ┆            ┆            ┆ 1…         ┆ 1…         │
│ 110 ┆ Customer 2  ┆ [200100,    ┆ ["200100", ┆ 200100 |   ┆ ["200100 | ┆ ["200100 | ┆ ["200100 | │
│     ┆             ┆ 200200]     ┆ "200200"]  ┆ 200200     ┆ 200200"]   ┆ 200200 |   ┆ 200200 |   │
│     ┆             ┆             ┆            ┆            ┆            ┆ 200300 |   ┆ 200300 |   │
│     ┆             ┆             ┆            ┆            ┆            ┆ 2…         ┆ 2…         │
│ 120 ┆ Customer 3  ┆ [300100,    ┆ ["300100", ┆ 300100 |   ┆ ["300100 | ┆ ["300100 | ┆ ["300100 | │
│     ┆             ┆ 300200]     ┆ "300200"]  ┆ 300200     ┆ 300200"]   ┆ 300200 |   ┆ 300200 |   │
│     ┆             ┆             ┆            ┆            ┆            ┆ 300300 |   ┆ 300300 |   │
│     ┆             ┆             ┆            ┆            ┆            ┆ 3…         ┆ 3…         │
│ 130 ┆ Customer 4  ┆ [400100,    ┆ ["400100", ┆ 400100 |   ┆ ["400100 | ┆ ["400100 | ┆ ["400100 | │
│     ┆             ┆ 400200]     ┆ "400200"]  ┆ 400200     ┆ 400200"]   ┆ 300200 |   ┆ 300200 |   │
│     ┆             ┆             ┆            ┆            ┆            ┆ 400300 |   ┆ 400300 |   │
│     ┆             ┆             ┆            ┆            ┆            ┆ 4…         ┆ 4…         │
│ 140 ┆ Customer 5  ┆ [500100,    ┆ ["500100", ┆ 500100 |   ┆ ["500100 | ┆ ["500100 | ┆ ["500100 | │
│     ┆             ┆ 500200]     ┆ "500200"]  ┆ 500200     ┆ 500200"]   ┆ 500200 |   ┆ 500200 |   │
│     ┆             ┆             ┆            ┆            ┆            ┆ 500300 |   ┆ 500300 |   │
│     ┆             ┆             ┆            ┆            ┆            ┆ 5…         ┆ 5…         │
│ …   ┆ …           ┆ …           ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          │
│ 200 ┆ Customer 1  ┆ [100100,    ┆ ["100100", ┆ 100100 |   ┆ ["100100 | ┆ ["100100 | ┆ ["100100 | │
│     ┆             ┆ 100200]     ┆ "100200"]  ┆ 100200     ┆ 100200"]   ┆ 100200 |   ┆ 100200 |   │
│     ┆             ┆             ┆            ┆            ┆            ┆ 100300 |   ┆ 100300 |   │
│     ┆             ┆             ┆            ┆            ┆            ┆ 1…         ┆ 1…         │
│ 210 ┆ Customer 2  ┆ [200100,    ┆ ["200100", ┆ 200100 |   ┆ ["200100 | ┆ ["200100 | ┆ ["200100 | │
│     ┆             ┆ 200200]     ┆ "200200"]  ┆ 200200     ┆ 200200"]   ┆ 200200 |   ┆ 200200 |   │
│     ┆             ┆             ┆            ┆            ┆            ┆ 200300 |   ┆ 200300 |   │
│     ┆             ┆             ┆            ┆            ┆            ┆ 2…         ┆ 2…         │
│ 220 ┆ Customer 3  ┆ [300100,    ┆ ["300100", ┆ 300100 |   ┆ ["300100 | ┆ ["300100 | ┆ ["300100 | │
│     ┆             ┆ 300200]     ┆ "300200"]  ┆ 300200     ┆ 300200"]   ┆ 300200 |   ┆ 300200 |   │
│     ┆             ┆             ┆            ┆            ┆            ┆ 300300 |   ┆ 300300 |   │
│     ┆             ┆             ┆            ┆            ┆            ┆ 3…         ┆ 3…         │
│ 230 ┆ Customer 4  ┆ [400100,    ┆ ["400100", ┆ 400100 |   ┆ ["400100 | ┆ ["400100 | ┆ ["400100 | │
│     ┆             ┆ 400200]     ┆ "400200"]  ┆ 400200     ┆ 400200"]   ┆ 300200 |   ┆ 300200 |   │
│     ┆             ┆             ┆            ┆            ┆            ┆ 400300 |   ┆ 400300 |   │
│     ┆             ┆             ┆            ┆            ┆            ┆ 4…         ┆ 4…         │
│ 240 ┆ Customer 5  ┆ [500100,    ┆ ["500100", ┆ 500100 |   ┆ ["500100 | ┆ ["500100 | ┆ ["500100 | │
│     ┆             ┆ 500200]     ┆ "500200"]  ┆ 500200     ┆ 500200"]   ┆ 500200 |   ┆ 500200 |   │
│     ┆             ┆             ┆            ┆            ┆            ┆ 500300 |   ┆ 500300 |   │
│     ┆             ┆             ┆            ┆            ┆            ┆ 5…         ┆ 5…         │
└─────┴─────────────┴─────────────┴────────────┴────────────┴────────────┴────────────┴────────────┘

In [108]:
# once you have a list to work with
# use explode() to break list content by rows
# say, list all phone #s by customers from PHONE1 column

out = customer.select(
    pl.col("ID"),
    pl.col("DESCRIPTION"),
    # Note: casting a scalar to List usually requires .implode() or similar, 
    # but assuming PHONE1 is already a list or this cast works in your context:
    pl.col("PHONE1").cast(pl.List(pl.Utf8)).alias("Phone1_Int_to-Str"),
).explode("Phone1_Int_to-Str", empty_as_null=False) # Explicitly set the parameter

print(out)

# out = customer.select(
#     pl.col("ID"),
#     pl.col("DESCRIPTION"),
#     pl.col("PHONE3"),
#     pl.col("PHONE3")
#         .list.eval(pl.element().str.split(" | ", literal=True))
#         .list.explode(empty_as_null=False)
#         .alias("new")
# )
# print(out)

shape: (30, 3)
┌─────┬─────────────┬───────────────────┐
│ ID  ┆ DESCRIPTION ┆ Phone1_Int_to-Str │
│ --- ┆ ---         ┆ ---               │
│ i64 ┆ str         ┆ str               │
╞═════╪═════════════╪═══════════════════╡
│ 100 ┆ Customer 1  ┆ 100100            │
│ 100 ┆ Customer 1  ┆ 100200            │
│ 110 ┆ Customer 2  ┆ 200100            │
│ 110 ┆ Customer 2  ┆ 200200            │
│ 120 ┆ Customer 3  ┆ 300100            │
│ …   ┆ …           ┆ …                 │
│ 220 ┆ Customer 3  ┆ 300200            │
│ 230 ┆ Customer 4  ┆ 400100            │
│ 230 ┆ Customer 4  ┆ 400200            │
│ 240 ┆ Customer 5  ┆ 500100            │
│ 240 ┆ Customer 5  ┆ 500200            │
└─────┴─────────────┴───────────────────┘

In [110]:
# operating on list columns
# using list methods inside columns to view slice of data
# for example , PHONE3 column has 5 values in list
# use head(), tail(), slice(), length()

out = customer.select(
    pl.col("ID"),
    pl.col("DESCRIPTION"),
    # Use literal=True for safety and speed; empty_as_null handles the warning context
    pl.col("PHONE3").explode(empty_as_null=False).str.split(" | ", literal=True).alias("new"),
).with_columns(
    pl.col("new").list.head(3).alias("top3"),
    pl.col("new").list.slice(-3, 3).alias("bottom_3"),
    pl.col("new").list.len().alias("observations"),  # Changed from .lengths() to .len()
)

print(out)

shape: (15, 6)
┌─────┬─────────────┬───────────────┬───────────────────────┬───────────────────────┬──────────────┐
│ ID  ┆ DESCRIPTION ┆ new           ┆ top3                  ┆ bottom_3              ┆ observations │
│ --- ┆ ---         ┆ ---           ┆ ---                   ┆ ---                   ┆ ---          │
│ i64 ┆ str         ┆ list[str]     ┆ list[str]             ┆ list[str]             ┆ u32          │
╞═════╪═════════════╪═══════════════╪═══════════════════════╪═══════════════════════╪══════════════╡
│ 100 ┆ Customer 1  ┆ ["100100",    ┆ ["100100", "100200",  ┆ ["100300", "100400",  ┆ 5            │
│     ┆             ┆ "100200", …   ┆ "100300"]             ┆ "100500"]             ┆              │
│     ┆             ┆ "100500…      ┆                       ┆                       ┆              │
│ 110 ┆ Customer 2  ┆ ["200100",    ┆ ["200100", "200200",  ┆ ["200300", "200400",  ┆ 5            │
│     ┆             ┆ "200200", …   ┆ "200300"]             ┆ "200500"]             ┆              │
│     ┆             ┆ "200500…      ┆                       ┆                       ┆              │
│ 120 ┆ Customer 3  ┆ ["300100",    ┆ ["300100", "300200",  ┆ ["300300", "300400",  ┆ 5            │
│     ┆             ┆ "300200", …   ┆ "300300"]             ┆ "300500"]             ┆              │
│     ┆             ┆ "300500…      ┆                       ┆                       ┆              │
│ 130 ┆ Customer 4  ┆ ["400100",    ┆ ["400100", "300200",  ┆ ["400300", "400400",  ┆ 5            │
│     ┆             ┆ "300200", …   ┆ "400300"]             ┆ "400500"]             ┆              │
│     ┆             ┆ "400500…      ┆                       ┆                       ┆              │
│ 140 ┆ Customer 5  ┆ ["500100",    ┆ ["500100", "500200",  ┆ ["500300", "500400",  ┆ 5            │
│     ┆             ┆ "500200", …   ┆ "500300"]             ┆ "500500"]             ┆              │
│     ┆             ┆ "500500…      ┆                       ┆                       ┆              │
│ …   ┆ …           ┆ …             ┆ …                     ┆ …                     ┆ …            │
│ 200 ┆ Customer 1  ┆ ["100100",    ┆ ["100100", "100200",  ┆ ["100300", "100400",  ┆ 5            │
│     ┆             ┆ "100200", …   ┆ "100300"]             ┆ "100500"]             ┆              │
│     ┆             ┆ "100500…      ┆                       ┆                       ┆              │
│ 210 ┆ Customer 2  ┆ ["200100",    ┆ ["200100", "200200",  ┆ ["200300", "200400",  ┆ 5            │
│     ┆             ┆ "200200", …   ┆ "200300"]             ┆ "200500"]             ┆              │
│     ┆             ┆ "200500…      ┆                       ┆                       ┆              │
│ 220 ┆ Customer 3  ┆ ["300100",    ┆ ["300100", "300200",  ┆ ["300300", "300400",  ┆ 5            │
│     ┆             ┆ "300200", …   ┆ "300300"]             ┆ "300500"]             ┆              │
│     ┆             ┆ "300500…      ┆                       ┆                       ┆              │
│ 230 ┆ Customer 4  ┆ ["400100",    ┆ ["400100", "300200",  ┆ ["400300", "400400",  ┆ 5            │
│     ┆             ┆ "300200", …   ┆ "400300"]             ┆ "400500"]             ┆              │
│     ┆             ┆ "400500…      ┆                       ┆                       ┆              │
│ 240 ┆ Customer 5  ┆ ["500100",    ┆ ["500100", "500200",  ┆ ["500300", "500400",  ┆ 5            │
│     ┆             ┆ "500200", …   ┆ "500300"]             ┆ "500500"]             ┆              │
│     ┆             ┆ "500500…      ┆                       ┆                       ┆              │
└─────┴─────────────┴───────────────┴───────────────────────┴───────────────────────┴──────────────┘

In [111]:
# working with List elements
# let;s say, we want to list customers with
# number of invalid emailIDs

out = customer.select(
    pl.col("ID"),
    pl.col("DESCRIPTION"),
    pl.col("EMAIL"),
)
print(out)
# for example, Customer 5 has one email ID = donotreply

out = out.with_columns(
    pl.col("EMAIL").str.split(" ").list.eval(pl.element().str.contains("donotreply"))
    .list.sum().alias("InvalidEMAILs")
)
print(out)

shape: (15, 3)
┌─────┬─────────────┬─────────────────────────────────┐
│ ID  ┆ DESCRIPTION ┆ EMAIL                           │
│ --- ┆ ---         ┆ ---                             │
│ i64 ┆ str         ┆ str                             │
╞═════╪═════════════╪═════════════════════════════════╡
│ 100 ┆ Customer 1  ┆ 1a@email 1b@email               │
│ 110 ┆ Customer 2  ┆ 2a@email 2b@email               │
│ 120 ┆ Customer 3  ┆ 3a@email 3b@email               │
│ 130 ┆ Customer 4  ┆ 4a@email 4b@email               │
│ 140 ┆ Customer 5  ┆ 5a@email 5b@email donotreply@e… │
│ …   ┆ …           ┆ …                               │
│ 200 ┆ Customer 1  ┆ 1a@email 1b@email               │
│ 210 ┆ Customer 2  ┆ 2a@email 2b@email               │
│ 220 ┆ Customer 3  ┆ 3a@email 3b@email               │
│ 230 ┆ Customer 4  ┆ 4a@email 4b@email               │
│ 240 ┆ Customer 5  ┆ 5a@email 5b@email donotreply@e… │
└─────┴─────────────┴─────────────────────────────────┘
shape: (15, 4)
┌─────┬─────────────┬─────────────────────────────────┬───────────────┐
│ ID  ┆ DESCRIPTION ┆ EMAIL                           ┆ InvalidEMAILs │
│ --- ┆ ---         ┆ ---                             ┆ ---           │
│ i64 ┆ str         ┆ str                             ┆ u32           │
╞═════╪═════════════╪═════════════════════════════════╪═══════════════╡
│ 100 ┆ Customer 1  ┆ 1a@email 1b@email               ┆ 0             │
│ 110 ┆ Customer 2  ┆ 2a@email 2b@email               ┆ 0             │
│ 120 ┆ Customer 3  ┆ 3a@email 3b@email               ┆ 0             │
│ 130 ┆ Customer 4  ┆ 4a@email 4b@email               ┆ 0             │
│ 140 ┆ Customer 5  ┆ 5a@email 5b@email donotreply@e… ┆ 1             │
│ …   ┆ …           ┆ …                               ┆ …             │
│ 200 ┆ Customer 1  ┆ 1a@email 1b@email               ┆ 0             │
│ 210 ┆ Customer 2  ┆ 2a@email 2b@email               ┆ 0             │
│ 220 ┆ Customer 3  ┆ 3a@email 3b@email               ┆ 0             │
│ 230 ┆ Customer 4  ┆ 4a@email 4b@email               ┆ 0             │
│ 240 ┆ Customer 5  ┆ 5a@email 5b@email donotreply@e… ┆ 1             │
└─────┴─────────────┴─────────────────────────────────┴───────────────┘

In [113]:
import polars as pl

sampleDF = pl.DataFrame(
    {
        "ID": list(range(1, 5)),
        # Explicitly define the dtype to handle mixed int/float values as Float64
        "NUMBER": [[7, 3.5, 3.5, 1, 2],
                   [6, 2.5, 3.5, 1, 4],
                   [3, 3.5, 3.5, 5, 5],
                   [2, 3.5, 3.5, 4, 3]]
    },
    schema_overrides={"NUMBER": pl.List(pl.Float64)}
)

print(sampleDF)

# Define the rank percentage expression
# Note: pl.col("*").count() inside list.eval refers to the count of elements in that specific list
rank_pct = (pl.element().rank(descending=True) / pl.element().count()).round(2)

out = sampleDF.with_columns(
    # Create a list of all numeric columns (excluding ID)
    pl.concat_list(pl.all().exclude("ID")).alias("all_numbers")
).select(
    # Keep original columns
    pl.all().exclude("all_numbers"),
    # Compute rank within each list
    pl.col("all_numbers").list.eval(rank_pct, parallel=True).alias("NUMBERS_RANK"),
)

print(out)

shape: (4, 2)
┌─────┬───────────────────┐
│ ID  ┆ NUMBER            │
│ --- ┆ ---               │
│ i64 ┆ list[f64]         │
╞═════╪═══════════════════╡
│ 1   ┆ [7.0, 3.5, … 2.0] │
│ 2   ┆ [6.0, 2.5, … 4.0] │
│ 3   ┆ [3.0, 3.5, … 5.0] │
│ 4   ┆ [2.0, 3.5, … 3.0] │
└─────┴───────────────────┘
shape: (4, 3)
┌─────┬───────────────────┬───────────────────┐
│ ID  ┆ NUMBER            ┆ NUMBERS_RANK      │
│ --- ┆ ---               ┆ ---               │
│ i64 ┆ list[f64]         ┆ list[f64]         │
╞═════╪═══════════════════╪═══════════════════╡
│ 1   ┆ [7.0, 3.5, … 2.0] ┆ [0.2, 0.5, … 0.8] │
│ 2   ┆ [6.0, 2.5, … 4.0] ┆ [0.2, 0.8, … 0.4] │
│ 3   ┆ [3.0, 3.5, … 5.0] ┆ [1.0, 0.7, … 0.3] │
│ 4   ┆ [2.0, 3.5, … 3.0] ┆ [1.0, 0.5, … 0.8] │
└─────┴───────────────────┴───────────────────┘

In [116]:
# applying RANK | eval functions on BALANCE SHEET data
# for example

############################
## BalanceSheet DataFrame ##
############################
import polars as pl
import random

sampleSize = 100_000
org = "ABC Inc."
ledger_type = "ACTUALS"
fiscal_year_from = 2020
fiscal_year_to = 2023
random.seed(123)

balanceSheet = pl.DataFrame({
    "LEDGER": ledger_type,
    "ORG": org,
    "FISCAL_YEAR": random.choices(list(range(fiscal_year_from, fiscal_year_to + 1)), k=sampleSize),
    "PERIOD": random.choices(list(range(1, 13)), k=sampleSize),
    "ASSETS": random.sample(range(1000000), sampleSize),
    "LIABILITY": random.sample(range(1000000), sampleSize),
    "REVENUE": random.sample(range(1000000), sampleSize),
    "NETWORTH": random.sample(range(1000000), sampleSize),
})

# Use pl.len() instead of pl.col("*").count()
# pl.len() inside list.eval refers to the length of the list being evaluated
rank_pct = (pl.element().rank(descending=True) / pl.len()).round(2)

out = balanceSheet.with_columns(
    pl.concat_list(pl.all().exclude("LEDGER", "ORG", "FISCAL_YEAR", "PERIOD")).alias("all_CASHFLOW")
).select(
    pl.all().exclude("all_CASHFLOW"),
    pl.col("all_CASHFLOW").list.eval(rank_pct, parallel=True).alias("cf_RANK"),
)

print(out.sample(5))

shape: (5, 9)
┌─────────┬──────────┬─────────────┬────────┬───┬───────────┬─────────┬──────────┬─────────────────┐
│ LEDGER  ┆ ORG      ┆ FISCAL_YEAR ┆ PERIOD ┆ … ┆ LIABILITY ┆ REVENUE ┆ NETWORTH ┆ cf_RANK         │
│ ---     ┆ ---      ┆ ---         ┆ ---    ┆   ┆ ---       ┆ ---     ┆ ---      ┆ ---             │
│ str     ┆ str      ┆ i64         ┆ i64    ┆   ┆ i64       ┆ i64     ┆ i64      ┆ list[f64]       │
╞═════════╪══════════╪═════════════╪════════╪═══╪═══════════╪═════════╪══════════╪═════════════════╡
│ ACTUALS ┆ ABC Inc. ┆ 2022        ┆ 4      ┆ … ┆ 621095    ┆ 235601  ┆ 322555   ┆ [0.5, 0.25, …   │
│         ┆          ┆             ┆        ┆   ┆           ┆         ┆          ┆ 0.75]           │
│ ACTUALS ┆ ABC Inc. ┆ 2021        ┆ 10     ┆ … ┆ 905296    ┆ 57662   ┆ 901329   ┆ [0.75, 0.25, …  │
│         ┆          ┆             ┆        ┆   ┆           ┆         ┆          ┆ 0.5]            │
│ ACTUALS ┆ ABC Inc. ┆ 2021        ┆ 4      ┆ … ┆ 407562    ┆ 660294  ┆ 607661   ┆ [0.75, 1.0, …   │
│         ┆          ┆             ┆        ┆   ┆           ┆         ┆          ┆ 0.5]            │
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 10     ┆ … ┆ 330912    ┆ 419232  ┆ 829203   ┆ [0.5, 1.0, …    │
│         ┆          ┆             ┆        ┆   ┆           ┆         ┆          ┆ 0.25]           │
│ ACTUALS ┆ ABC Inc. ┆ 2022        ┆ 12     ┆ … ┆ 577985    ┆ 85112   ┆ 353014   ┆ [0.25, 0.5, …   │
│         ┆          ┆             ┆        ┆   ┆           ┆         ┆          ┆ 0.75]           │
└─────────┴──────────┴─────────────┴────────┴───┴───────────┴─────────┴──────────┴─────────────────┘

In [121]:
# Polars Array datatype
# Arrays are a new data type that was recently introduced, 
# and are still pretty nascent in features that it offers. 

# The major difference between a List and an Array is that the latter
# is limited to having the same number of elements per row,
# while a List can have a variable number of elements. 

# Both still require that each element's data type is the same.

import polars as pl

array_df = pl.DataFrame(
    [
        pl.Series("Array_1", [[1, 3], [2, 5]]),
        pl.Series("Array_2", [[1, 7, 3], [8, 1, 0]]),
    ],
    schema={"Array_1": pl.Array(pl.Int64, shape=2), "Array_2": pl.Array(pl.Int64, shape=3)},
)

print(array_df)

out = array_df.select(
    # Cast to List first, then use .list.sum() / .list.min()
    pl.col("Array_1").cast(pl.List(pl.Int64)).list.min().alias("Array_1_min"),
    pl.col("Array_2").cast(pl.List(pl.Int64)).list.sum().alias("Array_2_sum"),
)

print(out)

shape: (2, 2)
┌───────────────┬───────────────┐
│ Array_1       ┆ Array_2       │
│ ---           ┆ ---           │
│ array[i64, 2] ┆ array[i64, 3] │
╞═══════════════╪═══════════════╡
│ [1, 3]        ┆ [1, 7, 3]     │
│ [2, 5]        ┆ [8, 1, 0]     │
└───────────────┴───────────────┘
shape: (2, 2)
┌─────────────┬─────────────┐
│ Array_1_min ┆ Array_2_sum │
│ ---         ┆ ---         │
│ i64         ┆ i64         │
╞═════════════╪═════════════╡
│ 1           ┆ 11          │
│ 2           ┆ 9           │
└─────────────┴─────────────┘

In [123]:
# like Polars List and Arrays, which allows users to work with data in sets
# Polars provide one more datatype Struct
# Struct data type is different than List and Arrays
# as Struct allows users to work with multiple columns without copying actual data

# Struct
############################
## BalanceSheet DataFrame ##
############################
import random
from datetime import datetime

sampleSize = 100_000
org = "ABC Inc."
ledger_type = "ACTUALS" # BUDGET, STATS are other Ledger types
fiscal_year_from = 2020
fiscal_year_to = 2023
random.seed(123)

balanceSheet = pl.DataFrame({
	"LEDGER" : ledger_type,
	"ORG" : org,
	"FISCAL_YEAR": random.choices(list(range(fiscal_year_from, 
                                          fiscal_year_to+1, 1)),k=sampleSize),
	"PERIOD": random.choices(list(range(1, 12+1, 1)),k=sampleSize),
	"ASSETS": random.sample(range(1000000), sampleSize),
    "LIABILITY": random.sample(range(1000000), sampleSize),
    "REVENUE": random.sample(range(1000000), sampleSize),
    "NETWORTH": random.sample(range(1000000), sampleSize),
})
print(balanceSheet.sample(5).with_row_index("Row #"))

out = balanceSheet.select(pl.col("FISCAL_YEAR").value_counts(sort=True))
print(out)

shape: (5, 9)
┌───────┬─────────┬──────────┬─────────────┬───┬────────┬───────────┬─────────┬──────────┐
│ Row # ┆ LEDGER  ┆ ORG      ┆ FISCAL_YEAR ┆ … ┆ ASSETS ┆ LIABILITY ┆ REVENUE ┆ NETWORTH │
│ ---   ┆ ---     ┆ ---      ┆ ---         ┆   ┆ ---    ┆ ---       ┆ ---     ┆ ---      │
│ u32   ┆ str     ┆ str      ┆ i64         ┆   ┆ i64    ┆ i64       ┆ i64     ┆ i64      │
╞═══════╪═════════╪══════════╪═════════════╪═══╪════════╪═══════════╪═════════╪══════════╡
│ 0     ┆ ACTUALS ┆ ABC Inc. ┆ 2021        ┆ … ┆ 175241 ┆ 475688    ┆ 337001  ┆ 842909   │
│ 1     ┆ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ … ┆ 406124 ┆ 428539    ┆ 828011  ┆ 920864   │
│ 2     ┆ ACTUALS ┆ ABC Inc. ┆ 2022        ┆ … ┆ 263392 ┆ 786931    ┆ 893209  ┆ 559320   │
│ 3     ┆ ACTUALS ┆ ABC Inc. ┆ 2021        ┆ … ┆ 670931 ┆ 634408    ┆ 220428  ┆ 454253   │
│ 4     ┆ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ … ┆ 507714 ┆ 484218    ┆ 581725  ┆ 110447   │
└───────┴─────────┴──────────┴─────────────┴───┴────────┴───────────┴─────────┴──────────┘
shape: (4, 1)
┌──────────────┐
│ FISCAL_YEAR  │
│ ---          │
│ struct[2]    │
╞══════════════╡
│ {2023,25136} │
│ {2021,25036} │
│ {2020,24957} │
│ {2022,24871} │
└──────────────┘

In [124]:
# using unnest will convert Struct to regular data frame
out = balanceSheet.select(pl.col("FISCAL_YEAR").value_counts(sort=True)).unnest("FISCAL_YEAR")
print(out)

shape: (4, 2)
┌─────────────┬───────┐
│ FISCAL_YEAR ┆ count │
│ ---         ┆ ---   │
│ i64         ┆ u32   │
╞═════════════╪═══════╡
│ 2023        ┆ 25136 │
│ 2021        ┆ 25036 │
│ 2020        ┆ 24957 │
│ 2022        ┆ 24871 │
└─────────────┴───────┘

In [125]:
# using Struct to identify duplicates
out = balanceSheet.filter(pl.struct("LEDGER","ORG","FISCAL_YEAR","PERIOD","ASSETS").is_duplicated())
# is_duplicated() is same as is_unique()
print(out)

shape: (0, 8)
┌────────┬─────┬─────────────┬────────┬────────┬───────────┬─────────┬──────────┐
│ LEDGER ┆ ORG ┆ FISCAL_YEAR ┆ PERIOD ┆ ASSETS ┆ LIABILITY ┆ REVENUE ┆ NETWORTH │
│ ---    ┆ --- ┆ ---         ┆ ---    ┆ ---    ┆ ---       ┆ ---     ┆ ---      │
│ str    ┆ str ┆ i64         ┆ i64    ┆ i64    ┆ i64       ┆ i64     ┆ i64      │
╞════════╪═════╪═════════════╪════════╪════════╪═══════════╪═════════╪══════════╡
└────────┴─────┴─────────────┴────────┴────────┴───────────┴─────────┴──────────┘

In [126]:
# using Struct for multi column Ranking
# This is another very useful feature of Polars

# consider a situation, when you are working with TimeSeries data
# and want to fill in missing data based on certain RANK

out = balanceSheet.with_columns(
    pl.struct("FISCAL_YEAR", "PERIOD")
    .rank("dense", descending=True)
    .over("LEDGER", "ORG", "ASSETS")
    .alias("Rank")
)
# .filter(pl.struct("LEDGER", "ORG", "ASSETS").is_duplicated())
print(out)

shape: (100_000, 9)
┌─────────┬──────────┬─────────────┬────────┬───┬───────────┬─────────┬──────────┬──────┐
│ LEDGER  ┆ ORG      ┆ FISCAL_YEAR ┆ PERIOD ┆ … ┆ LIABILITY ┆ REVENUE ┆ NETWORTH ┆ Rank │
│ ---     ┆ ---      ┆ ---         ┆ ---    ┆   ┆ ---       ┆ ---     ┆ ---      ┆ ---  │
│ str     ┆ str      ┆ i64         ┆ i64    ┆   ┆ i64       ┆ i64     ┆ i64      ┆ u32  │
╞═════════╪══════════╪═════════════╪════════╪═══╪═══════════╪═════════╪══════════╪══════╡
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 10     ┆ … ┆ 535987    ┆ 825234  ┆ 630949   ┆ 1    │
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 1      ┆ … ┆ 708385    ┆ 401531  ┆ 307809   ┆ 1    │
│ ACTUALS ┆ ABC Inc. ┆ 2021        ┆ 12     ┆ … ┆ 202378    ┆ 777927  ┆ 536595   ┆ 1    │
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 3      ┆ … ┆ 378510    ┆ 445913  ┆ 400960   ┆ 1    │
│ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ 9      ┆ … ┆ 662509    ┆ 339738  ┆ 116069   ┆ 1    │
│ …       ┆ …        ┆ …           ┆ …      ┆ … ┆ …         ┆ …       ┆ …        ┆ …    │
│ ACTUALS ┆ ABC Inc. ┆ 2022        ┆ 7      ┆ … ┆ 931656    ┆ 523338  ┆ 286147   ┆ 1    │
│ ACTUALS ┆ ABC Inc. ┆ 2022        ┆ 6      ┆ … ┆ 274014    ┆ 812724  ┆ 541937   ┆ 1    │
│ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ 8      ┆ … ┆ 804535    ┆ 188039  ┆ 876970   ┆ 1    │
│ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ 8      ┆ … ┆ 752404    ┆ 610809  ┆ 715951   ┆ 1    │
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 2      ┆ … ┆ 489051    ┆ 783855  ┆ 226190   ┆ 1    │
└─────────┴──────────┴─────────────┴────────┴───┴───────────┴─────────┴──────────┴──────┘

#### Numpy conversion

In [129]:
# Polars expressions support NumPy ufuncs
# This means that if a function is not provided by Polars
# we can use NumPy and we still have fast columnar operation through the NumPy API.

import polars as pl

df = pl.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})

out = df.select(
    pl.all().log().name.suffix("_log")
)

print(out)

shape: (3, 2)
┌──────────┬──────────┐
│ a_log    ┆ b_log    │
│ ---      ┆ ---      │
│ f64      ┆ f64      │
╞══════════╪══════════╡
│ 0.0      ┆ 1.386294 │
│ 0.693147 ┆ 1.609438 │
│ 1.098612 ┆ 1.791759 │
└──────────┴──────────┘

### Functions, User defined functions and Windows function

In [130]:
# basic calculations using Polars expressions
df = pl.DataFrame(
    {
        "a": [1, 2, 3],
        "b": [10, 20, 30],
    }
)

out = df.select(
    (pl.col("a") + pl.col("b")).alias("sum"),
    pl.col("a").mean().alias("mean"),
    pl.col("a").min().alias("min"),
    pl.col("a").max().alias("max")
    )
out

shape: (3, 4)
┌─────┬──────┬─────┬─────┐
│ sum ┆ mean ┆ min ┆ max │
│ --- ┆ ---  ┆ --- ┆ --- │
│ i64 ┆ f64  ┆ i64 ┆ i64 │
╞═════╪══════╪═════╪═════╡
│ 11  ┆ 2.0  ┆ 1   ┆ 3   │
│ 22  ┆ 2.0  ┆ 1   ┆ 3   │
│ 33  ┆ 2.0  ┆ 1   ┆ 3   │
└─────┴──────┴─────┴─────┘

In [131]:
# Let's use Polars expression built-in functions
# to perform a conditional Algebric operation

# below sample DataFrame produces a Balance Sheet,
# however, NETWORTH calculated is wrong

############################
## BalanceSheet DataFrame ##
############################
import random
from datetime import datetime

sampleSize = 100_000
org = "ABC Inc."
ledger_type = "ACTUALS" # BUDGET, STATS are other Ledger types
fiscal_year_from = 2020
fiscal_year_to = 2023
random.seed(123)

balanceSheet = pl.DataFrame({
	"LEDGER" : ledger_type,
	"ORG" : org,
	"FISCAL_YEAR": random.choices(list(range(fiscal_year_from, 
                                          fiscal_year_to+1, 1)),k=sampleSize),
	"PERIOD": random.choices(list(range(1, 12+1, 1)),k=sampleSize),
	"ASSETS": random.sample(range(1000000), sampleSize),
    "LIABILITY": random.sample(range(1000000), sampleSize),
    "REVENUE": random.sample(range(1000000), sampleSize),
    "NETWORTH": random.sample(range(1000000), sampleSize),
})
print(balanceSheet.sample(5).with_row_index("Row #"))

shape: (5, 9)
┌───────┬─────────┬──────────┬─────────────┬───┬────────┬───────────┬─────────┬──────────┐
│ Row # ┆ LEDGER  ┆ ORG      ┆ FISCAL_YEAR ┆ … ┆ ASSETS ┆ LIABILITY ┆ REVENUE ┆ NETWORTH │
│ ---   ┆ ---     ┆ ---      ┆ ---         ┆   ┆ ---    ┆ ---       ┆ ---     ┆ ---      │
│ u32   ┆ str     ┆ str      ┆ i64         ┆   ┆ i64    ┆ i64       ┆ i64     ┆ i64      │
╞═══════╪═════════╪══════════╪═════════════╪═══╪════════╪═══════════╪═════════╪══════════╡
│ 0     ┆ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ … ┆ 502787 ┆ 789623    ┆ 285175  ┆ 998267   │
│ 1     ┆ ACTUALS ┆ ABC Inc. ┆ 2022        ┆ … ┆ 787195 ┆ 235555    ┆ 822464  ┆ 897849   │
│ 2     ┆ ACTUALS ┆ ABC Inc. ┆ 2021        ┆ … ┆ 459726 ┆ 188180    ┆ 266351  ┆ 11373    │
│ 3     ┆ ACTUALS ┆ ABC Inc. ┆ 2022        ┆ … ┆ 447007 ┆ 48914     ┆ 249785  ┆ 906524   │
│ 4     ┆ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ … ┆ 495547 ┆ 330795    ┆ 939699  ┆ 269574   │
└───────┴─────────┴──────────┴─────────────┴───┴────────┴───────────┴─────────┴──────────┘

#### Polars Functions

In [132]:
# let's use Polars expression as functions to
# A. calculate NetWorth_c = ASSETS + REVENUE - LIABILITY
# B. generate a unique COSTCenter String = LEDGER+ORG+FISCAL_YEAR

out = balanceSheet.with_columns(
        (pl.col("ASSETS") + pl.col("REVENUE") -  pl.col("LIABILITY"))
            .alias("NetWorth_c"),
        (pl.col("LEDGER") + pl.col("ORG") + pl.col("FISCAL_YEAR").cast(pl.Utf8))
            .alias("CostCenter"),
    )
print(out.head(5))

shape: (5, 10)
┌─────────┬──────────┬─────────────┬────────┬───┬─────────┬──────────┬────────────┬────────────┐
│ LEDGER  ┆ ORG      ┆ FISCAL_YEAR ┆ PERIOD ┆ … ┆ REVENUE ┆ NETWORTH ┆ NetWorth_c ┆ CostCenter │
│ ---     ┆ ---      ┆ ---         ┆ ---    ┆   ┆ ---     ┆ ---      ┆ ---        ┆ ---        │
│ str     ┆ str      ┆ i64         ┆ i64    ┆   ┆ i64     ┆ i64      ┆ i64        ┆ str        │
╞═════════╪══════════╪═════════════╪════════╪═══╪═════════╪══════════╪════════════╪════════════╡
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 10     ┆ … ┆ 825234  ┆ 630949   ┆ 358184     ┆ ACTUALSABC │
│         ┆          ┆             ┆        ┆   ┆         ┆          ┆            ┆ Inc.2020   │
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 1      ┆ … ┆ 401531  ┆ 307809   ┆ -289400    ┆ ACTUALSABC │
│         ┆          ┆             ┆        ┆   ┆         ┆          ┆            ┆ Inc.2020   │
│ ACTUALS ┆ ABC Inc. ┆ 2021        ┆ 12     ┆ … ┆ 777927  ┆ 536595   ┆ 597339     ┆ ACTUALSABC │
│         ┆          ┆             ┆        ┆   ┆         ┆          ┆            ┆ Inc.2021   │
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 3      ┆ … ┆ 445913  ┆ 400960   ┆ 398951     ┆ ACTUALSABC │
│         ┆          ┆             ┆        ┆   ┆         ┆          ┆            ┆ Inc.2020   │
│ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ 9      ┆ … ┆ 339738  ┆ 116069   ┆ -72121     ┆ ACTUALSABC │
│         ┆          ┆             ┆        ┆   ┆         ┆          ┆            ┆ Inc.2023   │
└─────────┴──────────┴─────────────┴────────┴───┴─────────┴──────────┴────────────┴────────────┘

#### user defined function

let's pretend, we have a function which is more complex in that case, a user defined function is required

for example, ORG incur interest on Liability, which is calculated as following and substracted from NetWorth

interest paid on Liability Accounts

math
    i = P (1 + r/n)^n*T

In [133]:
# user defined function

# let's first setup OOPs for Liability class
import random
class Liability:

    def __init__(self, P, n, r, t):
        self.principalAmount = P
        # self.rate = r/100
        self.rate = r/100
        self.compound = n # in case of simple interest, n = 1
        self.time = t/12

    def getLoanInterest(self):
    # compound rate interest deposit
        # returns a tuple of interest and Total
        return round(self.principalAmount 
                     * (1 + self.rate / self.compound)**(self.compound * self.time) 
                     - self.principalAmount, ndigits=2), round(self.principalAmount, ndigits=2)
    
def getInterest(amount):
    compound=1.0
    rate=2.875
    t=60
    d = Liability(amount, compound, rate, t)
    return d.getLoanInterest()

In [134]:
out = balanceSheet.with_columns(
    [
        pl.col("LIABILITY").map_elements(getInterest).alias("int_on_liab")
    ]
)
print(out)

shape: (100_000, 9)
┌─────────┬──────────┬─────────────┬────────┬───┬───────────┬─────────┬──────────┬─────────────┐
│ LEDGER  ┆ ORG      ┆ FISCAL_YEAR ┆ PERIOD ┆ … ┆ LIABILITY ┆ REVENUE ┆ NETWORTH ┆ int_on_liab │
│ ---     ┆ ---      ┆ ---         ┆ ---    ┆   ┆ ---       ┆ ---     ┆ ---      ┆ ---         │
│ str     ┆ str      ┆ i64         ┆ i64    ┆   ┆ i64       ┆ i64     ┆ i64      ┆ list[f64]   │
╞═════════╪══════════╪═════════════╪════════╪═══╪═══════════╪═════════╪══════════╪═════════════╡
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 10     ┆ … ┆ 535987    ┆ 825234  ┆ 630949   ┆ [81607.61,  │
│         ┆          ┆             ┆        ┆   ┆           ┆         ┆          ┆ 535987.0]   │
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 1      ┆ … ┆ 708385    ┆ 401531  ┆ 307809   ┆ [107856.36, │
│         ┆          ┆             ┆        ┆   ┆           ┆         ┆          ┆ 708385.0]   │
│ ACTUALS ┆ ABC Inc. ┆ 2021        ┆ 12     ┆ … ┆ 202378    ┆ 777927  ┆ 536595   ┆ [30813.41,  │
│         ┆          ┆             ┆        ┆   ┆           ┆         ┆          ┆ 202378.0]   │
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 3      ┆ … ┆ 378510    ┆ 445913  ┆ 400960   ┆ [57630.68,  │
│         ┆          ┆             ┆        ┆   ┆           ┆         ┆          ┆ 378510.0]   │
│ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ 9      ┆ … ┆ 662509    ┆ 339738  ┆ 116069   ┆ [100871.43, │
│         ┆          ┆             ┆        ┆   ┆           ┆         ┆          ┆ 662509.0]   │
│ …       ┆ …        ┆ …           ┆ …      ┆ … ┆ …         ┆ …       ┆ …        ┆ …           │
│ ACTUALS ┆ ABC Inc. ┆ 2022        ┆ 7      ┆ … ┆ 931656    ┆ 523338  ┆ 286147   ┆ [141850.87, │
│         ┆          ┆             ┆        ┆   ┆           ┆         ┆          ┆ 931656.0]   │
│ ACTUALS ┆ ABC Inc. ┆ 2022        ┆ 6      ┆ … ┆ 274014    ┆ 812724  ┆ 541937   ┆ [41720.47,  │
│         ┆          ┆             ┆        ┆   ┆           ┆         ┆          ┆ 274014.0]   │
│ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ 8      ┆ … ┆ 804535    ┆ 188039  ┆ 876970   ┆ [122495.84, │
│         ┆          ┆             ┆        ┆   ┆           ┆         ┆          ┆ 804535.0]   │
│ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ 8      ┆ … ┆ 752404    ┆ 610809  ┆ 715951   ┆ [114558.55, │
│         ┆          ┆             ┆        ┆   ┆           ┆         ┆          ┆ 752404.0]   │
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 2      ┆ … ┆ 489051    ┆ 783855  ┆ 226190   ┆ [74461.29,  │
│         ┆          ┆             ┆        ┆   ┆           ┆         ┆          ┆ 489051.0]   │
└─────────┴──────────┴─────────────┴────────┴───┴───────────┴─────────┴──────────┴─────────────┘

In [135]:
## ideal way of doing it, use Polars built in Expressions
# compound=1.0
# rate=2.875
# t=60

out = balanceSheet.with_columns(
    # create the list of homogeneous data
    pl.concat_list(pl.all()
                   .exclude(["LEDGER","ORG","FISCAL_YEAR",
                            "PERIOD","ASSETS","REVENUE","NETWORTH"]))
                            .alias("liab")
).select([
    # select all columns except the intermediate list
    pl.all().exclude("liab"),
    # compute the rank by calling `arr.eval`
    pl.col("LIABILITY").map_elements(lambda x: 
                                     round(x
                     * (1 + 2.875 / 1.0)**(1.0 * 60) 
                     - x, ndigits=2)
                             )
    .alias("liability_new_Calc")
])
print(out)

shape: (100_000, 9)
┌─────────┬──────────┬─────────────┬────────┬───┬───────────┬─────────┬──────────┬─────────────────┐
│ LEDGER  ┆ ORG      ┆ FISCAL_YEAR ┆ PERIOD ┆ … ┆ LIABILITY ┆ REVENUE ┆ NETWORTH ┆ liability_new_C │
│ ---     ┆ ---      ┆ ---         ┆ ---    ┆   ┆ ---       ┆ ---     ┆ ---      ┆ alc             │
│ str     ┆ str      ┆ i64         ┆ i64    ┆   ┆ i64       ┆ i64     ┆ i64      ┆ ---             │
│         ┆          ┆             ┆        ┆   ┆           ┆         ┆          ┆ f64             │
╞═════════╪══════════╪═════════════╪════════╪═══╪═══════════╪═════════╪══════════╪═════════════════╡
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 10     ┆ … ┆ 535987    ┆ 825234  ┆ 630949   ┆ 1.0604e41       │
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 1      ┆ … ┆ 708385    ┆ 401531  ┆ 307809   ┆ 1.4014e41       │
│ ACTUALS ┆ ABC Inc. ┆ 2021        ┆ 12     ┆ … ┆ 202378    ┆ 777927  ┆ 536595   ┆ 4.0037e40       │
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 3      ┆ … ┆ 378510    ┆ 445913  ┆ 400960   ┆ 7.4882e40       │
│ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ 9      ┆ … ┆ 662509    ┆ 339738  ┆ 116069   ┆ 1.3107e41       │
│ …       ┆ …        ┆ …           ┆ …      ┆ … ┆ …         ┆ …       ┆ …        ┆ …               │
│ ACTUALS ┆ ABC Inc. ┆ 2022        ┆ 7      ┆ … ┆ 931656    ┆ 523338  ┆ 286147   ┆ 1.8431e41       │
│ ACTUALS ┆ ABC Inc. ┆ 2022        ┆ 6      ┆ … ┆ 274014    ┆ 812724  ┆ 541937   ┆ 5.4209e40       │
│ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ 8      ┆ … ┆ 804535    ┆ 188039  ┆ 876970   ┆ 1.5916e41       │
│ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ 8      ┆ … ┆ 752404    ┆ 610809  ┆ 715951   ┆ 1.4885e41       │
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 2      ┆ … ┆ 489051    ┆ 783855  ┆ 226190   ┆ 9.6751e40       │
└─────────┴──────────┴─────────────┴────────┴───┴───────────┴─────────┴──────────┴─────────────────┘

#### windows function

In [137]:
print(balanceSheet.sample(5).with_row_index("Row #"))

shape: (5, 9)
┌───────┬─────────┬──────────┬─────────────┬───┬────────┬───────────┬─────────┬──────────┐
│ Row # ┆ LEDGER  ┆ ORG      ┆ FISCAL_YEAR ┆ … ┆ ASSETS ┆ LIABILITY ┆ REVENUE ┆ NETWORTH │
│ ---   ┆ ---     ┆ ---      ┆ ---         ┆   ┆ ---    ┆ ---       ┆ ---     ┆ ---      │
│ u32   ┆ str     ┆ str      ┆ i64         ┆   ┆ i64    ┆ i64       ┆ i64     ┆ i64      │
╞═══════╪═════════╪══════════╪═════════════╪═══╪════════╪═══════════╪═════════╪══════════╡
│ 0     ┆ ACTUALS ┆ ABC Inc. ┆ 2021        ┆ … ┆ 145482 ┆ 907874    ┆ 393585  ┆ 451700   │
│ 1     ┆ ACTUALS ┆ ABC Inc. ┆ 2022        ┆ … ┆ 163574 ┆ 696189    ┆ 584222  ┆ 522647   │
│ 2     ┆ ACTUALS ┆ ABC Inc. ┆ 2021        ┆ … ┆ 666610 ┆ 973150    ┆ 589721  ┆ 48077    │
│ 3     ┆ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ … ┆ 328547 ┆ 968013    ┆ 667863  ┆ 503768   │
│ 4     ┆ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ … ┆ 840264 ┆ 29435     ┆ 434182  ┆ 128934   │
└───────┴─────────┴──────────┴─────────────┴───┴────────┴───────────┴─────────┴──────────┘

In [138]:
out = balanceSheet.select(
    "LEDGER",
    "FISCAL_YEAR",
    pl.col("NETWORTH").mean().over("FISCAL_YEAR").alias("networth_by_FY"),
    pl.col("REVENUE")
    .mean()
    .over(["FISCAL_YEAR", "PERIOD"])
    .alias("avg_rev_by_FYAP"),
    pl.col("ASSETS").mean().alias("avg_assets"),
)
print(out)

shape: (100_000, 5)
┌─────────┬─────────────┬────────────────┬─────────────────┬──────────────┐
│ LEDGER  ┆ FISCAL_YEAR ┆ networth_by_FY ┆ avg_rev_by_FYAP ┆ avg_assets   │
│ ---     ┆ ---         ┆ ---            ┆ ---             ┆ ---          │
│ str     ┆ i64         ┆ f64            ┆ f64             ┆ f64          │
╞═════════╪═════════════╪════════════════╪═════════════════╪══════════════╡
│ ACTUALS ┆ 2020        ┆ 498528.963417  ┆ 500178.734118   ┆ 500706.79386 │
│ ACTUALS ┆ 2020        ┆ 498528.963417  ┆ 504533.509133   ┆ 500706.79386 │
│ ACTUALS ┆ 2021        ┆ 499910.464251  ┆ 502578.376791   ┆ 500706.79386 │
│ ACTUALS ┆ 2020        ┆ 498528.963417  ┆ 500137.570938   ┆ 500706.79386 │
│ ACTUALS ┆ 2023        ┆ 497007.493555  ┆ 499761.514699   ┆ 500706.79386 │
│ …       ┆ …           ┆ …              ┆ …               ┆ …            │
│ ACTUALS ┆ 2022        ┆ 501173.793897  ┆ 496805.930039   ┆ 500706.79386 │
│ ACTUALS ┆ 2022        ┆ 501173.793897  ┆ 504434.734793   ┆ 500706.79386 │
│ ACTUALS ┆ 2023        ┆ 497007.493555  ┆ 495342.956584   ┆ 500706.79386 │
│ ACTUALS ┆ 2023        ┆ 497007.493555  ┆ 495342.956584   ┆ 500706.79386 │
│ ACTUALS ┆ 2020        ┆ 498528.963417  ┆ 509464.849498   ┆ 500706.79386 │
└─────────┴─────────────┴────────────────┴─────────────────┴──────────────┘

In [139]:
filtered = balanceSheet.filter(pl.col("LEDGER") == "ACTUALS").select(
    "FISCAL_YEAR",
    "PERIOD",
    "NETWORTH",
)
print(filtered)

shape: (100_000, 3)
┌─────────────┬────────┬──────────┐
│ FISCAL_YEAR ┆ PERIOD ┆ NETWORTH │
│ ---         ┆ ---    ┆ ---      │
│ i64         ┆ i64    ┆ i64      │
╞═════════════╪════════╪══════════╡
│ 2020        ┆ 10     ┆ 630949   │
│ 2020        ┆ 1      ┆ 307809   │
│ 2021        ┆ 12     ┆ 536595   │
│ 2020        ┆ 3      ┆ 400960   │
│ 2023        ┆ 9      ┆ 116069   │
│ …           ┆ …      ┆ …        │
│ 2022        ┆ 7      ┆ 286147   │
│ 2022        ┆ 6      ┆ 541937   │
│ 2023        ┆ 8      ┆ 876970   │
│ 2023        ┆ 8      ┆ 715951   │
│ 2020        ┆ 2      ┆ 226190   │
└─────────────┴────────┴──────────┘

In [140]:
out = filtered.with_columns(
    pl.col(["FISCAL_YEAR","PERIOD","NETWORTH",]).sort_by("PERIOD", descending=False).over("FISCAL_YEAR"),
)
print(out)

shape: (100_000, 3)
┌─────────────┬────────┬──────────┐
│ FISCAL_YEAR ┆ PERIOD ┆ NETWORTH │
│ ---         ┆ ---    ┆ ---      │
│ i64         ┆ i64    ┆ i64      │
╞═════════════╪════════╪══════════╡
│ 2020        ┆ 1      ┆ 307809   │
│ 2020        ┆ 1      ┆ 272713   │
│ 2021        ┆ 1      ┆ 617923   │
│ 2020        ┆ 1      ┆ 34682    │
│ 2023        ┆ 1      ┆ 389798   │
│ …           ┆ …      ┆ …        │
│ 2022        ┆ 12     ┆ 828123   │
│ 2022        ┆ 12     ┆ 225945   │
│ 2023        ┆ 12     ┆ 230376   │
│ 2023        ┆ 12     ┆ 586496   │
│ 2020        ┆ 12     ┆ 858653   │
└─────────────┴────────┴──────────┘

## Polars Data Transformation

#### joins

In [155]:
########################
## ACCOUNTS DataFrame ##
########################
import random
from datetime import datetime

accounts = pl.DataFrame({
    "ID":  list(range(10000, 45000, 1000)),
    "AS_OF_DATE" : datetime(2022, 1, 1),
    "DESCRIPTION" : ["Operating Expenses","Non Operating Expenses","Assets",
                     "Liabilities","Net worth accounts", "Statistical Accounts",
                     "Revenue"] * 5,
    "REGION": ["Region A","Region B","Region C","Region D", "Region E"] * 7,
    "TYPE" : ["E","E","A","L","N","S","R"] * 5,
    "STATUS" : "Active",
    "CLASSIFICATION" : ["OPERATING_EXPENSES","NON-OPERATING_EXPENSES", 
                        "ASSETS","LIABILITIES","NET_WORTH","STATISTICS",
                        "REVENUE"] * 5,
    "CATEGORY" : [
       		"Travel","Payroll","non-Payroll","Allowance","Cash",
       		"Facility","Supply","Services","Investment","Misc.",
       		"Depreciation","Gain","Service","Retired","Fault.",
       		"Receipt","Accrual","Return","Credit","ROI",
       		"Cash","Funds","Invest","Transfer","Roll-over",
       		"FTE","Members","Non_Members","Temp","Contractors",
       		"Sales","Merchant","Service","Consulting","Subscriptions"
       	],
})
accounts.sample(5).with_row_index("Row #")

shape: (5, 9)
┌───────┬───────┬────────────────┬───────────────┬───┬──────┬────────┬───────────────┬─────────────┐
│ Row # ┆ ID    ┆ AS_OF_DATE     ┆ DESCRIPTION   ┆ … ┆ TYPE ┆ STATUS ┆ CLASSIFICATIO ┆ CATEGORY    │
│ ---   ┆ ---   ┆ ---            ┆ ---           ┆   ┆ ---  ┆ ---    ┆ N             ┆ ---         │
│ u32   ┆ i64   ┆ datetime[μs]   ┆ str           ┆   ┆ str  ┆ str    ┆ ---           ┆ str         │
│       ┆       ┆                ┆               ┆   ┆      ┆        ┆ str           ┆             │
╞═══════╪═══════╪════════════════╪═══════════════╪═══╪══════╪════════╪═══════════════╪═════════════╡
│ 0     ┆ 29000 ┆ 2022-01-01     ┆ Statistical   ┆ … ┆ S    ┆ Active ┆ STATISTICS    ┆ ROI         │
│       ┆       ┆ 00:00:00       ┆ Accounts      ┆   ┆      ┆        ┆               ┆             │
│ 1     ┆ 43000 ┆ 2022-01-01     ┆ Statistical   ┆ … ┆ S    ┆ Active ┆ STATISTICS    ┆ Consulting  │
│       ┆       ┆ 00:00:00       ┆ Accounts      ┆   ┆      ┆        ┆               ┆             │
│ 2     ┆ 14000 ┆ 2022-01-01     ┆ Net worth     ┆ … ┆ N    ┆ Active ┆ NET_WORTH     ┆ Cash        │
│       ┆       ┆ 00:00:00       ┆ accounts      ┆   ┆      ┆        ┆               ┆             │
│ 3     ┆ 12000 ┆ 2022-01-01     ┆ Assets        ┆ … ┆ A    ┆ Active ┆ ASSETS        ┆ non-Payroll │
│       ┆       ┆ 00:00:00       ┆               ┆   ┆      ┆        ┆               ┆             │
│ 4     ┆ 37000 ┆ 2022-01-01     ┆ Revenue       ┆ … ┆ R    ┆ Active ┆ REVENUE       ┆ Non_Members │
│       ┆       ┆ 00:00:00       ┆               ┆   ┆      ┆        ┆               ┆             │
└───────┴───────┴────────────────┴───────────────┴───┴──────┴────────┴───────────────┴─────────────┘

In [156]:
##########################
## DEPARTMENT DataFrame ##
##########################
import random
from datetime import datetime

dept = pl.DataFrame({
    "ID":  list(range(1000, 2500, 100)),
    "AS_OF_DATE" : datetime(2022, 1, 1),
    "DESCRIPTION" : ["Sales & Marketing","Human Resource",
                     "Information Technology","Business leaders","other temp"] * 3,
    "REGION": ["Region A","Region B","Region C"] * 5,
    "STATUS" : "Active",
    "CLASSIFICATION" : ["SALES","HR", "IT","BUSINESS","OTHERS"] * 3,
    "TYPE" : ["S","H","I","B","O"] * 3,
    "CATEGORY" : ["sales","human_resource","IT_Staff","business","others"] * 3,
})
dept.sample(5).with_row_index("Row #")

shape: (5, 9)
┌───────┬──────┬───────────────┬───────────────┬───┬────────┬───────────────┬──────┬───────────────┐
│ Row # ┆ ID   ┆ AS_OF_DATE    ┆ DESCRIPTION   ┆ … ┆ STATUS ┆ CLASSIFICATIO ┆ TYPE ┆ CATEGORY      │
│ ---   ┆ ---  ┆ ---           ┆ ---           ┆   ┆ ---    ┆ N             ┆ ---  ┆ ---           │
│ u32   ┆ i64  ┆ datetime[μs]  ┆ str           ┆   ┆ str    ┆ ---           ┆ str  ┆ str           │
│       ┆      ┆               ┆               ┆   ┆        ┆ str           ┆      ┆               │
╞═══════╪══════╪═══════════════╪═══════════════╪═══╪════════╪═══════════════╪══════╪═══════════════╡
│ 0     ┆ 1200 ┆ 2022-01-01    ┆ Information   ┆ … ┆ Active ┆ IT            ┆ I    ┆ IT_Staff      │
│       ┆      ┆ 00:00:00      ┆ Technology    ┆   ┆        ┆               ┆      ┆               │
│ 1     ┆ 1100 ┆ 2022-01-01    ┆ Human         ┆ … ┆ Active ┆ HR            ┆ H    ┆ human_resourc │
│       ┆      ┆ 00:00:00      ┆ Resource      ┆   ┆        ┆               ┆      ┆ e             │
│ 2     ┆ 1900 ┆ 2022-01-01    ┆ other temp    ┆ … ┆ Active ┆ OTHERS        ┆ O    ┆ others        │
│       ┆      ┆ 00:00:00      ┆               ┆   ┆        ┆               ┆      ┆               │
│ 3     ┆ 1700 ┆ 2022-01-01    ┆ Information   ┆ … ┆ Active ┆ IT            ┆ I    ┆ IT_Staff      │
│       ┆      ┆ 00:00:00      ┆ Technology    ┆   ┆        ┆               ┆      ┆               │
│ 4     ┆ 2300 ┆ 2022-01-01    ┆ Business      ┆ … ┆ Active ┆ BUSINESS      ┆ B    ┆ business      │
│       ┆      ┆ 00:00:00      ┆ leaders       ┆   ┆        ┆               ┆      ┆               │
└───────┴──────┴───────────────┴───────────────┴───┴────────┴───────────────┴──────┴───────────────┘

In [157]:
########################
## LOCATION DataFrame ##
########################
import random
from datetime import datetime

location = pl.DataFrame({
    "ID":  list(range(11, 23)),
    "AS_OF_DATE" : datetime(2022, 1, 1),
    "DESCRIPTION" : ["Boston","New York","Philadelphia","Cleveland","Richmond",
                     "Atlanta","Chicago","St. Louis","Minneapolis","Kansas City",
                     "Dallas","San Francisco"],
    "REGION": ["Region A","Region B","Region C","Region D"] * 3,
    "TYPE" : "Physical",
    "CATEGORY" : ["Ship","Recv","Mfg"] * 4
})
location.sample(5).with_row_index("Row #")

shape: (5, 7)
┌───────┬─────┬─────────────────────┬─────────────┬──────────┬──────────┬──────────┐
│ Row # ┆ ID  ┆ AS_OF_DATE          ┆ DESCRIPTION ┆ REGION   ┆ TYPE     ┆ CATEGORY │
│ ---   ┆ --- ┆ ---                 ┆ ---         ┆ ---      ┆ ---      ┆ ---      │
│ u32   ┆ i64 ┆ datetime[μs]        ┆ str         ┆ str      ┆ str      ┆ str      │
╞═══════╪═════╪═════════════════════╪═════════════╪══════════╪══════════╪══════════╡
│ 0     ┆ 16  ┆ 2022-01-01 00:00:00 ┆ Atlanta     ┆ Region B ┆ Physical ┆ Mfg      │
│ 1     ┆ 21  ┆ 2022-01-01 00:00:00 ┆ Dallas      ┆ Region C ┆ Physical ┆ Recv     │
│ 2     ┆ 15  ┆ 2022-01-01 00:00:00 ┆ Richmond    ┆ Region A ┆ Physical ┆ Recv     │
│ 3     ┆ 12  ┆ 2022-01-01 00:00:00 ┆ New York    ┆ Region B ┆ Physical ┆ Recv     │
│ 4     ┆ 14  ┆ 2022-01-01 00:00:00 ┆ Cleveland   ┆ Region D ┆ Physical ┆ Ship     │
└───────┴─────┴─────────────────────┴─────────────┴──────────┴──────────┴──────────┘

In [144]:
######################
## LEDGER DataFrame ##
######################
import random
from datetime import datetime

sampleSize = 100_000
org = "ABC Inc."
ledger_type = "ACTUALS" # BUDGET, STATS are other Ledger types
fiscal_year_from = 2020
fiscal_year_to = 2023
random.seed(123)

ledger = pl.DataFrame({
	"LEDGER" : ledger_type,
	"ORG" : org,
	"FISCAL_YEAR": random.choices(list(range(fiscal_year_from, 
                                          fiscal_year_to+1, 1)),k=sampleSize),
	"PERIOD": random.choices(list(range(1, 12+1, 1)),k=sampleSize),
	"ACCOUNT" : random.choices(accounts["ACCOUNT"], k=sampleSize),
	"DEPT" : random.choices(dept["DEPT"], k=sampleSize),
	"LOCATION" : random.choices(location["LOCATION"], k=sampleSize),
	"POSTED_TOTAL": random.sample(range(1000000), sampleSize)
})
ledger.sample(5).with_row_index("Row #")

shape: (5, 9)
┌───────┬─────────┬──────────┬─────────────┬───┬─────────┬──────┬──────────┬──────────────┐
│ Row # ┆ LEDGER  ┆ ORG      ┆ FISCAL_YEAR ┆ … ┆ ACCOUNT ┆ DEPT ┆ LOCATION ┆ POSTED_TOTAL │
│ ---   ┆ ---     ┆ ---      ┆ ---         ┆   ┆ ---     ┆ ---  ┆ ---      ┆ ---          │
│ u32   ┆ str     ┆ str      ┆ i64         ┆   ┆ i64     ┆ i64  ┆ i64      ┆ i64          │
╞═══════╪═════════╪══════════╪═════════════╪═══╪═════════╪══════╪══════════╪══════════════╡
│ 0     ┆ ACTUALS ┆ ABC Inc. ┆ 2021        ┆ … ┆ 21000   ┆ 2200 ┆ 16       ┆ 724499       │
│ 1     ┆ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ … ┆ 26000   ┆ 2300 ┆ 12       ┆ 233935       │
│ 2     ┆ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ … ┆ 16000   ┆ 2000 ┆ 16       ┆ 399686       │
│ 3     ┆ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ … ┆ 20000   ┆ 1000 ┆ 14       ┆ 859026       │
│ 4     ┆ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ … ┆ 36000   ┆ 1200 ┆ 13       ┆ 345493       │
└───────┴─────────┴──────────┴─────────────┴───┴─────────┴──────┴──────────┴──────────────┘

In [148]:
## using joins

df_inner_ledger_join = ledger.join(accounts, on="ACCOUNT", how="inner")
print(df_inner_ledger_join)

# df_inner_ledger_join = ledger.join(dept, on="DEPT", how="inner")
# print(df_inner_ledger_join)

# df_inner_ledger_join = ledger.join(location, on="LOCATION", how="inner")
# print(df_inner_ledger_join)

shape: (100_000, 15)
┌─────────┬──────────┬─────────────┬────────┬───┬──────┬────────┬────────────────────┬─────────────┐
│ LEDGER  ┆ ORG      ┆ FISCAL_YEAR ┆ PERIOD ┆ … ┆ TYPE ┆ STATUS ┆ CLASSIFICATION     ┆ CATEGORY    │
│ ---     ┆ ---      ┆ ---         ┆ ---    ┆   ┆ ---  ┆ ---    ┆ ---                ┆ ---         │
│ str     ┆ str      ┆ i64         ┆ i64    ┆   ┆ str  ┆ str    ┆ str                ┆ str         │
╞═════════╪══════════╪═════════════╪════════╪═══╪══════╪════════╪════════════════════╪═════════════╡
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 10     ┆ … ┆ A    ┆ Active ┆ ASSETS             ┆ non-Payroll │
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 1      ┆ … ┆ E    ┆ Active ┆ OPERATING_EXPENSES ┆ Travel      │
│ ACTUALS ┆ ABC Inc. ┆ 2021        ┆ 12     ┆ … ┆ N    ┆ Active ┆ NET_WORTH          ┆ Gain        │
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 3      ┆ … ┆ L    ┆ Active ┆ LIABILITIES        ┆ Roll-over   │
│ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ 9      ┆ … ┆ N    ┆ Active ┆ NET_WORTH          ┆ Cash        │
│ …       ┆ …        ┆ …           ┆ …      ┆ … ┆ …    ┆ …      ┆ …                  ┆ …           │
│ ACTUALS ┆ ABC Inc. ┆ 2022        ┆ 7      ┆ … ┆ E    ┆ Active ┆ OPERATING_EXPENSES ┆ Temp        │
│ ACTUALS ┆ ABC Inc. ┆ 2022        ┆ 6      ┆ … ┆ L    ┆ Active ┆ LIABILITIES        ┆ Merchant    │
│ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ 8      ┆ … ┆ A    ┆ Active ┆ ASSETS             ┆ Transfer    │
│ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ 8      ┆ … ┆ N    ┆ Active ┆ NET_WORTH          ┆ Cash        │
│ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ 2      ┆ … ┆ E    ┆ Active ┆ NON-OPERATING_EXPE ┆ Payroll     │
│         ┆          ┆             ┆        ┆   ┆      ┆        ┆ NSES               ┆             │
└─────────┴──────────┴─────────────┴────────┴───┴──────┴────────┴────────────────────┴─────────────┘

#### concatenation

In [149]:
accounts.shape, dept.shape, location.shape, ledger.shape

((35, 8), (15, 8), (12, 6), (100000, 8))

In [154]:
dept

shape: (15, 8)
┌──────┬────────────────┬───────────────┬──────────┬────────┬───────────────┬──────┬───────────────┐
│ DEPT ┆ AS_OF_DATE     ┆ DESCRIPTION   ┆ REGION   ┆ STATUS ┆ CLASSIFICATIO ┆ TYPE ┆ CATEGORY      │
│ ---  ┆ ---            ┆ ---           ┆ ---      ┆ ---    ┆ N             ┆ ---  ┆ ---           │
│ i64  ┆ datetime[μs]   ┆ str           ┆ str      ┆ str    ┆ ---           ┆ str  ┆ str           │
│      ┆                ┆               ┆          ┆        ┆ str           ┆      ┆               │
╞══════╪════════════════╪═══════════════╪══════════╪════════╪═══════════════╪══════╪═══════════════╡
│ 1000 ┆ 2022-01-01     ┆ Sales &       ┆ Region A ┆ Active ┆ SALES         ┆ S    ┆ sales         │
│      ┆ 00:00:00       ┆ Marketing     ┆          ┆        ┆               ┆      ┆               │
│ 1100 ┆ 2022-01-01     ┆ Human         ┆ Region B ┆ Active ┆ HR            ┆ H    ┆ human_resourc │
│      ┆ 00:00:00       ┆ Resource      ┆          ┆        ┆               ┆      ┆ e             │
│ 1200 ┆ 2022-01-01     ┆ Information   ┆ Region C ┆ Active ┆ IT            ┆ I    ┆ IT_Staff      │
│      ┆ 00:00:00       ┆ Technology    ┆          ┆        ┆               ┆      ┆               │
│ 1300 ┆ 2022-01-01     ┆ Business      ┆ Region A ┆ Active ┆ BUSINESS      ┆ B    ┆ business      │
│      ┆ 00:00:00       ┆ leaders       ┆          ┆        ┆               ┆      ┆               │
│ 1400 ┆ 2022-01-01     ┆ other temp    ┆ Region B ┆ Active ┆ OTHERS        ┆ O    ┆ others        │
│      ┆ 00:00:00       ┆               ┆          ┆        ┆               ┆      ┆               │
│ …    ┆ …              ┆ …             ┆ …        ┆ …      ┆ …             ┆ …    ┆ …             │
│ 2000 ┆ 2022-01-01     ┆ Sales &       ┆ Region B ┆ Active ┆ SALES         ┆ S    ┆ sales         │
│      ┆ 00:00:00       ┆ Marketing     ┆          ┆        ┆               ┆      ┆               │
│ 2100 ┆ 2022-01-01     ┆ Human         ┆ Region C ┆ Active ┆ HR            ┆ H    ┆ human_resourc │
│      ┆ 00:00:00       ┆ Resource      ┆          ┆        ┆               ┆      ┆ e             │
│ 2200 ┆ 2022-01-01     ┆ Information   ┆ Region A ┆ Active ┆ IT            ┆ I    ┆ IT_Staff      │
│      ┆ 00:00:00       ┆ Technology    ┆          ┆        ┆               ┆      ┆               │
│ 2300 ┆ 2022-01-01     ┆ Business      ┆ Region B ┆ Active ┆ BUSINESS      ┆ B    ┆ business      │
│      ┆ 00:00:00       ┆ leaders       ┆          ┆        ┆               ┆      ┆               │
│ 2400 ┆ 2022-01-01     ┆ other temp    ┆ Region C ┆ Active ┆ OTHERS        ┆ O    ┆ others        │
│      ┆ 00:00:00       ┆               ┆          ┆        ┆               ┆      ┆               │
└──────┴────────────────┴───────────────┴──────────┴────────┴───────────────┴──────┴───────────────┘

In [158]:
######################
## LEDGER DataFrame ##
######################
import random
from datetime import datetime

sampleSize = 100_000
org = "ABC Inc."
ledger_type = "ACTUALS" # BUDGET, STATS are other Ledger types
fiscal_year_from = 2020
fiscal_year_to = 2023
random.seed(123)

ledger = pl.DataFrame({
	"LEDGER" : ledger_type,
	"ORG" : org,
	"FISCAL_YEAR": random.choices(list(range(fiscal_year_from, 
                                          fiscal_year_to+1, 1)),k=sampleSize),
	"PERIOD": random.choices(list(range(1, 12+1, 1)),k=sampleSize),
	"ACCOUNT" : random.choices(accounts["ID"], k=sampleSize),
	"DEPT" : random.choices(dept["ID"], k=sampleSize),
	"LOCATION" : random.choices(location["ID"], k=sampleSize),
	"POSTED_TOTAL": random.sample(range(1000000), sampleSize)
})
ledger.sample(5).with_row_index("Row #")

shape: (5, 9)
┌───────┬─────────┬──────────┬─────────────┬───┬─────────┬──────┬──────────┬──────────────┐
│ Row # ┆ LEDGER  ┆ ORG      ┆ FISCAL_YEAR ┆ … ┆ ACCOUNT ┆ DEPT ┆ LOCATION ┆ POSTED_TOTAL │
│ ---   ┆ ---     ┆ ---      ┆ ---         ┆   ┆ ---     ┆ ---  ┆ ---      ┆ ---          │
│ u32   ┆ str     ┆ str      ┆ i64         ┆   ┆ i64     ┆ i64  ┆ i64      ┆ i64          │
╞═══════╪═════════╪══════════╪═════════════╪═══╪═════════╪══════╪══════════╪══════════════╡
│ 0     ┆ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ … ┆ 15000   ┆ 1600 ┆ 16       ┆ 392102       │
│ 1     ┆ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ … ┆ 17000   ┆ 1100 ┆ 22       ┆ 771891       │
│ 2     ┆ ACTUALS ┆ ABC Inc. ┆ 2022        ┆ … ┆ 40000   ┆ 1100 ┆ 15       ┆ 143543       │
│ 3     ┆ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ … ┆ 14000   ┆ 2400 ┆ 16       ┆ 413625       │
│ 4     ┆ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ … ┆ 19000   ┆ 1400 ┆ 12       ┆ 187383       │
└───────┴─────────┴──────────┴─────────────┴───┴─────────┴──────┴──────────┴──────────────┘

In [159]:
ledger_budg = pl.DataFrame({
	"LEDGER" : ledger_type,
	"ORG" : org,
	"FISCAL_YEAR": random.choices(list(range(fiscal_year_from, fiscal_year_to+1, 1))
                               ,k=sampleSize),
	"PERIOD": random.choices(list(range(1, 12+1, 1)),k=sampleSize),
	"ACCOUNT" : random.choices(accounts["ID"], k=sampleSize),
	"DEPT" : random.choices(dept["ID"], k=sampleSize),
	"LOCATION" : random.choices(location["ID"], k=sampleSize),
	"POSTED_TOTAL": random.sample(range(1000000), sampleSize)
})
ledger_budg.sample(5).with_row_index("Row #")

shape: (5, 9)
┌───────┬─────────┬──────────┬─────────────┬───┬─────────┬──────┬──────────┬──────────────┐
│ Row # ┆ LEDGER  ┆ ORG      ┆ FISCAL_YEAR ┆ … ┆ ACCOUNT ┆ DEPT ┆ LOCATION ┆ POSTED_TOTAL │
│ ---   ┆ ---     ┆ ---      ┆ ---         ┆   ┆ ---     ┆ ---  ┆ ---      ┆ ---          │
│ u32   ┆ str     ┆ str      ┆ i64         ┆   ┆ i64     ┆ i64  ┆ i64      ┆ i64          │
╞═══════╪═════════╪══════════╪═════════════╪═══╪═════════╪══════╪══════════╪══════════════╡
│ 0     ┆ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ … ┆ 32000   ┆ 1900 ┆ 13       ┆ 331353       │
│ 1     ┆ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ … ┆ 33000   ┆ 1000 ┆ 12       ┆ 742827       │
│ 2     ┆ ACTUALS ┆ ABC Inc. ┆ 2021        ┆ … ┆ 22000   ┆ 1100 ┆ 13       ┆ 971885       │
│ 3     ┆ ACTUALS ┆ ABC Inc. ┆ 2021        ┆ … ┆ 37000   ┆ 1700 ┆ 14       ┆ 450198       │
│ 4     ┆ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ … ┆ 23000   ┆ 1600 ┆ 15       ┆ 646088       │
└───────┴─────────┴──────────┴─────────────┴───┴─────────┴──────┴──────────┴──────────────┘

In [160]:
#########################################
# combined ledger for Actuals and Budget
#########################################
dfLedger = pl.concat([ledger, ledger_budg], how="vertical")
dfLedger.sample(5).with_row_index("Row #")

shape: (5, 9)
┌───────┬─────────┬──────────┬─────────────┬───┬─────────┬──────┬──────────┬──────────────┐
│ Row # ┆ LEDGER  ┆ ORG      ┆ FISCAL_YEAR ┆ … ┆ ACCOUNT ┆ DEPT ┆ LOCATION ┆ POSTED_TOTAL │
│ ---   ┆ ---     ┆ ---      ┆ ---         ┆   ┆ ---     ┆ ---  ┆ ---      ┆ ---          │
│ u32   ┆ str     ┆ str      ┆ i64         ┆   ┆ i64     ┆ i64  ┆ i64      ┆ i64          │
╞═══════╪═════════╪══════════╪═════════════╪═══╪═════════╪══════╪══════════╪══════════════╡
│ 0     ┆ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ … ┆ 27000   ┆ 1600 ┆ 17       ┆ 345418       │
│ 1     ┆ ACTUALS ┆ ABC Inc. ┆ 2022        ┆ … ┆ 12000   ┆ 1200 ┆ 13       ┆ 141989       │
│ 2     ┆ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ … ┆ 41000   ┆ 1200 ┆ 19       ┆ 667832       │
│ 3     ┆ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ … ┆ 26000   ┆ 1500 ┆ 12       ┆ 185257       │
│ 4     ┆ ACTUALS ┆ ABC Inc. ┆ 2021        ┆ … ┆ 43000   ┆ 1700 ┆ 12       ┆ 984628       │
└───────┴─────────┴──────────┴─────────────┴───┴─────────┴──────┴──────────┴──────────────┘

In [161]:
dfLedger.shape

(200000, 8)

#### pivot

In [165]:
df = pl.DataFrame(
    {
        "foo": ["A", "A", "B", "B", "C"],
        "N": [1, 2, 2, 4, 2],
        "bar": ["k", "l", "m", "n", "o"],
    }
)
print(df)

out = df.pivot(index="foo", on="bar", values="N", aggregate_function="sum")
print(out)

shape: (5, 3)
┌─────┬─────┬─────┐
│ foo ┆ N   ┆ bar │
│ --- ┆ --- ┆ --- │
│ str ┆ i64 ┆ str │
╞═════╪═════╪═════╡
│ A   ┆ 1   ┆ k   │
│ A   ┆ 2   ┆ l   │
│ B   ┆ 2   ┆ m   │
│ B   ┆ 4   ┆ n   │
│ C   ┆ 2   ┆ o   │
└─────┴─────┴─────┘
shape: (3, 6)
┌─────┬─────┬─────┬─────┬─────┬─────┐
│ foo ┆ k   ┆ l   ┆ m   ┆ n   ┆ o   │
│ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- │
│ str ┆ i64 ┆ i64 ┆ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╪═════╪═════╪═════╡
│ A   ┆ 1   ┆ 2   ┆ 0   ┆ 0   ┆ 0   │
│ B   ┆ 0   ┆ 0   ┆ 2   ┆ 4   ┆ 0   │
│ C   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 2   │
└─────┴─────┴─────┴─────┴─────┴─────┘

In [167]:
############################
## BalanceSheet DataFrame ##
############################
import random
from datetime import datetime

sampleSize = 100_000
org = "ABC Inc."
ledger_type = "ACTUALS" # BUDGET, STATS are other Ledger types
fiscal_year_from = 2020
fiscal_year_to = 2023
random.seed(123)

balanceSheet = pl.DataFrame({
	"LEDGER" : ledger_type,
	"ORG" : org,
	"FISCAL_YEAR": random.choices(list(range(fiscal_year_from, 
                                          fiscal_year_to+1, 1)),k=sampleSize),
	"PERIOD": random.choices(list(range(1, 12+1, 1)),k=sampleSize),
	"ASSETS": random.sample(range(1000000), sampleSize),
    "LIABILITY": random.sample(range(1000000), sampleSize),
    "REVENUE": random.sample(range(1000000), sampleSize),
    "NETWORTH": random.sample(range(1000000), sampleSize),
})
print(balanceSheet.sample(5).with_row_index("Row #"))

shape: (5, 9)
┌───────┬─────────┬──────────┬─────────────┬───┬────────┬───────────┬─────────┬──────────┐
│ Row # ┆ LEDGER  ┆ ORG      ┆ FISCAL_YEAR ┆ … ┆ ASSETS ┆ LIABILITY ┆ REVENUE ┆ NETWORTH │
│ ---   ┆ ---     ┆ ---      ┆ ---         ┆   ┆ ---    ┆ ---       ┆ ---     ┆ ---      │
│ u32   ┆ str     ┆ str      ┆ i64         ┆   ┆ i64    ┆ i64       ┆ i64     ┆ i64      │
╞═══════╪═════════╪══════════╪═════════════╪═══╪════════╪═══════════╪═════════╪══════════╡
│ 0     ┆ ACTUALS ┆ ABC Inc. ┆ 2021        ┆ … ┆ 827789 ┆ 691829    ┆ 827375  ┆ 466027   │
│ 1     ┆ ACTUALS ┆ ABC Inc. ┆ 2021        ┆ … ┆ 992001 ┆ 810592    ┆ 385309  ┆ 516774   │
│ 2     ┆ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ … ┆ 785026 ┆ 578670    ┆ 726848  ┆ 349705   │
│ 3     ┆ ACTUALS ┆ ABC Inc. ┆ 2023        ┆ … ┆ 386270 ┆ 638055    ┆ 913744  ┆ 194642   │
│ 4     ┆ ACTUALS ┆ ABC Inc. ┆ 2020        ┆ … ┆ 811221 ┆ 965228    ┆ 961978  ┆ 938885   │
└───────┴─────────┴──────────┴─────────────┴───┴────────┴───────────┴─────────┴──────────┘

In [169]:
out = balanceSheet.pivot(index="FISCAL_YEAR", on="PERIOD", values="NETWORTH", aggregate_function="median")
print(out)

shape: (4, 13)
┌─────────────┬──────────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ FISCAL_YEAR ┆ 10       ┆ 1        ┆ 12       ┆ … ┆ 4        ┆ 8        ┆ 2        ┆ 7        │
│ ---         ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ i64         ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞═════════════╪══════════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 2020        ┆ 519604.0 ┆ 512152.0 ┆ 491098.5 ┆ … ┆ 487557.0 ┆ 494666.0 ┆ 491307.0 ┆ 494794.0 │
│ 2021        ┆ 514325.0 ┆ 493920.5 ┆ 502130.5 ┆ … ┆ 483349.0 ┆ 493417.0 ┆ 503360.5 ┆ 514359.0 │
│ 2023        ┆ 490111.5 ┆ 500121.0 ┆ 497847.5 ┆ … ┆ 484256.0 ┆ 506810.0 ┆ 486628.5 ┆ 487821.0 │
│ 2022        ┆ 490166.0 ┆ 503240.0 ┆ 506036.0 ┆ … ┆ 509159.0 ┆ 487072.5 ┆ 495781.5 ┆ 507723.5 │
└─────────────┴──────────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [171]:
# lazy execution
q = (balanceSheet.lazy()
     .collect()
     .pivot(index="FISCAL_YEAR", on="PERIOD", values="NETWORTH", aggregate_function="sum")
     .lazy()
)

out = q.collect()
print(out)

shape: (4, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ FISCAL_YE ┆ 10        ┆ 1         ┆ 12        ┆ … ┆ 4         ┆ 8         ┆ 2         ┆ 7        │
│ AR        ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ ---       ┆ i64       ┆ i64       ┆ i64       ┆   ┆ i64       ┆ i64       ┆ i64       ┆ i64      │
│ i64       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2020      ┆ 108224941 ┆ 108038900 ┆ 104273367 ┆ … ┆ 972685995 ┆ 101209961 ┆ 103032396 ┆ 10381162 │
│           ┆ 5         ┆ 1         ┆ 8         ┆   ┆           ┆ 2         ┆ 6         ┆ 31       │
│ 2021      ┆ 108108676 ┆ 104743057 ┆ 104492372 ┆ … ┆ 100276120 ┆ 101698492 ┆ 104962643 ┆ 10383994 │
│           ┆ 5         ┆ 7         ┆ 9         ┆   ┆ 2         ┆ 2         ┆ 3         ┆ 32       │
│ 2023      ┆ 102746210 ┆ 105297297 ┆ 103340523 ┆ … ┆ 103721463 ┆ 106394484 ┆ 104096539 ┆ 10014053 │
│           ┆ 5         ┆ 9         ┆ 5         ┆   ┆ 5         ┆ 2         ┆ 8         ┆ 61       │
│ 2022      ┆ 102879002 ┆ 103223842 ┆ 100630852 ┆ … ┆ 105154873 ┆ 105099774 ┆ 105418639 ┆ 10246101 │
│           ┆ 9         ┆ 6         ┆ 5         ┆   ┆ 5         ┆ 6         ┆ 1         ┆ 72       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

#### melts

In [175]:
df = pl.DataFrame(
    {
        "A": ["a", "b", "a"],
        "B": [1, 3, 5],
        "C": [10, 11, 12],
        "D": [2, 4, 6],
    }
)
print(df)

out = df.unpivot(index=["A", "B"], on=["C", "D"])
print(out)

shape: (3, 4)
┌─────┬─────┬─────┬─────┐
│ A   ┆ B   ┆ C   ┆ D   │
│ --- ┆ --- ┆ --- ┆ --- │
│ str ┆ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╪═════╡
│ a   ┆ 1   ┆ 10  ┆ 2   │
│ b   ┆ 3   ┆ 11  ┆ 4   │
│ a   ┆ 5   ┆ 12  ┆ 6   │
└─────┴─────┴─────┴─────┘
shape: (6, 4)
┌─────┬─────┬──────────┬───────┐
│ A   ┆ B   ┆ variable ┆ value │
│ --- ┆ --- ┆ ---      ┆ ---   │
│ str ┆ i64 ┆ str      ┆ i64   │
╞═════╪═════╪══════════╪═══════╡
│ a   ┆ 1   ┆ C        ┆ 10    │
│ b   ┆ 3   ┆ C        ┆ 11    │
│ a   ┆ 5   ┆ C        ┆ 12    │
│ a   ┆ 1   ┆ D        ┆ 2     │
│ b   ┆ 3   ┆ D        ┆ 4     │
│ a   ┆ 5   ┆ D        ┆ 6     │
└─────┴─────┴──────────┴───────┘

In [176]:
out = balanceSheet.unpivot(index=["FISCAL_YEAR", "PERIOD"], on=["NETWORTH"])
print(out)

shape: (100_000, 4)
┌─────────────┬────────┬──────────┬────────┐
│ FISCAL_YEAR ┆ PERIOD ┆ variable ┆ value  │
│ ---         ┆ ---    ┆ ---      ┆ ---    │
│ i64         ┆ i64    ┆ str      ┆ i64    │
╞═════════════╪════════╪══════════╪════════╡
│ 2020        ┆ 10     ┆ NETWORTH ┆ 630949 │
│ 2020        ┆ 1      ┆ NETWORTH ┆ 307809 │
│ 2021        ┆ 12     ┆ NETWORTH ┆ 536595 │
│ 2020        ┆ 3      ┆ NETWORTH ┆ 400960 │
│ 2023        ┆ 9      ┆ NETWORTH ┆ 116069 │
│ …           ┆ …      ┆ …        ┆ …      │
│ 2022        ┆ 7      ┆ NETWORTH ┆ 286147 │
│ 2022        ┆ 6      ┆ NETWORTH ┆ 541937 │
│ 2023        ┆ 8      ┆ NETWORTH ┆ 876970 │
│ 2023        ┆ 8      ┆ NETWORTH ┆ 715951 │
│ 2020        ┆ 2      ┆ NETWORTH ┆ 226190 │
└─────────────┴────────┴──────────┴────────┘

## Polars SQL

#### how to use Lazy API

```test
the lazy API allows Polars to apply automatic query optimization with the query optimizer
the lazy API allows you to work with larger than memory datasets using streaming
the lazy API can catch schema errors before processing the data
In the ideal case we use the lazy API right from a file as the query optimizer may help us to reduce the amount of data we read from the file.

scan_csv or scan_parquet or scan_xxx
import polars as pl

from ..paths import DATA_DIR

q1 = (
    pl.scan_csv(f"{DATA_DIR}/reddit.csv")
    .with_columns(pl.col("name").str.to_uppercase())
    .filter(pl.col("comment_karma") > 0)
)
If we were to run the code above on the Reddit CSV the query would not be evaluated. Instead Polars takes each line of code, adds it to the internal query graph and optimizes the query graph.

import polars as pl

from ..paths import DATA_DIR

q4 = (
    pl.scan_csv(f"{DATA_DIR}/reddit.csv")
    .with_columns(pl.col("name").str.to_uppercase())
    .filter(pl.col("comment_karma") > 0)
    .collect()
)
Execution on larger-than-memory (RAM) data analytics
If your data requires more memory than you have available Polars may be able to process the data in batches using streaming mode. To use streaming mode you simply pass the streaming=True argument to collect

import polars as pl

from ..paths import DATA_DIR

q5 = (
    pl.scan_csv(f"{DATA_DIR}/reddit.csv")
    .with_columns(pl.col("name").str.to_uppercase())
    .filter(pl.col("comment_karma") > 0)
    .collect(streaming=True)
)
Execution on a partial dataset

While you're writing, optimizing or checking your query on a large dataset, querying all available data may lead to a slow development process.

You can instead execute the query with the .fetch method. The .fetch method takes a parameter n_rows and tries to 'fetch' that number of rows at the data source. The number of rows cannot be guaranteed, however, as the lazy API does not count how many rows there are at each stage of the query.

Here we "fetch" 100 rows from the source file and apply the predicates.

import polars as pl

from ..paths import DATA_DIR

q9 = (
    pl.scan_csv(f"{DATA_DIR}/reddit.csv")
    .with_columns(pl.col("name").str.to_uppercase())
    .filter(pl.col("comment_karma") > 0)
    .fetch(n_rows=int(100))
)
TODO: cover streaming topic
TODO: cover sinking to a a file
TODO: all topics from Lazy API Chapter
```

In [184]:
#### Query Optimization
import polars as pl

q3 = pl.DataFrame({"foo": ["a", "b", "c"], "bar": [0, 1, 2]}).lazy()

# 1. Use collect_schema() to avoid PerformanceWarning
print(q3.collect_schema())

# 2. Use explain() instead of describe_optimized_plan()
print("\n--- Optimized Plan ---")
print(q3.explain())

print("\n--- Unoptimized Plan ---")
print(q3.explain(optimized=False))

## query example with updated pivot syntax
lazy_eager_query = (
    pl.DataFrame(
        {
            "id": ["a", "b", "c"],
            "month": ["jan", "feb", "mar"],
            "values": [0, 1, 2],
        }
    )
    .lazy()
    .with_columns((2 * pl.col("values")).alias("double_values"))
    .collect()
    .pivot(
        index="id",
        on="month",              # ✅ Renamed from 'columns' to 'on' in Polars 1.0+
        values="double_values",
        aggregate_function="first"
    )
    .lazy()
    .filter(pl.col("mar").is_null())
    .collect()
)
print("\n--- Pivot Result ---")
print(lazy_eager_query)

# 3. Skip show_graph() entirely since Graphviz is not installed.
#    Use explain(format="tree") as a dependency-free alternative.
print("\n--- Tree View (No Graphviz Required) ---")
print(q3.explain(format="tree", optimized=False))

Schema({'foo': String, 'bar': Int64})

--- Optimized Plan ---
DF ["foo", "bar"]; PROJECT */2 COLUMNS

--- Unoptimized Plan ---
DF ["foo", "bar"]; PROJECT */2 COLUMNS

--- Pivot Result ---
shape: (2, 4)
┌─────┬──────┬──────┬──────┐
│ id  ┆ jan  ┆ feb  ┆ mar  │
│ --- ┆ ---  ┆ ---  ┆ ---  │
│ str ┆ i64  ┆ i64  ┆ i64  │
╞═════╪══════╪══════╪══════╡
│ a   ┆ 0    ┆ null ┆ null │
│ b   ┆ null ┆ 2    ┆ null │
└─────┴──────┴──────┴──────┘

--- Tree View (No Graphviz Required) ---
                 0
   ┌─────────────────────────
   │
   │  ╭─────────────────────╮
   │  │ DF ["foo", "bar"]   │
 0 │  │ PROJECT */2 COLUMNS │
   │  ╰─────────────────────╯